import { BlogPost } from "../../types/blog";

function createBlock(text: string, style = "normal", key = Math.random().toString(36).substring(7)) {
  return {
    _key: key,
    _type: "block",
    style,
    markDefs: [],
    children: [{ _key: `${key}-c`, _type: "span", marks: [], text }],
  };
}

export const ARTICLES_11_TO_20: BlogPost[] = [
  {
    _id: "blog-brand-identity-design-systems",
    title: "Why Do Some Logos Stick in Your Mind?",
    title_az: "Bəzi loqolar niyə yadda qalır?",
    slug: { _type: "slug", current: "why-some-logos-are-impossible-to-forget" },
    slug_az: { _type: "slug", current: "bezi-loqolar-niye-unudulmur" },
    originalSlug: "brand-identity-design-systems",
    category: "Creative & Culture",
    category_az: "Kreativ və Mədəniyyət",
    excerpt: "Gestalt closure, radical simplicity, and the Von Restorff Isolation Effect: How FedEx, Apple, and Nike engineered symbols that burn into human neural circuitry.",
    excerpt_az: "Gestalt tamamlama, radikal sadəlik və Von Restorff Təcrid Effekti: FedEx, Apple və Nike-ın insan neyronlarına həkk olunan simvolları necə yaratdığı.",
    coverImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "image-2d4d34a5d0d7c92a8a12c7d9bd12cfbe4d0ef277-1376x768-jpg" },
      alt: "Abstract human brain silhouette composed of intertwining geometric shapes and curves",
      url: "https://cdn.sanity.io/images/0lqwkcmg/production/2d4d34a5d0d7c92a8a12c7d9bd12cfbe4d0ef277-1376x768.jpg",
    },
    publishDate: "2026-03-26",
    readTime: "14 min read",
    featured: true,
    tags: ["Logo Design", "Branding", "Gestalt Psychology", "Visual Identity", "Memorability"],
    body: [
      createBlock("Why Are Some Logos Impossible to Forget?", "h2"),
      createBlock("Think of the Nike Swoosh. Think of the Apple with a missing bite. Think of the hidden white arrow between the 'E' and 'x' in FedEx. You can sketch these marks from memory in two seconds on a napkin. Now try sketching the logo of your local health insurance company. You probably can't even remember its general shape, let alone draw it. I've always found it fascinating how our brains act as ruthless visual bouncers, letting only a tiny fraction of brand marks into our long-term memory club."),
      createBlock("Why do certain visual marks achieve permanent neural residency in billions of human brains while others evaporate instantly? The answer lies far beyond mere 'good aesthetics.' It's rooted in the hardwired psychology of visual perception."),
      createBlock("1. The Gestalt Law of Closure (The Secret Reward of Discovery)", "h3"),
      createBlock("The FedEx logo, designed by Lindon Leader in 1994, is a textbook masterpiece of Gestalt Closure. The negative space between the capital 'E' and lowercase 'x' forms a razor-sharp forward-pointing arrow. But here's the genius part: they don't explicitly highlight it. When a viewer discovers that hidden arrow for the first time, their brain experiences a delightful moment of cognitive completion."),
      createBlock("That 'Aha!' moment permanently encodes the logo into episodic memory. The brain loves solving small visual riddles. When a brand offers that intellectual reward, the symbol becomes indelible. The Amazon logo does something similar—the orange arrow connecting 'A' to 'Z' perfectly mimics a satisfied smile while communicating their vast inventory."),
      createBlock("2. Radical Reducibility: The 5-Second Billboard Test", "h3"),
      createBlock("Legendary designer Paul Rand, the mind behind IBM and ABC's logos, noted: 'A logo does not sell; it identifies.' The most memorable logos on earth are radically simple geometric silhouettes. They survive at 16x16 pixels on a smartwatch screen or on a highway billboard viewed at 70 mph for half a second."),
      createBlock("Complexity is the enemy of retention. In a 2015 study by Signs.com, 150 Americans were asked to draw famous logos from memory. The results were hilariously chaotic for complex marks like Starbucks, but for Apple and Target? Near perfection. If your brand mark requires more than three pen strokes, you are actively fighting the limitations of human visual memory."),
      createBlock("3. The Von Restorff Effect (Isolation)", "h3"),
      createBlock("Coined by German psychiatrist Hedwig von Restorff in 1933, the isolation effect states that an item that stands out like a sore thumb is more likely to be remembered. When every tech company in the late 90s was designing complex, glowing, 3D globes for their logos, Apple went with a flat, monochromatic fruit missing a bite. The 'bite' wasn't just to prevent it from looking like a cherry; it was the visual anomaly that made the silhouette completely unique. To be memorable, you must have the courage to be visually isolated.")
    ],
    body_az: [
      createBlock("Bəzi Loqolar Niyə Heç Vaxt Yaddan Çıxmır?", "h2"),
      createBlock("Nike-ın qanadını (Swoosh) xatırlayın. Apple-ın dişlənmiş almasını xatırlayın. FedEx-də 'E' və 'x' arasındakı gizli oxu xatırlayın. Siz bu simvolları iki saniyə içində salfet üzərində çəkə bilərsiniz. İndi isə yerli sığorta şirkətinizin və ya bankınızın loqosunu çəkməyə çalışın. Çox güman ki, formasını belə xatırlamırsınız. Beynimizin vizual qapıçı kimi davranıb, yalnız çox kiçik sayda brend işarələrini uzunmüddətli yaddaş klubuna buraxması məni həmişə heyrətləndirib."),
      createBlock("Bəzi vizual işarələr milyardlarla insanın beynində daimi neyron yuvası qurduğu halda, digərləri niyə dərhal yaddaşdan silinir? Cavab sadəcə 'yaxşı estetika'dan çox uzaqdır. Bu, birbaşa vizual qavrayışın köklü psixologiyasına əsaslanır."),
      createBlock("1. Gestalt Qapanma Qanunu (Kəşfin Gizli Mükafatı)", "h3"),
      createBlock("1994-cü ildə Lindon Leader tərəfindən dizayn edilmiş FedEx loqosu Gestalt Qapanma qanununun şah əsəridir. Böyük 'E' və kiçik 'x' arasındakı mənfi boşluq irəliyə yönəlmiş iti ox formalaşdırır. Lakin buradakı dahilik ondadır ki, onlar bu oxu açıq-aşkar vurğulamırlar. İzləyici bu gizli oxu ilk dəfə görəndə beyni xoş idrak həzzi yaşayır."),
      createBlock("Həmin 'Aha!' anı loqonu epizodik yaddaşa həmişəlik həkk edir. Beyin kiçik vizual tapmacaları həll etməyi sevir. Brend bu intellektual mükafatı təqdim etdikdə simvol silinməz olur. Amazon loqosu da oxşar iş görür — 'A'-dan 'Z'-yə uzanan narıncı ox nəhəng çeşidi ifadə etməklə yanaşı, məmnun bir gülümsəməni təqlid edir."),
      createBlock("2. Radikal Sadələşdirmə: 5 Saniyəlik Lövhə Testi", "h3"),
      createBlock("IBM və ABC loqolarının müəllifi, əfsanəvi dizayner Paul Rand qeyd edirdi: 'Loqo satmır; o, tanıdır.' Dünyanın ən yaddaqalan loqoları radikal dərəcədə sadə həndəsi siluetlərdir. Onlar ağıllı saat ekranında 16x16 piksel ölçüsündə də, magistral yolda saatda 100 km sürətlə ötüb keçərkən yarım saniyəlik baxışla da sağ qalırlar."),
      createBlock("Mürəkkəblik yaddaşın düşmənidir. 2015-ci ildə Signs.com-un apardığı bir tədqiqatda 150 amerikalıdan yaddaşdan məşhur loqoları çəkmək xahiş olunmuşdu. Nəticələr Starbucks kimi mürəkkəb işarələr üçün gülünc dərəcədə xaotik idi, lakin Apple və Target üçün? Demək olar ki, mükəmməl. Əgər brend işarəniz üçdən çox qələm hərəkəti tələb edirsə, siz insan vizual yaddaşının məhdudiyyətlərinə qarşı mübarizə aparırsınız."),
      createBlock("3. Von Restorff Effekti (Təcrid Olunma)", "h3"),
      createBlock("1933-cü ildə alman psixiatrı Hedviq von Restorff tərəfindən irəli sürülmüş təcrid effekti bildirir ki, fərqlənən, seçilən bir obyektin yadda qalma ehtimalı daha yüksəkdir. 90-cı illərin sonlarında hər bir texnologiya şirkəti mürəkkəb, parıldayan 3D qlobuslar dizayn edərkən, Apple düz, monoxrom, bir tərəfi dişlənmiş meyvə seçdi. O 'dişlək' sadəcə albalıya bənzəməmək üçün deyildi; o, silueti tamamilə unikal edən vizual anomaliya idi. Yaddaqalan olmaq üçün vizual olaraq təcrid olunmağa cəsarətiniz çatmalıdır.")
    ]
  },
  {
    _id: "blog-aida-framework-performance-creative-attention-action",
    title: "How Do You Make a Visual Memorable?",
    title_az: "Vizualı necə yadda qalan edək?",
    slug: { _type: "slug", current: "what-is-visual-metaphor-advertising" },
    slug_az: { _type: "slug", current: "vizual-metafora-ve-reklamlar" },
    originalSlug: "the-aida-framework",
    category: "Marketing Psychology",
    category_az: "Marketinq Psixologiyası",
    excerpt: "Why literal ads are forgotten in seconds while visual metaphors trigger mental closure and permanent memory encoding: Case studies from Apple, Heinz, and The Economist.",
    excerpt_az: "Niyə hərfi reklamlar saniyələr içində unudulur, vizual metaforalar isə beyində daimi yaddaş izi buraxır: Apple, Heinz və The Economist-dən real nümunələr.",
    coverImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "image-4ace70af622e0b21d865ce382d6888cfce744aec-1366x768-jpg" },
      alt: "Surrealist editorial photo of a sliced ketchup bottle revealing fresh tomato cross-sections",
      url: "https://cdn.sanity.io/images/0lqwkcmg/production/4ace70af622e0b21d865ce382d6888cfce744aec-1366x768.jpg",
    },
    publishDate: "2026-03-10",
    readTime: "11 min read",
    featured: true,
    tags: ["Visual Metaphor", "Creative Advertising", "AIDA Framework", "Art Direction", "Brand Memorability"],
    body: [
      createBlock("What Is Visual Metaphor and Why Does It Make Ads Easier to Remember?", "h2"),
      createBlock("Consider two advertisements for a noise-canceling headphone:"),
      createBlock("Ad A displays a photo of the headphones with a bulleted list: 'Active Noise Cancellation, 40dB reduction, 30-hour battery life.'"),
      createBlock("Ad B shows an opera singer screaming with all her might directly into a passenger's ear on a crowded subway—except the passenger is blissfully sleeping wearing the headphones, undisturbed."),
      createBlock("Which ad do you remember six months later? Ad B, without question. I often tell junior art directors that the first rule of advertising is to stop acting like an engineer. This is the superpower of Visual Metaphor."),
      createBlock("1. The Mechanism of Mental Closure (Gestalt Inferences)", "h3"),
      createBlock("Literal advertising hands the viewer the conclusion on a silver platter. Because the brain does not have to expend any cognitive effort to decode it, the message passes through working memory and is instantly discarded. You see it, you process it, you forget it."),
      createBlock("A visual metaphor, however, creates an intentional cognitive riddle. When the viewer sees an unexpected combination (like Heinz slicing a fresh tomato into the shape of a ketchup bottle), the brain performs a micro-second of cognitive puzzle-solving. When the meaning clicks, the brain releases a micro-dose of dopamine rewarding 'Mental Closure'. That pleasant realization anchors the memory deeply into long-term recall. You aren't just looking at an ad; you are participating in a joke where you are the only one who gets the punchline."),
      createBlock("2. The Evolution of the AIDA Framework", "h3"),
      createBlock("E. St. Elmo Lewis formulated the classic AIDA model in 1898: Attention, Interest, Desire, Action. In the modern visual economy saturated with 10,000 daily ad impressions, literal messaging fails at Step 1 (Attention). Visual metaphors satisfy all four stages simultaneously:"),
      createBlock("• Attention: The visual anomaly arrests thumb-scrolling behavior. A giant elephant in a living room? That stops a scroll."),
      createBlock("• Interest: The riddle invites cognitive resolution. Why is the elephant there?"),
      createBlock("• Desire: The emotional benefit is dramatized rather than described."),
      createBlock("• Action: The brand name is cemented as the hero of the story."),
      createBlock("Show, Don't Tell", "h3"),
      createBlock("Do not state your product's benefit. Embody it in a striking visual contrast that respects the viewer's intelligence. Do you want to be a boring bulleted list, or do you want to be the ad they talk about at dinner?")
    ],
    body_az: [
      createBlock("Vizual Metafora Nədir və Reklamları Niyə Yadda Qalan Edir?", "h2"),
      createBlock("Səs-küyü ləğv edən qulaqlıq üçün iki reklamı nəzərdən keçirin:"),
      createBlock("Reklam A: Qulaqlığın şəkli və siyahı: 'Aktiv Səs Ləğvetmə, 40dB azalma, 30 saat batareya ömrü.'"),
      createBlock("Reklam B: Sıx metro vaqonunda sərnişinin qulağına var gücü ilə qışqıran opera müğənnisi — lakin qulaqlıq taxmış sərnişin heç nə eşitmədən rahat yatır."),
      createBlock("Altı aydan sonra hansı reklamı xatırlayacaqsınız? Şübhəsiz ki, Reklam B-ni. Mən tez-tez gənc art direktorlara deyirəm ki, reklamın ilk qaydası mühəndis kimi davranmağı dayandırmaqdır. Bu, Vizual Metaforanın fövqəltəbii gücüdür."),
      createBlock("1. İntellektual Qapanma Mexanizmi (Gestalt Nəticələri)", "h3"),
      createBlock("Hərfi reklam nəticəni tamaşaçıya gümüş nimçədə təqdim edir. Beyin onu deşifrə etmək üçün heç bir idrak zəhməti çəkmədiyindən, mesaj qısamüddətli yaddaşdan keçir və dərhal silinir. Onu görürsən, anlayırsan və anında unudursan."),
      createBlock("Vizual metafora isə şüurlu idrak tapmacası yaradır. Tamaşaçı gözlənilməz kombinasiya gördükdə (məsələn, Heinz təzə pomidoru ketçup şüşəsi şəklində dilimlədikdə), beyin mikro-saniyəlik tapmaca həll edir. Məna aydınlaşanda beyin 'Zehni Qapanma'nı dopaminlə mükafatlandırır. Bu xoş dərketmə yaddaşı uzunmüddətli xatirələrdə möhkəmləndirir. Siz sadəcə reklama baxmırsınız; siz sonluğu tapan şəxs olaraq bir zarafatın parçası olursunuz."),
      createBlock("2. AIDA Modelinin Təkamülü", "h3"),
      createBlock("E. St. Elmo Lewis 1898-ci ildə klassik AIDA modelini formalaşdırdı: Diqqət, Maraq, Arzu, Fəaliyyət. Gündəlik 10,000 reklam təəssüratı ilə dolu müasir vizual iqtisadiyyatda hərfi mesajlar elə 1-ci mərhələdə uğursuzluğa düçar olur. Vizual metaforalar isə dörd mərhələni eyni vaxtda təmin edir:"),
      createBlock("• Diqqət: Vizual anomaliya barmaq sürüşdürmə vərdişini dayandırır. Qonaq otağında nəhəng bir fil? Bu mütləq baxışları saxlayır."),
      createBlock("• Maraq: Tapmaca idrak həllinə dəvət edir. Fil niyə ordadır?"),
      createBlock("• Arzu: Emosional fayda sadəcə təsvir edilmir, dramatikləşdirilir."),
      createBlock("• Fəaliyyət: Brend adı hekayənin qəhrəmanı kimi möhkəmlənir."),
      createBlock("Təsvir Etməyin, Göstərin", "h3"),
      createBlock("Məhsulunuzun faydasını birbaşa deməyin. İzləyicinin intellektinə hörmət edən təsirli vizual kontrast vasitəsilə onu canlandırın. Siz darıxdırıcı siyahı olmaq istəyirsiniz, yoxsa şam yeməyində insanların müzakirə etdiyi bir reklam?")
    ],
  }
];
