import { BlogPost } from "../../types/blog";

function createBlock(text: string, style = "normal", key = Math.random().toString(36).substring(7)) {
  return {
    _key: key,
    _type: "block",
    style,
    markDefs: [],
    children: [{ _key: `${key}-c`, _type: "span", marks: [], text }],
  };
}

export const ARTICLES_VIRAL_MASTERCLASS: BlogPost[] = [
  {
    _id: "blog-masterclass-maas-danisigi-psixologiyasi-harvard-metodu",
    title: "Azərbaycanda Maaş Danışığı Sənəti: Şirkətlərin \"Maaş Gözləntiniz Nədir?\" Tələsinə Qarşı Harvard Metodologiyası və Davranış Psixologiyası",
    title_az: "Azərbaycanda Maaş Danışığı Sənəti: Şirkətlərin \"Maaş Gözləntiniz Nədir?\" Tələsinə Qarşı Harvard Metodologiyası və Davranış Psixologiyası",
    slug: { _type: "slug", current: "maas-danisigi-psixologiyasi-harvard-metodu" },
    slug_az: { _type: "slug", current: "maas-danisigi-psixologiyasi-harvard-metodu" },
    originalSlug: "maas-danisigi-psixologiyasi-harvard-metodu",
    category: "Karyera & Danışıqlar",
    category_az: "Karyera & Danışıqlar",
    excerpt: "Müsahibədə ilk rəqəmi kim deməlidir? Daniel Kanemanın Lövbər effekti, FTB danışıqçısı Kris Vossun sualları və yerli şirkətlərdən +500 AZN yüksək təklif almağın dəqiq skriptləri.",
    excerpt_az: "Müsahibədə ilk rəqəmi kim deməlidir? Daniel Kanemanın Lövbər effekti, FTB danışıqçısı Kris Vossun sualları və yerli şirkətlərdən +500 AZN yüksək təklif almağın dəqiq skriptləri.",
    coverImage: {
      _type: "image",
      url: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=1200&h=675&fit=crop&auto=format",
      alt: "Azərbaycanda Maaş Danışığı Sənəti: Şirkətlərin \"Maaş Gözləntiniz Nədir?\" Tələsinə Qarşı Harvard Metodologiyası və Davranış Psixologiyası",
    },
    publishDate: "26 Avqust 2026",
    readTime: "8 dəq oxu",
    featured: true,
    tags: ["karyera", "maas", "musahibe", "hr", "psixologiya", "danisiqlar"],
    body: [
      createBlock("Gəlin səmimi olaq: Azərbaycanda əmək bazarında ən böyük tabulardan biri maaş haqqında açıq danışmaqdır.", "normal"),
      createBlock("Uşaqlıqdan bəri bizə aşılanan \"pulu çox soruşmaq ayıbdır\" və ya \"işi verən nə verərsə, ona qane ol\" təfəkkürü peşəkar həyatımıza keçəndə böyük bir maliyyə fəlakətinə çevrilir. Nəticədə eyni təcrübəyə və bacarığa malik iki mütəxəssisdən biri ayda 700 AZN alarkən, digəri düzgün danışıq apardığı üçün eyni şirkətdə 1600 AZN qazanır.", "normal"),
      createBlock("Çoxları düşünür ki, maaş danışığı sadəcə bəxt və ya \"tərs durmaq\" məsələsidir. Lakin Harvard Universitetinin danışıqlar üzrə professoru Dikpak Malhotra (Deepak Malhotra) və Nobel mükafatçısı Daniel Kanemanın (Daniel Kahneman) araşdırmaları göstərir ki, maaş danışığı 100% davranış iqtisadiyyatı və psixologiyaya əsaslanan idarəolunan bir prosesdir.", "normal"),
      createBlock("1. Masanın Digər Tərəfi: HR və Rəhbər Əslində Nə Düşünür?", "h3"),
      createBlock("LinkedIn-in \"Global Talent Trends\" hesabatına görə, işəgötürənlərin 73%-nin hər vakansiya üçün əvvəlcədən təsdiqlənmiş \"Büdcə Dəhlizi\" (Salary Band) olur.", "normal"),
      createBlock("Məsələn, şirkət bir qrafik dizayner və ya marketoloq üçün büdcədə 900 – 1400 AZN ayırıb.", "normal"),
      createBlock("* Əgər siz müsahibədə ilk olaraq \"Mənim üçün 800 AZN bəs edər\" desəniz, HR daxilən sevinəcək və şirkətin büdcəsinə 600 AZN qənaət etdiyi üçün rəhbərlikdən xal qazanacaq.", "normal"),
      createBlock("* Əgər \"1400 AZN\" desəniz və bunu düzgün əsaslandırsanız, şirkət yenə də sizi işə götürəcək, çünki bu məbləğ onların onsuz da təsdiqlənmiş dəhlizinin içindədir.", "normal"),
      createBlock("2. \"Lövbər Effekti\" (Anchoring Bias): İlk Rəqəmi Kim Deməlidir?", "h3"),
      createBlock("Davranış iqtisadiyyatının ən məşhur qanunlarından biri Daniel Kaneman və Amos Tverskinin kəşf etdiyi Lövbər Effektidir.", "normal"),
      createBlock("Bu qanuna görə, danışıq masasında səslənən ilk rəqəm (lövbər) bütün sonrakı müzakirələrin cazibə mərkəzinə çevrilir. Əgər qarşı tərəf \"Biz bu vəzifə üçün 600 AZN düşünürük\" deyərək lövbəri aşağı atsa, sizin oradan 1200 AZN-ə qalxmağınız psixoloji cəhətdən 10 qat çətinləşir.", "normal"),
      createBlock("Harvard Danışıqlar Məktəbinin tövsiyəsi: Bazar dəyərini dəqiq bilirsinizsə, lövbəri birinci siz atın; amma tək rəqəmlə yox, \"Strateji Aralıq\" (Range) ilə.", "normal"),
      createBlock("Columbia Business School-un tədqiqatları sübut edir ki, yuxarı sərhədi yüksək olan aralıq verdikdə (məsələn: 1200 - 1500 AZN), işəgötürən avtomatik olaraq aralığın minimumunu (1200 AZN) kompromis kimi qəbul edir.", "normal"),
      createBlock("3. Keçmiş FTB Baş Danışıqçısı Kris Vossdan \"Kalibrlənmiş Suallar\"", "h3"),
      createBlock("Keçmiş FTB girov danışıqçısı Kris Vossun (\"Never Split the Difference\" kitabının müəllifi) metodu: \"Necə?\" sualları ilə təzyiqi qarşı tərəfə ötürmək.", "normal"),
      createBlock("Real Dialoq Ssenarisi:", "normal"),
      createBlock("Şirkət: \"Biz sizin namizədliyinizi bəyəndik, lakin hazırda maksimum 700 AZN təklif edə bilərik.\"", "blockquote"),
      createBlock(">", "normal"),
      createBlock("Siz: \"Şirkətinizin hazırkı büdcə çərçivəsini və resursları optimallaşdırmaq istəyini tam başa düşürəm. Eyni zamanda, bu vəzifədə məndən gözlənilən problemləri həll etmək hədəflərini nəzərə alsaq, bu büdcə ilə qarşılıqlı olaraq necə irəliləyə bilərik?\"", "blockquote"),
      createBlock("4. Təkcə \"Net Maaş\" Yox: \"Total Compensation\" Paketi", "h3"),
      createBlock("1. Hibrid / Uzaqdan İş: Həftədə 2 gün evdən işləmək ayda 100-150 AZN yol/yemək və 30-40 saat vaxt qənaətidir.", "normal"),
      createBlock("2. Peşəkar İnkişaf Büdcəsi: İllik beynəlxalq kurs və konfrans xərclərinin qarşılanması.", "normal"),
      createBlock("3. Protokollaşdırılmış Artım: \"3 aylıq sınaq müddətində X metrikanı yerinə yetirdikdən sonra maaş rəsmi olaraq 1200 AZN-ə qaldırılır.\"", "normal"),
      createBlock("Mənbələr və Ədəbiyyat:", "h3"),
      createBlock("1. Malhotra, D. (Harvard Business Review) – \"15 Rules for Negotiating a Job Offer\".", "normal"),
      createBlock("2. Kahneman, D., & Tversky, A. – \"Judgment under Uncertainty: Heuristics and Biases\".", "normal"),
      createBlock("3. Voss, C. – \"Never Split the Difference: Negotiating As If Your Life Depended On It\".", "normal")
    ],
    body_az: [
      createBlock("Gəlin səmimi olaq: Azərbaycanda əmək bazarında ən böyük tabulardan biri maaş haqqında açıq danışmaqdır.", "normal"),
      createBlock("Uşaqlıqdan bəri bizə aşılanan \"pulu çox soruşmaq ayıbdır\" və ya \"işi verən nə verərsə, ona qane ol\" təfəkkürü peşəkar həyatımıza keçəndə böyük bir maliyyə fəlakətinə çevrilir. Nəticədə eyni təcrübəyə və bacarığa malik iki mütəxəssisdən biri ayda 700 AZN alarkən, digəri düzgün danışıq apardığı üçün eyni şirkətdə 1600 AZN qazanır.", "normal"),
      createBlock("Çoxları düşünür ki, maaş danışığı sadəcə bəxt və ya \"tərs durmaq\" məsələsidir. Lakin Harvard Universitetinin danışıqlar üzrə professoru Dikpak Malhotra (Deepak Malhotra) və Nobel mükafatçısı Daniel Kanemanın (Daniel Kahneman) araşdırmaları göstərir ki, maaş danışığı 100% davranış iqtisadiyyatı və psixologiyaya əsaslanan idarəolunan bir prosesdir.", "normal"),
      createBlock("1. Masanın Digər Tərəfi: HR və Rəhbər Əslində Nə Düşünür?", "h3"),
      createBlock("LinkedIn-in \"Global Talent Trends\" hesabatına görə, işəgötürənlərin 73%-nin hər vakansiya üçün əvvəlcədən təsdiqlənmiş \"Büdcə Dəhlizi\" (Salary Band) olur.", "normal"),
      createBlock("Məsələn, şirkət bir qrafik dizayner və ya marketoloq üçün büdcədə 900 – 1400 AZN ayırıb.", "normal"),
      createBlock("* Əgər siz müsahibədə ilk olaraq \"Mənim üçün 800 AZN bəs edər\" desəniz, HR daxilən sevinəcək və şirkətin büdcəsinə 600 AZN qənaət etdiyi üçün rəhbərlikdən xal qazanacaq.", "normal"),
      createBlock("* Əgər \"1400 AZN\" desəniz və bunu düzgün əsaslandırsanız, şirkət yenə də sizi işə götürəcək, çünki bu məbləğ onların onsuz da təsdiqlənmiş dəhlizinin içindədir.", "normal"),
      createBlock("2. \"Lövbər Effekti\" (Anchoring Bias): İlk Rəqəmi Kim Deməlidir?", "h3"),
      createBlock("Davranış iqtisadiyyatının ən məşhur qanunlarından biri Daniel Kaneman və Amos Tverskinin kəşf etdiyi Lövbər Effektidir.", "normal"),
      createBlock("Bu qanuna görə, danışıq masasında səslənən ilk rəqəm (lövbər) bütün sonrakı müzakirələrin cazibə mərkəzinə çevrilir. Əgər qarşı tərəf \"Biz bu vəzifə üçün 600 AZN düşünürük\" deyərək lövbəri aşağı atsa, sizin oradan 1200 AZN-ə qalxmağınız psixoloji cəhətdən 10 qat çətinləşir.", "normal"),
      createBlock("Harvard Danışıqlar Məktəbinin tövsiyəsi: Bazar dəyərini dəqiq bilirsinizsə, lövbəri birinci siz atın; amma tək rəqəmlə yox, \"Strateji Aralıq\" (Range) ilə.", "normal"),
      createBlock("Columbia Business School-un tədqiqatları sübut edir ki, yuxarı sərhədi yüksək olan aralıq verdikdə (məsələn: 1200 - 1500 AZN), işəgötürən avtomatik olaraq aralığın minimumunu (1200 AZN) kompromis kimi qəbul edir.", "normal"),
      createBlock("3. Keçmiş FTB Baş Danışıqçısı Kris Vossdan \"Kalibrlənmiş Suallar\"", "h3"),
      createBlock("Keçmiş FTB girov danışıqçısı Kris Vossun (\"Never Split the Difference\" kitabının müəllifi) metodu: \"Necə?\" sualları ilə təzyiqi qarşı tərəfə ötürmək.", "normal"),
      createBlock("Real Dialoq Ssenarisi:", "normal"),
      createBlock("Şirkət: \"Biz sizin namizədliyinizi bəyəndik, lakin hazırda maksimum 700 AZN təklif edə bilərik.\"", "blockquote"),
      createBlock(">", "normal"),
      createBlock("Siz: \"Şirkətinizin hazırkı büdcə çərçivəsini və resursları optimallaşdırmaq istəyini tam başa düşürəm. Eyni zamanda, bu vəzifədə məndən gözlənilən problemləri həll etmək hədəflərini nəzərə alsaq, bu büdcə ilə qarşılıqlı olaraq necə irəliləyə bilərik?\"", "blockquote"),
      createBlock("4. Təkcə \"Net Maaş\" Yox: \"Total Compensation\" Paketi", "h3"),
      createBlock("1. Hibrid / Uzaqdan İş: Həftədə 2 gün evdən işləmək ayda 100-150 AZN yol/yemək və 30-40 saat vaxt qənaətidir.", "normal"),
      createBlock("2. Peşəkar İnkişaf Büdcəsi: İllik beynəlxalq kurs və konfrans xərclərinin qarşılanması.", "normal"),
      createBlock("3. Protokollaşdırılmış Artım: \"3 aylıq sınaq müddətində X metrikanı yerinə yetirdikdən sonra maaş rəsmi olaraq 1200 AZN-ə qaldırılır.\"", "normal"),
      createBlock("Mənbələr və Ədəbiyyat:", "h3"),
      createBlock("1. Malhotra, D. (Harvard Business Review) – \"15 Rules for Negotiating a Job Offer\".", "normal"),
      createBlock("2. Kahneman, D., & Tversky, A. – \"Judgment under Uncertainty: Heuristics and Biases\".", "normal"),
      createBlock("3. Voss, C. – \"Never Split the Difference: Negotiating As If Your Life Depended On It\".", "normal")
    ],
    seo: {
      metaTitle: "Azərbaycanda Maaş Danışığı Sənəti: Şirkətlərin \"Maaş Gözləntiniz Nədir?\" Tələsinə Qarşı Harvard Metodologiyası və Davranış Psixologiyası | Rvan.me",
      metaDescription: "Müsahibədə ilk rəqəmi kim deməlidir? Daniel Kanemanın Lövbər effekti, FTB danışıqçısı Kris Vossun sualları və yerli şirkətlərdən +500 AZN yüksək təklif almağın dəqiq skriptləri.",
      canonicalUrl: "https://www.rvan.me/blog/maas-danisigi-psixologiyasi-harvard-metodu"
    }
  },
  {
    _id: "blog-masterclass-gozel-dizayn-niye-pul-itirir-nielsen-norman-group",
    title: "Niyə \"Gözəl Dizayn\" Şirkətlərə Pul İtirir? Nielsen Norman Group Tədqiqatları və Yerli E-Ticarətin 42%-lik Dərsi",
    title_az: "Niyə \"Gözəl Dizayn\" Şirkətlərə Pul İtirir? Nielsen Norman Group Tədqiqatları və Yerli E-Ticarətin 42%-lik Dərsi",
    slug: { _type: "slug", current: "gozel-dizayn-niye-pul-itirir-nielsen-norman-group" },
    slug_az: { _type: "slug", current: "gozel-dizayn-niye-pul-itirir-nielsen-norman-group" },
    originalSlug: "gozel-dizayn-niye-pul-itirir-nielsen-norman-group",
    category: "UI/UX & Rəqəmsal Məhsul",
    category_az: "UI/UX & Rəqəmsal Məhsul",
    excerpt: "Dribbble-dakı min layklı dizaynlar real biznesdə niyə satışları öldürür? Baymard İnstitutunun 68.8% səbət tərki araşdırması və dizaynerin maaşını 3 qat artıran 4 biznes metrikası.",
    excerpt_az: "Dribbble-dakı min layklı dizaynlar real biznesdə niyə satışları öldürür? Baymard İnstitutunun 68.8% səbət tərki araşdırması və dizaynerin maaşını 3 qat artıran 4 biznes metrikası.",
    coverImage: {
      _type: "image",
      url: "https://images.unsplash.com/photo-1581291518655-9523c932edcf?w=1200&h=675&fit=crop&auto=format",
      alt: "Niyə \"Gözəl Dizayn\" Şirkətlərə Pul İtirir? Nielsen Norman Group Tədqiqatları və Yerli E-Ticarətin 42%-lik Dərsi",
    },
    publishDate: "24 Avqust 2026",
    readTime: "9 dəq oxu",
    featured: true,
    tags: ["uiux", "dizayn", "product design", "baymard", "nngroup", "ecommerce", "konversiya"],
    body: [
      createBlock("Müasir rəqəmsal dünyada çox təhlükəli bir mif dolaşır: \"Əgər dizayn estetik, müasir və rəngarəngdirsə, o mütləq uğurlu olacaq.\"", "normal"),
      createBlock("Hər il minlərlə dizayner Dribbble və Behance platformalarında minlərlə layk toplayan animasiyalı, neon rəngli konseptlər paylaşır. Amma eyni dizaynları real biznesə tətbiq etdikdə acı reallıq üzə çıxır: Satışlar kəskin düşür, istifadəçilər çaşqınlıq içində tətbiqi tərk edir.", "normal"),
      createBlock("1. Baymard İnstitutunun Statistikası: 68.8% Səbət Tərki", "h3"),
      createBlock("Dünyanın aparıcı e-ticarət və UX tədqiqat institutu olan Baymard Institute-un 48.000-dən çox istifadəçini əhatə edən qlobal araşdırmasına görə, onlayn alış-verişdə səbətə məhsul atıb saytı tərk edənlərin ortalama göstəricisi 68.8%-dir.", "normal"),
      createBlock("Səbəblər:", "normal"),
      createBlock("* 24% – Saytın məcburi şəkildə uzun qeydiyyat tələb etməsi.", "normal"),
      createBlock("* 18% – Ödəniş və checkout prosesinin həddindən artıq mürəkkəb olması.", "normal"),
      createBlock("* 17% – Sonda gözlənilməz əlavə xərclərin çıxması.", "normal"),
      createBlock("2. Nielsen Norman Group (NN/g): F-Shape Scanning Modeli", "h3"),
      createBlock("Don Norman və Yakob Nilsenin (Jakob Nielsen) qurduğu Nielsen Norman Group göz izləmə (Eye-tracking) araşdırması ilə sübut etdi ki, istifadəçilər veb-saytları kitab kimi oxumur, F-şəkilli trayektoriya ilə gözdən keçirir:", "normal"),
      createBlock("1. Əvvəlcə yuxarı horizontal xətt.", "normal"),
      createBlock("2. Sonra bir qədər qısa ikinci horizontal xətt.", "normal"),
      createBlock("3. Sol tərəf boyunca şaquli eniş.", "normal"),
      createBlock("Əgər ən vacib çağırış (CTA) düyməsi bu təbii axına uyğun qoyulmayıbsa, istifadəçi koqnitiv yüklənmə yaşayır və səhifəni tərk edir.", "normal"),
      createBlock("3. Yerli E-Ticarətdən Real Case: Sadəlik Satışı Necə 42% Artırdı?", "h3"),
      createBlock("Bakıda fəaliyyət göstərən çatdırılma xidmətində tətbiq edilən UX dəyişikliyi:", "normal"),
      createBlock("* Qeydiyyat tam ləğv edildi (Yalnız nömrə + 1 SMS kod).", "normal"),
      createBlock("* Checkout tək səhifəyə endirildi (One-Page Checkout).", "normal"),
      createBlock("* \"Sifarişi Təsdiqlə\" düyməsi baş barmağın çatdığı Thumb Zone sahəsinə yerləşdirildi.", "normal"),
      createBlock("Nəticə: Sifarişi tamamlayanların nisbəti 32%-dən 45.4%-ə yüksəldi (+42% xalis artım).", "normal"),
      createBlock("Dizaynerin Maaşını Artıran 4 Biznes Metrikası:", "h3"),
      createBlock("1. Conversion Rate (Konversiya dərəcəsi)", "normal"),
      createBlock("2. Bounce Rate (Hemen çıxma faizi)", "normal"),
      createBlock("3. Task Completion Rate (Tapşırığı tamamlama vaxtı)", "normal"),
      createBlock("4. Drop-off Rate (Mərhələdən qopma dərəcəsi)", "normal"),
      createBlock("Mənbələr:", "h3"),
      createBlock("1. Baymard Institute (2023 Research) – \"48 Cart Abandonment Rate Statistics\".", "normal"),
      createBlock("2. Nielsen, J., & Pernice, K. – \"Eyetracking Web Usability\" (Nielsen Norman Group).", "normal"),
      createBlock("3. Norman, D. – \"The Design of Everyday Things\".", "normal")
    ],
    body_az: [
      createBlock("Müasir rəqəmsal dünyada çox təhlükəli bir mif dolaşır: \"Əgər dizayn estetik, müasir və rəngarəngdirsə, o mütləq uğurlu olacaq.\"", "normal"),
      createBlock("Hər il minlərlə dizayner Dribbble və Behance platformalarında minlərlə layk toplayan animasiyalı, neon rəngli konseptlər paylaşır. Amma eyni dizaynları real biznesə tətbiq etdikdə acı reallıq üzə çıxır: Satışlar kəskin düşür, istifadəçilər çaşqınlıq içində tətbiqi tərk edir.", "normal"),
      createBlock("1. Baymard İnstitutunun Statistikası: 68.8% Səbət Tərki", "h3"),
      createBlock("Dünyanın aparıcı e-ticarət və UX tədqiqat institutu olan Baymard Institute-un 48.000-dən çox istifadəçini əhatə edən qlobal araşdırmasına görə, onlayn alış-verişdə səbətə məhsul atıb saytı tərk edənlərin ortalama göstəricisi 68.8%-dir.", "normal"),
      createBlock("Səbəblər:", "normal"),
      createBlock("* 24% – Saytın məcburi şəkildə uzun qeydiyyat tələb etməsi.", "normal"),
      createBlock("* 18% – Ödəniş və checkout prosesinin həddindən artıq mürəkkəb olması.", "normal"),
      createBlock("* 17% – Sonda gözlənilməz əlavə xərclərin çıxması.", "normal"),
      createBlock("2. Nielsen Norman Group (NN/g): F-Shape Scanning Modeli", "h3"),
      createBlock("Don Norman və Yakob Nilsenin (Jakob Nielsen) qurduğu Nielsen Norman Group göz izləmə (Eye-tracking) araşdırması ilə sübut etdi ki, istifadəçilər veb-saytları kitab kimi oxumur, F-şəkilli trayektoriya ilə gözdən keçirir:", "normal"),
      createBlock("1. Əvvəlcə yuxarı horizontal xətt.", "normal"),
      createBlock("2. Sonra bir qədər qısa ikinci horizontal xətt.", "normal"),
      createBlock("3. Sol tərəf boyunca şaquli eniş.", "normal"),
      createBlock("Əgər ən vacib çağırış (CTA) düyməsi bu təbii axına uyğun qoyulmayıbsa, istifadəçi koqnitiv yüklənmə yaşayır və səhifəni tərk edir.", "normal"),
      createBlock("3. Yerli E-Ticarətdən Real Case: Sadəlik Satışı Necə 42% Artırdı?", "h3"),
      createBlock("Bakıda fəaliyyət göstərən çatdırılma xidmətində tətbiq edilən UX dəyişikliyi:", "normal"),
      createBlock("* Qeydiyyat tam ləğv edildi (Yalnız nömrə + 1 SMS kod).", "normal"),
      createBlock("* Checkout tək səhifəyə endirildi (One-Page Checkout).", "normal"),
      createBlock("* \"Sifarişi Təsdiqlə\" düyməsi baş barmağın çatdığı Thumb Zone sahəsinə yerləşdirildi.", "normal"),
      createBlock("Nəticə: Sifarişi tamamlayanların nisbəti 32%-dən 45.4%-ə yüksəldi (+42% xalis artım).", "normal"),
      createBlock("Dizaynerin Maaşını Artıran 4 Biznes Metrikası:", "h3"),
      createBlock("1. Conversion Rate (Konversiya dərəcəsi)", "normal"),
      createBlock("2. Bounce Rate (Hemen çıxma faizi)", "normal"),
      createBlock("3. Task Completion Rate (Tapşırığı tamamlama vaxtı)", "normal"),
      createBlock("4. Drop-off Rate (Mərhələdən qopma dərəcəsi)", "normal"),
      createBlock("Mənbələr:", "h3"),
      createBlock("1. Baymard Institute (2023 Research) – \"48 Cart Abandonment Rate Statistics\".", "normal"),
      createBlock("2. Nielsen, J., & Pernice, K. – \"Eyetracking Web Usability\" (Nielsen Norman Group).", "normal"),
      createBlock("3. Norman, D. – \"The Design of Everyday Things\".", "normal")
    ],
    seo: {
      metaTitle: "Niyə \"Gözəl Dizayn\" Şirkətlərə Pul İtirir? Nielsen Norman Group Tədqiqatları və Yerli E-Ticarətin 42%-lik Dərsi | Rvan.me",
      metaDescription: "Dribbble-dakı min layklı dizaynlar real biznesdə niyə satışları öldürür? Baymard İnstitutunun 68.8% səbət tərki araşdırması və dizaynerin maaşını 3 qat artıran 4 biznes metrikası.",
      canonicalUrl: "https://www.rvan.me/blog/gozel-dizayn-niye-pul-itirir-nielsen-norman-group"
    }
  },
  {
    _id: "blog-masterclass-izleyici-coxlugu-satis-getirmir-cialdini-funnel",
    title: "Niyə 50.000 İzləyicisi Olan Səhifə 100 AZN Qazanır, Amma 2.000 İzləyicisi Olan Şirkət Satış Rekordları Qırır?",
    title_az: "Niyə 50.000 İzləyicisi Olan Səhifə 100 AZN Qazanır, Amma 2.000 İzləyicisi Olan Şirkət Satış Rekordları Qırır?",
    slug: { _type: "slug", current: "izleyici-coxlugu-satis-getirmir-cialdini-funnel" },
    slug_az: { _type: "slug", current: "izleyici-coxlugu-satis-getirmir-cialdini-funnel" },
    originalSlug: "izleyici-coxlugu-satis-getirmir-cialdini-funnel",
    category: "Marketinq & SMM",
    category_az: "Marketinq & SMM",
    excerpt: "Sosial mediada 'Vanity Metrics' tələsi. Robert Çaldininin 3 psixoloji prinsipi və soyuq izləyicini sadiq alıcıya çevirən 3 pilləli satış qıfı (Funnel) strategiyası.",
    excerpt_az: "Sosial mediada 'Vanity Metrics' tələsi. Robert Çaldininin 3 psixoloji prinsipi və soyuq izləyicini sadiq alıcıya çevirən 3 pilləli satış qıfı (Funnel) strategiyası.",
    coverImage: {
      _type: "image",
      url: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=1200&h=675&fit=crop&auto=format",
      alt: "Niyə 50.000 İzləyicisi Olan Səhifə 100 AZN Qazanır, Amma 2.000 İzləyicisi Olan Şirkət Satış Rekordları Qırır?",
    },
    publishDate: "22 Avqust 2026",
    readTime: "8 dəq oxu",
    featured: true,
    tags: ["smm", "marketinq", "instagram", "cialdini", "satis qifi", "funnel", "brend"],
    body: [
      createBlock("Azərbaycan sosial media bazarında ən çox pul və enerji itkisinə səbəb olan təməl bir yanılsama var: \"İzləyici sayı çoxdursa, deməli satış da çox olacaq.\"", "normal"),
      createBlock("Hər gün minlərlə manat büdcə giveaway-lərə və mənasız izləyici artırmağa xərclənir. Nəticədə 50-100 minlik \"nəhəng\" səhifələr yaranır, amma bir post paylaşanda altına cəmi 3 nəfər rəy yazır, WhatsApp-a isə günlərlə heç bir real müştəri mesajı gəlmir.", "normal"),
      createBlock("Əsl dəyər \"İzləyici sayı\"nda deyil, \"Auditoriyanın Güvən İndeksi\"ndədir.", "normal"),
      createBlock("1. Robert Çaldininin 3 Qızıl Qaydasının Tətbiqi", "h3"),
      createBlock("1. **Sosial Sübut (Social Proof):** Məhsulu istifadə edən real müştərinin səs yazısını, unboxing videosunu və ya emosional rəyini paylaşmaq. Harvard araşdırmalarına görə, real istifadəçi rəyi olan postlar konversiyanı 270% artırır.", "normal"),
      createBlock("2. **Avtoritet (Authority):** Hər gün \"Məhsul satılır\" deməyin. Sahənizdə insanların aldanmaması üçün maarifləndirici ekspert təhlilləri paylaşın.", "normal"),
      createBlock("3. **Qarşılıqlılıq (Reciprocity):** İnsanlara əvvəlcə təmənnasız dəyər verin (Pulsuz bələdçi, şablon, analiz).", "normal"),
      createBlock("2. Satış Qıfının (Sales Funnel) 3 Pilləsi:", "h3"),
      createBlock("* **TOFU (Top of Funnel - 60% Məzmun):** Hamı üçün maraqlı, viral, maarifləndirici Reels və postlar.", "normal"),
      createBlock("* **MOFU (Middle of Funnel - 30% Məzmun):** Etibar və Avtoritet: Case Study, rəylər, komanda arxası.", "normal"),
      createBlock("* **BOFU (Bottom of Funnel - 10% Məzmun):** Birbaşa Satış: Konkret təklif, zəmanət və aydın CTA.", "normal"),
      createBlock("Mənbələr:", "h3"),
      createBlock("1. Cialdini, R. B. – \"Influence: The Psychology of Persuasion\".", "normal"),
      createBlock("2. Berger, J. – \"Contagious: Why Things Catch On\".", "normal")
    ],
    body_az: [
      createBlock("Azərbaycan sosial media bazarında ən çox pul və enerji itkisinə səbəb olan təməl bir yanılsama var: \"İzləyici sayı çoxdursa, deməli satış da çox olacaq.\"", "normal"),
      createBlock("Hər gün minlərlə manat büdcə giveaway-lərə və mənasız izləyici artırmağa xərclənir. Nəticədə 50-100 minlik \"nəhəng\" səhifələr yaranır, amma bir post paylaşanda altına cəmi 3 nəfər rəy yazır, WhatsApp-a isə günlərlə heç bir real müştəri mesajı gəlmir.", "normal"),
      createBlock("Əsl dəyər \"İzləyici sayı\"nda deyil, \"Auditoriyanın Güvən İndeksi\"ndədir.", "normal"),
      createBlock("1. Robert Çaldininin 3 Qızıl Qaydasının Tətbiqi", "h3"),
      createBlock("1. **Sosial Sübut (Social Proof):** Məhsulu istifadə edən real müştərinin səs yazısını, unboxing videosunu və ya emosional rəyini paylaşmaq. Harvard araşdırmalarına görə, real istifadəçi rəyi olan postlar konversiyanı 270% artırır.", "normal"),
      createBlock("2. **Avtoritet (Authority):** Hər gün \"Məhsul satılır\" deməyin. Sahənizdə insanların aldanmaması üçün maarifləndirici ekspert təhlilləri paylaşın.", "normal"),
      createBlock("3. **Qarşılıqlılıq (Reciprocity):** İnsanlara əvvəlcə təmənnasız dəyər verin (Pulsuz bələdçi, şablon, analiz).", "normal"),
      createBlock("2. Satış Qıfının (Sales Funnel) 3 Pilləsi:", "h3"),
      createBlock("* **TOFU (Top of Funnel - 60% Məzmun):** Hamı üçün maraqlı, viral, maarifləndirici Reels və postlar.", "normal"),
      createBlock("* **MOFU (Middle of Funnel - 30% Məzmun):** Etibar və Avtoritet: Case Study, rəylər, komanda arxası.", "normal"),
      createBlock("* **BOFU (Bottom of Funnel - 10% Məzmun):** Birbaşa Satış: Konkret təklif, zəmanət və aydın CTA.", "normal"),
      createBlock("Mənbələr:", "h3"),
      createBlock("1. Cialdini, R. B. – \"Influence: The Psychology of Persuasion\".", "normal"),
      createBlock("2. Berger, J. – \"Contagious: Why Things Catch On\".", "normal")
    ],
    seo: {
      metaTitle: "Niyə 50.000 İzləyicisi Olan Səhifə 100 AZN Qazanır, Amma 2.000 İzləyicisi Olan Şirkət Satış Rekordları Qırır? | Rvan.me",
      metaDescription: "Sosial mediada 'Vanity Metrics' tələsi. Robert Çaldininin 3 psixoloji prinsipi və soyuq izləyicini sadiq alıcıya çevirən 3 pilləli satış qıfı (Funnel) strategiyası.",
      canonicalUrl: "https://www.rvan.me/blog/izleyici-coxlugu-satis-getirmir-cialdini-funnel"
    }
  },
  {
    _id: "blog-masterclass-qlobal-frilans-upwork-linkedin-saati-40-dollar",
    title: "Bakıda Oturaraq Qlobal Bazardan Valyuta Qazanmaq: Upwork və LinkedIn-də Saatı 40$+ Təklif Almağın Strateji Anatomiyası",
    title_az: "Bakıda Oturaraq Qlobal Bazardan Valyuta Qazanmaq: Upwork və LinkedIn-də Saatı 40$+ Təklif Almağın Strateji Anatomiyası",
    slug: { _type: "slug", current: "qlobal-frilans-upwork-linkedin-saati-40-dollar" },
    slug_az: { _type: "slug", current: "qlobal-frilans-upwork-linkedin-saati-40-dollar" },
    originalSlug: "qlobal-frilans-upwork-linkedin-saati-40-dollar",
    category: "Frilanserlik & Qlobal",
    category_az: "Frilanserlik & Qlobal",
    excerpt: "Yerli bazarın büdcə limitlərindən çıxış yolu. The Futur metodologiyası, qlobal müştəriyə təsir edən Cold Proposal şablonu və LinkedIn Inbound satış sistemi.",
    excerpt_az: "Yerli bazarın büdcə limitlərindən çıxış yolu. The Futur metodologiyası, qlobal müştəriyə təsir edən Cold Proposal şablonu və LinkedIn Inbound satış sistemi.",
    coverImage: {
      _type: "image",
      url: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1200&h=675&fit=crop&auto=format",
      alt: "Bakıda Oturaraq Qlobal Bazardan Valyuta Qazanmaq: Upwork və LinkedIn-də Saatı 40$+ Təklif Almağın Strateji Anatomiyası",
    },
    publishDate: "20 Avqust 2026",
    readTime: "9 dəq oxu",
    featured: false,
    tags: ["frilans", "upwork", "linkedin", "dollar qazanmaq", "the futur", "chris do", "portfolio"],
    body: [
      createBlock("Yerli bazarda 150 AZN üçün 10 dəfə düzəliş tələb edən müştəri ilə işləmək insanı tükəndirir (burnout). Halbuki eyni vaxtı və enerjini ABŞ və Avropadakı startaplara sərf etməklə saatı 40-70$ və ya layihə başına 2000-5000$ qazanmaq mümkündür.", "normal"),
      createBlock("1. Ucuz Qiymətlə Rəqabət Aparmaq Tələsi", "h3"),
      createBlock("Qlobal müştəri saatı 8$ olan profili görəndə keyfiyyətsiz işdən şübhələnir. Onlar üçün əsas məsələ vaxta qənaət və problemin birdəfəlik həllidir.", "normal"),
      createBlock("2. Upwork-də İş Qazandıran 4 Pilləli Şablon:", "h3"),
      createBlock("1. **1-ci Abzas:** Birbaşa müştərinin probleminə toxunuş (Adınızı tərifləmədən).", "normal"),
      createBlock("2. **2-ci Abzas:** Həll yolu və 90 saniyəlik qısa Loom video linki.", "normal"),
      createBlock("3. **3-cü Abzas:** Bənzər bir layihədə əldə edilən konkret nəticə (+35% konversiya).", "normal"),
      createBlock("4. **4-cü Abzas:** Aşağı riskli çağırış (10 dəqiqəlik qısa tanışlıq zəngi).", "normal"),
      createBlock("Mənbələr:", "h3"),
      createBlock("1. Do, C. (The Futur) – \"Pricing Design & The Psychology of Value\".", "normal"),
      createBlock("2. Upwork Research Institute – \"Freelance Forward Global Report\".", "normal")
    ],
    body_az: [
      createBlock("Yerli bazarda 150 AZN üçün 10 dəfə düzəliş tələb edən müştəri ilə işləmək insanı tükəndirir (burnout). Halbuki eyni vaxtı və enerjini ABŞ və Avropadakı startaplara sərf etməklə saatı 40-70$ və ya layihə başına 2000-5000$ qazanmaq mümkündür.", "normal"),
      createBlock("1. Ucuz Qiymətlə Rəqabət Aparmaq Tələsi", "h3"),
      createBlock("Qlobal müştəri saatı 8$ olan profili görəndə keyfiyyətsiz işdən şübhələnir. Onlar üçün əsas məsələ vaxta qənaət və problemin birdəfəlik həllidir.", "normal"),
      createBlock("2. Upwork-də İş Qazandıran 4 Pilləli Şablon:", "h3"),
      createBlock("1. **1-ci Abzas:** Birbaşa müştərinin probleminə toxunuş (Adınızı tərifləmədən).", "normal"),
      createBlock("2. **2-ci Abzas:** Həll yolu və 90 saniyəlik qısa Loom video linki.", "normal"),
      createBlock("3. **3-cü Abzas:** Bənzər bir layihədə əldə edilən konkret nəticə (+35% konversiya).", "normal"),
      createBlock("4. **4-cü Abzas:** Aşağı riskli çağırış (10 dəqiqəlik qısa tanışlıq zəngi).", "normal"),
      createBlock("Mənbələr:", "h3"),
      createBlock("1. Do, C. (The Futur) – \"Pricing Design & The Psychology of Value\".", "normal"),
      createBlock("2. Upwork Research Institute – \"Freelance Forward Global Report\".", "normal")
    ],
    seo: {
      metaTitle: "Bakıda Oturaraq Qlobal Bazardan Valyuta Qazanmaq: Upwork və LinkedIn-də Saatı 40$+ Təklif Almağın Strateji Anatomiyası | Rvan.me",
      metaDescription: "Yerli bazarın büdcə limitlərindən çıxış yolu. The Futur metodologiyası, qlobal müştəriyə təsir edən Cold Proposal şablonu və LinkedIn Inbound satış sistemi.",
      canonicalUrl: "https://www.rvan.me/blog/qlobal-frilans-upwork-linkedin-saati-40-dollar"
    }
  },
  {
    _id: "blog-masterclass-cv-niye-6-saniyede-red-edilir-ats-sistemleri",
    title: "CV-niz Niyə 6 Saniyədə Zibil Qutusuna Gedir? Harvard Tədqiqatı və ATS (Applicant Tracking System) Alqoritmlərinin Şifrəsi",
    title_az: "CV-niz Niyə 6 Saniyədə Zibil Qutusuna Gedir? Harvard Tədqiqatı və ATS (Applicant Tracking System) Alqoritmlərinin Şifrəsi",
    slug: { _type: "slug", current: "cv-niye-6-saniyede-red-edilir-ats-sistemleri" },
    slug_az: { _type: "slug", current: "cv-niye-6-saniyede-red-edilir-ats-sistemleri" },
    originalSlug: "cv-niye-6-saniyede-red-edilir-ats-sistemleri",
    category: "Karyera & HR",
    category_az: "Karyera & HR",
    excerpt: "CV-lərin 75%-i niyə insan gözü görmədən rədd edilir? Canva tələsi, The Ladders göz izləmə araşdırması və Google-un məşhur XYZ formulu.",
    excerpt_az: "CV-lərin 75%-i niyə insan gözü görmədən rədd edilir? Canva tələsi, The Ladders göz izləmə araşdırması və Google-un məşhur XYZ formulu.",
    coverImage: {
      _type: "image",
      url: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=1200&h=675&fit=crop&auto=format",
      alt: "CV-niz Niyə 6 Saniyədə Zibil Qutusuna Gedir? Harvard Tədqiqatı və ATS (Applicant Tracking System) Alqoritmlərinin Şifrəsi",
    },
    publishDate: "18 Avqust 2026",
    readTime: "8 dəq oxu",
    featured: false,
    tags: ["cv", "ats", "rekruting", "vakansiya", "is axtarisi", "google xyz", "hr"],
    body: [
      createBlock("Harvard Business School-un \"Hidden Workers\" adlı qlobal tədqiqatı göstərir ki, böyük şirkətlərə daxil olan CV-lərin 75%-dən çoxu insan tərəfindən oxunmadan, birbaşa avtomatlaşdırılmış ATS proqramları tərəfindən rədd edilir.", "normal"),
      createBlock("1. Canva Dizaynları Niyə Keçmir?", "h3"),
      createBlock("2 sütunlu mürəkkəb dizaynlar, qrafik barlar və şəkillər ATS robotlarının mətni parçalamasına (parsing) mane olur və CV avtomatik arxivə gedir.", "normal"),
      createBlock("2. Google-un \"XYZ Formulu\" ilə Təcrübə Yazmaq:", "h3"),
      createBlock("\"Mən [Z] tətbiq edərək [Y] nəticəsini əldə etdim və bu [X] metrikayla ölçüldü.\"", "blockquote"),
      createBlock("Nümunə: \"Yeni vizual dildən və Reels strategiyasından istifadə edərək (Z), şirkətin Instagram satışlarını 4 ayda 35% artırdım (X) və aylıq gəlirə 4000 AZN əlavə töhfə verdim (Y).\"", "normal"),
      createBlock("Mənbələr:", "h3"),
      createBlock("1. Harvard Business School – \"Hidden Workers: Untapped Talent\".", "normal"),
      createBlock("2. The Ladders Eye-Tracking Study.", "normal")
    ],
    body_az: [
      createBlock("Harvard Business School-un \"Hidden Workers\" adlı qlobal tədqiqatı göstərir ki, böyük şirkətlərə daxil olan CV-lərin 75%-dən çoxu insan tərəfindən oxunmadan, birbaşa avtomatlaşdırılmış ATS proqramları tərəfindən rədd edilir.", "normal"),
      createBlock("1. Canva Dizaynları Niyə Keçmir?", "h3"),
      createBlock("2 sütunlu mürəkkəb dizaynlar, qrafik barlar və şəkillər ATS robotlarının mətni parçalamasına (parsing) mane olur və CV avtomatik arxivə gedir.", "normal"),
      createBlock("2. Google-un \"XYZ Formulu\" ilə Təcrübə Yazmaq:", "h3"),
      createBlock("\"Mən [Z] tətbiq edərək [Y] nəticəsini əldə etdim və bu [X] metrikayla ölçüldü.\"", "blockquote"),
      createBlock("Nümunə: \"Yeni vizual dildən və Reels strategiyasından istifadə edərək (Z), şirkətin Instagram satışlarını 4 ayda 35% artırdım (X) və aylıq gəlirə 4000 AZN əlavə töhfə verdim (Y).\"", "normal"),
      createBlock("Mənbələr:", "h3"),
      createBlock("1. Harvard Business School – \"Hidden Workers: Untapped Talent\".", "normal"),
      createBlock("2. The Ladders Eye-Tracking Study.", "normal")
    ],
    seo: {
      metaTitle: "CV-niz Niyə 6 Saniyədə Zibil Qutusuna Gedir? Harvard Tədqiqatı və ATS (Applicant Tracking System) Alqoritmlərinin Şifrəsi | Rvan.me",
      metaDescription: "CV-lərin 75%-i niyə insan gözü görmədən rədd edilir? Canva tələsi, The Ladders göz izləmə araşdırması və Google-un məşhur XYZ formulu.",
      canonicalUrl: "https://www.rvan.me/blog/cv-niye-6-saniyede-red-edilir-ats-sistemleri"
    }
  },
  {
    _id: "blog-masterclass-sunii-intellekt-kimleri-issiz-qoyacaq-mit-stanford",
    title: "Süni İntellekt (AI) Əslində Kimləri İşsiz Qoyacaq? MIT və Stanford Universitetlərinin 2024-2026 Tədqiqatları və Karyera Sığortası",
    title_az: "Süni İntellekt (AI) Əslində Kimləri İşsiz Qoyacaq? MIT və Stanford Universitetlərinin 2024-2026 Tədqiqatları və Karyera Sığortası",
    slug: { _type: "slug", current: "sunii-intellekt-kimleri-issiz-qoyacaq-mit-stanford" },
    slug_az: { _type: "slug", current: "sunii-intellekt-kimleri-issiz-qoyacaq-mit-stanford" },
    originalSlug: "sunii-intellekt-kimleri-issiz-qoyacaq-mit-stanford",
    category: "Süni İntellekt & Gələcək",
    category_az: "Süni İntellekt & Gələcək",
    excerpt: "AI iş yerlərini yox edir, yoxsa yenidən bölüşdürür? MIT-nin 453 mütəxəssis üzərindəki eksperimenti və gələcəyin ən yüksək qazanclı hibrid bacarıqları.",
    excerpt_az: "AI iş yerlərini yox edir, yoxsa yenidən bölüşdürür? MIT-nin 453 mütəxəssis üzərindəki eksperimenti və gələcəyin ən yüksək qazanclı hibrid bacarıqları.",
    coverImage: {
      _type: "image",
      url: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1200&h=675&fit=crop&auto=format",
      alt: "Süni İntellekt (AI) Əslində Kimləri İşsiz Qoyacaq? MIT və Stanford Universitetlərinin 2024-2026 Tədqiqatları və Karyera Sığortası",
    },
    publishDate: "16 Avqust 2026",
    readTime: "9 dəq oxu",
    featured: false,
    tags: ["ai", "suni intellekt", "mit", "stanford", "geleceyin peseleri", "chatgpt", "karyera"],
    body: [
      createBlock("MIT iqtisadçıları Şakked Noy və Uitni Janq tərəfindən aparılan eksperiment göstərdi ki, AI alətlərindən istifadə edən mütəxəssislər işlərini 37% daha sürətli və 18% daha keyfiyyətli tamamlayırlar.", "normal"),
      createBlock("Süni intellekt sizin yerinizi tutmayacaq. Amma süni intellektdən istifadə edərək işini 2 qat sürətləndirən bir mütəxəssis, köhnə üsullarla işləyən həmkarını bazardan sıxışdırıb çıxaracaq.", "normal"),
      createBlock("Əsl kritik bacarıq \"Prompt yazmaq\" deyil, \"Domen Ekspertizası\" (Sahə biliyi) olacaq.", "normal"),
      createBlock("Mənbələr:", "h3"),
      createBlock("1. Noy, S., & Zhang, W. (MIT) – Science, 2023.", "normal"),
      createBlock("2. Stanford HAI – Artificial Intelligence Index Report 2024.", "normal")
    ],
    body_az: [
      createBlock("MIT iqtisadçıları Şakked Noy və Uitni Janq tərəfindən aparılan eksperiment göstərdi ki, AI alətlərindən istifadə edən mütəxəssislər işlərini 37% daha sürətli və 18% daha keyfiyyətli tamamlayırlar.", "normal"),
      createBlock("Süni intellekt sizin yerinizi tutmayacaq. Amma süni intellektdən istifadə edərək işini 2 qat sürətləndirən bir mütəxəssis, köhnə üsullarla işləyən həmkarını bazardan sıxışdırıb çıxaracaq.", "normal"),
      createBlock("Əsl kritik bacarıq \"Prompt yazmaq\" deyil, \"Domen Ekspertizası\" (Sahə biliyi) olacaq.", "normal"),
      createBlock("Mənbələr:", "h3"),
      createBlock("1. Noy, S., & Zhang, W. (MIT) – Science, 2023.", "normal"),
      createBlock("2. Stanford HAI – Artificial Intelligence Index Report 2024.", "normal")
    ],
    seo: {
      metaTitle: "Süni İntellekt (AI) Əslində Kimləri İşsiz Qoyacaq? MIT və Stanford Universitetlərinin 2024-2026 Tədqiqatları və Karyera Sığortası | Rvan.me",
      metaDescription: "AI iş yerlərini yox edir, yoxsa yenidən bölüşdürür? MIT-nin 453 mütəxəssis üzərindəki eksperimenti və gələcəyin ən yüksək qazanclı hibrid bacarıqları.",
      canonicalUrl: "https://www.rvan.me/blog/sunii-intellekt-kimleri-issiz-qoyacaq-mit-stanford"
    }
  },
  {
    _id: "blog-masterclass-sifirdan-ui-ux-dizayn-oyrenmek-6-ayliq-xərite",
    title: "Kurslara 1500 AZN Xərcləmədən Sıfırdan UI/UX Dizayneri Olmaq: 6 Aylıq Özünütəhsil Yol Xəritəsi",
    title_az: "Kurslara 1500 AZN Xərcləmədən Sıfırdan UI/UX Dizayneri Olmaq: 6 Aylıq Özünütəhsil Yol Xəritəsi",
    slug: { _type: "slug", current: "sifirdan-ui-ux-dizayn-oyrenmek-6-ayliq-xərite" },
    slug_az: { _type: "slug", current: "sifirdan-ui-ux-dizayn-oyrenmek-6-ayliq-xərite" },
    originalSlug: "sifirdan-ui-ux-dizayn-oyrenmek-6-ayliq-xərite",
    category: "Təhsil & Dizayn",
    category_az: "Təhsil & Dizayn",
    excerpt: "YouTube və pulsuz resurslarla 6 aya necə peşəkar dizayner olmaq olar? Josh Kaufman-ın sürətli öyrənmə metodu, Figma ustalığı və 2 güclü Case Study formulu.",
    excerpt_az: "YouTube və pulsuz resurslarla 6 aya necə peşəkar dizayner olmaq olar? Josh Kaufman-ın sürətli öyrənmə metodu, Figma ustalığı və 2 güclü Case Study formulu.",
    coverImage: {
      _type: "image",
      url: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=1200&h=675&fit=crop&auto=format",
      alt: "Kurslara 1500 AZN Xərcləmədən Sıfırdan UI/UX Dizayneri Olmaq: 6 Aylıq Özünütəhsil Yol Xəritəsi",
    },
    publishDate: "14 Avqust 2026",
    readTime: "10 dəq oxu",
    featured: false,
    tags: ["uiux", "figma", "dizayn oyrenmek", "pulsuz kurslar", "ozunutehsil", "portfolio"],
    body: [
      createBlock("Kursların 85%-i sadəcə YouTube-da pulsuz olan məlumatları şablon slaydlarla satır. Düzgün yol xəritəsi ilə 6 aya sıfırdan güclü mütəxəssisə çevrilmək mümkündür.", "normal"),
      createBlock("6 Aylıq Plan:", "h3"),
      createBlock("* **1-2-ci Ay:** Qeştalt Psixologiyası, Tipoqrafika, 60-30-10 Rəng Qaydası, Figma Auto Layout və Components.", "normal"),
      createBlock("* **3-4-cü Ay:** Klonlama (Reverse Engineering) və Laws of UX insan psixologiyası qanunları.", "normal"),
      createBlock("* **5-6-cı Ay:** Real yerli problemi həll edən 2 dərindən işlənmiş Case Study.", "normal"),
      createBlock("Mənbələr:", "h3"),
      createBlock("1. Kaufman, J. – \"The First 20 Hours\".", "normal"),
      createBlock("2. Yablonski, J. – \"Laws of UX\".", "normal")
    ],
    body_az: [
      createBlock("Kursların 85%-i sadəcə YouTube-da pulsuz olan məlumatları şablon slaydlarla satır. Düzgün yol xəritəsi ilə 6 aya sıfırdan güclü mütəxəssisə çevrilmək mümkündür.", "normal"),
      createBlock("6 Aylıq Plan:", "h3"),
      createBlock("* **1-2-ci Ay:** Qeştalt Psixologiyası, Tipoqrafika, 60-30-10 Rəng Qaydası, Figma Auto Layout və Components.", "normal"),
      createBlock("* **3-4-cü Ay:** Klonlama (Reverse Engineering) və Laws of UX insan psixologiyası qanunları.", "normal"),
      createBlock("* **5-6-cı Ay:** Real yerli problemi həll edən 2 dərindən işlənmiş Case Study.", "normal"),
      createBlock("Mənbələr:", "h3"),
      createBlock("1. Kaufman, J. – \"The First 20 Hours\".", "normal"),
      createBlock("2. Yablonski, J. – \"Laws of UX\".", "normal")
    ],
    seo: {
      metaTitle: "Kurslara 1500 AZN Xərcləmədən Sıfırdan UI/UX Dizayneri Olmaq: 6 Aylıq Özünütəhsil Yol Xəritəsi | Rvan.me",
      metaDescription: "YouTube və pulsuz resurslarla 6 aya necə peşəkar dizayner olmaq olar? Josh Kaufman-ın sürətli öyrənmə metodu, Figma ustalığı və 2 güclü Case Study formulu.",
      canonicalUrl: "https://www.rvan.me/blog/sifirdan-ui-ux-dizayn-oyrenmek-6-ayliq-xərite"
    }
  },
  {
    _id: "blog-masterclass-kod-yazmadan-sayt-yigib-satmaq-framer-no-code",
    title: "Kod Yazmadan Veb-Sayt Yığıb 500 – 1500 AZN-ə Satmaq: Framer və Figma ilə \"No-Code\" Gəlir Modeli",
    title_az: "Kod Yazmadan Veb-Sayt Yığıb 500 – 1500 AZN-ə Satmaq: Framer və Figma ilə \"No-Code\" Gəlir Modeli",
    slug: { _type: "slug", current: "kod-yazmadan-sayt-yigib-satmaq-framer-no-code" },
    slug_az: { _type: "slug", current: "kod-yazmadan-sayt-yigib-satmaq-framer-no-code" },
    originalSlug: "kod-yazmadan-sayt-yigib-satmaq-framer-no-code",
    category: "No-Code & Veb",
    category_az: "No-Code & Veb",
    excerpt: "Gartner-in 70%-lik No-Code proqnozu. Figma-dan Framer-ə 3 addımlıq istehsal zənciri və yerli bizneslərə Landing Page satmağın dəqiq skripti.",
    excerpt_az: "Gartner-in 70%-lik No-Code proqnozu. Figma-dan Framer-ə 3 addımlıq istehsal zənciri və yerli bizneslərə Landing Page satmağın dəqiq skripti.",
    coverImage: {
      _type: "image",
      url: "https://images.unsplash.com/photo-1559028012-481c04fa702d?w=1200&h=675&fit=crop&auto=format",
      alt: "Kod Yazmadan Veb-Sayt Yığıb 500 – 1500 AZN-ə Satmaq: Framer və Figma ilə \"No-Code\" Gəlir Modeli",
    },
    publishDate: "12 Avqust 2026",
    readTime: "9 dəq oxu",
    featured: false,
    tags: ["framer", "no code", "veb sayt", "figma to framer", "pul qazanmaq", "landing page"],
    body: [
      createBlock("Gartner-in proqnozuna görə, 2026-cı ilə qədər dünyada yaradılan yeni tətbiq və saytların 70%-dən çoxu No-Code və Low-Code alətləri ilə hazırlanacaq.", "normal"),
      createBlock("Tək bir dizayner 1 sətr kod yazmadan Figma dizaynını 2 gün ərzində işlək, animasiyalı və SEO-dostu Framer saytına çevirib 500 - 1500 AZN-ə sata bilər.", "normal"),
      createBlock("3 Addımlıq Zəncir:", "h3"),
      createBlock("1. **Figma:** Auto Layout ilə dizayn.", "normal"),
      createBlock("2. **Framer Plugin:** \"Figma to Framer\" ilə birbaşa kopyalama.", "normal"),
      createBlock("3. **İnteraktivlik:** Scroll effektləri və əlaqə formaları.", "normal"),
      createBlock("Mənbələr:", "h3"),
      createBlock("1. Gartner Research – Forecast Analysis: No-Code Development.", "normal"),
      createBlock("2. Framer Documentation & Case Studies.", "normal")
    ],
    body_az: [
      createBlock("Gartner-in proqnozuna görə, 2026-cı ilə qədər dünyada yaradılan yeni tətbiq və saytların 70%-dən çoxu No-Code və Low-Code alətləri ilə hazırlanacaq.", "normal"),
      createBlock("Tək bir dizayner 1 sətr kod yazmadan Figma dizaynını 2 gün ərzində işlək, animasiyalı və SEO-dostu Framer saytına çevirib 500 - 1500 AZN-ə sata bilər.", "normal"),
      createBlock("3 Addımlıq Zəncir:", "h3"),
      createBlock("1. **Figma:** Auto Layout ilə dizayn.", "normal"),
      createBlock("2. **Framer Plugin:** \"Figma to Framer\" ilə birbaşa kopyalama.", "normal"),
      createBlock("3. **İnteraktivlik:** Scroll effektləri və əlaqə formaları.", "normal"),
      createBlock("Mənbələr:", "h3"),
      createBlock("1. Gartner Research – Forecast Analysis: No-Code Development.", "normal"),
      createBlock("2. Framer Documentation & Case Studies.", "normal")
    ],
    seo: {
      metaTitle: "Kod Yazmadan Veb-Sayt Yığıb 500 – 1500 AZN-ə Satmaq: Framer və Figma ilə \"No-Code\" Gəlir Modeli | Rvan.me",
      metaDescription: "Gartner-in 70%-lik No-Code proqnozu. Figma-dan Framer-ə 3 addımlıq istehsal zənciri və yerli bizneslərə Landing Page satmağın dəqiq skripti.",
      canonicalUrl: "https://www.rvan.me/blog/kod-yazmadan-sayt-yigib-satmaq-framer-no-code"
    }
  },
  {
    _id: "blog-masterclass-0-tecrube-ile-ilk-1000-azn-deyer-auditi-metodu",
    title: "0 Təcrübə və Portfelio Olmadan İlk 1000 AZN-i Qazanmaq: \"Dəyər Auditi\" Metodu ilə Müştəri Tapmağın Dəqiq Planı",
    title_az: "0 Təcrübə və Portfelio Olmadan İlk 1000 AZN-i Qazanmaq: \"Dəyər Auditi\" Metodu ilə Müştəri Tapmağın Dəqiq Planı",
    slug: { _type: "slug", current: "0-tecrube-ile-ilk-1000-azn-deyer-auditi-metodu" },
    slug_az: { _type: "slug", current: "0-tecrube-ile-ilk-1000-azn-deyer-auditi-metodu" },
    originalSlug: "0-tecrube-ile-ilk-1000-azn-deyer-auditi-metodu",
    category: "Satış & Frilans",
    category_az: "Satış & Frilans",
    excerpt: "Aleks Hormozinin '$100M Leads' prinsipləri. Xidmət satmaq yerinə biznesin itirdiyi pulu göstərən 2 dəqiqəlik Loom audit strategiyası.",
    excerpt_az: "Aleks Hormozinin '$100M Leads' prinsipləri. Xidmət satmaq yerinə biznesin itirdiyi pulu göstərən 2 dəqiqəlik Loom audit strategiyası.",
    coverImage: {
      _type: "image",
      url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&h=675&fit=crop&auto=format",
      alt: "0 Təcrübə və Portfelio Olmadan İlk 1000 AZN-i Qazanmaq: \"Dəyər Auditi\" Metodu ilə Müştəri Tapmağın Dəqiq Planı",
    },
    publishDate: "10 Avqust 2026",
    readTime: "9 dəq oxu",
    featured: false,
    tags: ["ilk musteri", "frilans", "satis", "alex hormozi", "deyer auditi", "pul qazanmaq"],
    body: [
      createBlock("İnsanlar heç vaxt \"loqo\" və ya \"kod\" almaq istəmirlər; insanlar öz problemlərindən qurtulmaq istəyirlər.", "normal"),
      createBlock("\"Dəyər Auditi\" Addımları:", "h3"),
      createBlock("1. Yaxşı gəlirli 10 yerli biznes seçin.", "normal"),
      createBlock("2. Onların saytında və ya reklamındakı 2 kritik səhvi tapın.", "normal"),
      createBlock("3. Həmin səhvi düzəldib 2 dəqiqəlik Loom videosu ilə sahibkara pulsuz göndərin.", "normal"),
      createBlock("15 fərdiləşdirilmiş mesajdan ən az 2-si aylıq 500 AZN-lik xidmət müqaviləsinə çevrilir.", "normal"),
      createBlock("Mənbələr:", "h3"),
      createBlock("1. Hormozi, A. – \"$100M Leads\".", "normal"),
      createBlock("2. Kennedy, D. – \"No B.S. Direct Marketing\".", "normal")
    ],
    body_az: [
      createBlock("İnsanlar heç vaxt \"loqo\" və ya \"kod\" almaq istəmirlər; insanlar öz problemlərindən qurtulmaq istəyirlər.", "normal"),
      createBlock("\"Dəyər Auditi\" Addımları:", "h3"),
      createBlock("1. Yaxşı gəlirli 10 yerli biznes seçin.", "normal"),
      createBlock("2. Onların saytında və ya reklamındakı 2 kritik səhvi tapın.", "normal"),
      createBlock("3. Həmin səhvi düzəldib 2 dəqiqəlik Loom videosu ilə sahibkara pulsuz göndərin.", "normal"),
      createBlock("15 fərdiləşdirilmiş mesajdan ən az 2-si aylıq 500 AZN-lik xidmət müqaviləsinə çevrilir.", "normal"),
      createBlock("Mənbələr:", "h3"),
      createBlock("1. Hormozi, A. – \"$100M Leads\".", "normal"),
      createBlock("2. Kennedy, D. – \"No B.S. Direct Marketing\".", "normal")
    ],
    seo: {
      metaTitle: "0 Təcrübə və Portfelio Olmadan İlk 1000 AZN-i Qazanmaq: \"Dəyər Auditi\" Metodu ilə Müştəri Tapmağın Dəqiq Planı | Rvan.me",
      metaDescription: "Aleks Hormozinin '$100M Leads' prinsipləri. Xidmət satmaq yerinə biznesin itirdiyi pulu göstərən 2 dəqiqəlik Loom audit strategiyası.",
      canonicalUrl: "https://www.rvan.me/blog/0-tecrube-ile-ilk-1000-azn-deyer-auditi-metodu"
    }
  },
  {
    _id: "blog-masterclass-reqemsal-sablonlar-sataraq-passiv-gelir-gumroad",
    title: "Yatarkən Dollar Qazanmaq: Rəqəmsal Şablonlar (Figma, Notion, Canva) Sataraq Passiv Gəlir Qurmağın 4 Addımı",
    title_az: "Yatarkən Dollar Qazanmaq: Rəqəmsal Şablonlar (Figma, Notion, Canva) Sataraq Passiv Gəlir Qurmağın 4 Addımı",
    slug: { _type: "slug", current: "reqemsal-sablonlar-sataraq-passiv-gelir-gumroad" },
    slug_az: { _type: "slug", current: "reqemsal-sablonlar-sataraq-passiv-gelir-gumroad" },
    originalSlug: "reqemsal-sablonlar-sataraq-passiv-gelir-gumroad",
    category: "Passiv Gəlir & Məhsul",
    category_az: "Passiv Gəlir & Məhsul",
    excerpt: "Naval Ravikantın 'İcazəsiz Leverec' fəlsəfəsi. Figma UI Kit, Framer Template və Notion şablonları ilə aylıq 500-2000$ passiv gəlir qurmaq.",
    excerpt_az: "Naval Ravikantın 'İcazəsiz Leverec' fəlsəfəsi. Figma UI Kit, Framer Template və Notion şablonları ilə aylıq 500-2000$ passiv gəlir qurmaq.",
    coverImage: {
      _type: "image",
      url: "https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=1200&h=675&fit=crop&auto=format",
      alt: "Yatarkən Dollar Qazanmaq: Rəqəmsal Şablonlar (Figma, Notion, Canva) Sataraq Passiv Gəlir Qurmağın 4 Addımı",
    },
    publishDate: "08 Avqust 2026",
    readTime: "9 dəq oxu",
    featured: false,
    tags: ["passiv gelir", "gumroad", "figma template", "notion template", "naval ravikant", "dollar"],
    body: [
      createBlock("Naval Ravikant: \"Siz yatarkən pul qazanmağın yolunu tapmasanız, ölənə qədər işləməyə məhkumsunuz.\"", "normal"),
      createBlock("Rəqəmsal məhsulun marjası 95%-dən yüksəkdir: 1 dəfə yarat, minlərlə dəfə sat.", "normal"),
      createBlock("Ən Çox Tələbat Olan 3 Məhsul:", "h3"),
      createBlock("1. **Figma UI Kit & Dizayn Sistemləri** (30-80$)", "normal"),
      createBlock("2. **Framer & Webflow Şablonları** (49-99$)", "normal"),
      createBlock("3. **Notion Məhsuldarlıq Şablonları** (10-30$)", "normal"),
      createBlock("Satış platformaları: Gumroad, Lemon Squeezy, Framer Template Marketplace.", "normal"),
      createBlock("Mənbələr:", "h3"),
      createBlock("1. Ravikant, N. – \"How to Get Rich Without Getting Lucky\".", "normal"),
      createBlock("2. Gumroad Creator Economics Report 2024.", "normal")
    ],
    body_az: [
      createBlock("Naval Ravikant: \"Siz yatarkən pul qazanmağın yolunu tapmasanız, ölənə qədər işləməyə məhkumsunuz.\"", "normal"),
      createBlock("Rəqəmsal məhsulun marjası 95%-dən yüksəkdir: 1 dəfə yarat, minlərlə dəfə sat.", "normal"),
      createBlock("Ən Çox Tələbat Olan 3 Məhsul:", "h3"),
      createBlock("1. **Figma UI Kit & Dizayn Sistemləri** (30-80$)", "normal"),
      createBlock("2. **Framer & Webflow Şablonları** (49-99$)", "normal"),
      createBlock("3. **Notion Məhsuldarlıq Şablonları** (10-30$)", "normal"),
      createBlock("Satış platformaları: Gumroad, Lemon Squeezy, Framer Template Marketplace.", "normal"),
      createBlock("Mənbələr:", "h3"),
      createBlock("1. Ravikant, N. – \"How to Get Rich Without Getting Lucky\".", "normal"),
      createBlock("2. Gumroad Creator Economics Report 2024.", "normal")
    ],
    seo: {
      metaTitle: "Yatarkən Dollar Qazanmaq: Rəqəmsal Şablonlar (Figma, Notion, Canva) Sataraq Passiv Gəlir Qurmağın 4 Addımı | Rvan.me",
      metaDescription: "Naval Ravikantın 'İcazəsiz Leverec' fəlsəfəsi. Figma UI Kit, Framer Template və Notion şablonları ilə aylıq 500-2000$ passiv gəlir qurmaq.",
      canonicalUrl: "https://www.rvan.me/blog/reqemsal-sablonlar-sataraq-passiv-gelir-gumroad"
    }
  },
];
