import { BlogPost } from "../../types/blog";

function createBlock(text: string, style = "normal", key = Math.random().toString(36).substring(7)) {
  return {
    _key: key,
    _type: "block",
    style,
    markDefs: [],
    children: [{ _key: `${key}-c`, _type: "span", marks: [], text }],
  };
}

function createImageBlock(url: string, alt: string, caption?: string) {
  return {
    _key: Math.random().toString(36).substring(7),
    _type: "image",
    asset: { _type: "reference", _ref: "image-manual" },
    alt,
    caption,
    url,
  };
}

export const ARTICLES_11_TO_20: BlogPost[] = [
  // 11. RULE OF THREE
  {
    _id: "blog-10-graphic-design-rules-art-directors-never-break",
    title: "Why Does the Number 3 Appear Everywhere in Design and Writing?",
    title_az: "Niyə '3 Qaydası' Dizaynda Və Mətndə Hər Yerdə Qarşımıza Çıxır?",
    slug: { _type: "slug", current: "why-the-number-3-appears-everywhere-in-design" },
    slug_az: { _type: "slug", current: "3-qaydasi-dizaynda-ve-metnde" },
    originalSlug: "10-graphic-design-rules",
    category: "Design Psychology",
    category_az: "Dizayn Psixologiyası",
    excerpt: "The Latin maxim 'Omne trium perfectum': Why groups of three satisfy human cognitive pattern recognition in typography, pricing tiers, storytelling, and UI layout.",
    excerpt_az: "'Omne trium perfectum' latın prinsipi: Üçlük qrupları tipoqrafikada, qiymət paketlərində, hekayələrdə və UI tərtibatında niyə ən mükəmməl ahəng yaradır.",
    coverImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "image-three-cover" },
      alt: "Geometric composition of three harmoniously aligned golden ratio spheres",
      url: "https://images.unsplash.com/photo-1509228468518-180dd4864904?w=1200&auto=format&fit=crop&q=80",
    },
    publishDate: "2026-03-24",
    readTime: "8 min read",
    featured: false,
    tags: ["Rule of Three", "Composition", "Design Psychology", "Layout", "Visual Balance"],
    body: [
      createBlock("Why Does the Number 3 Appear Everywhere in Design and Writing?", "h2"),
      createBlock("Goldilocks and the Three Bears. 'Life, Liberty, and the pursuit of Happiness.' 'Veni, vidi, vici.' Basic, Pro, and Enterprise. Stop, Look, and Listen. The three-column grid."),
      createBlock("Throughout human history, literature, rhetoric, and visual design, the number three appears with astonishing frequency. The ancient Romans coined a legal and rhetorical maxim: *Omne trium perfectum*—everything that comes in threes is perfect. Why is our cognitive architecture so deeply drawn to triads?"),
      createBlock("1. The Mathematical Minimum of a Pattern", "h3"),
      createBlock("In cognitive psychology, one element is a point. Two elements are a line or a comparison. But three elements represent the smallest mathematical number required to establish a recognizable pattern."),
      createBlock("The human brain is a tireless pattern-matching engine. When we encounter three items, our brain registers: Introduction, Continuation, Confirmation. It feels rhythmically complete, satisfying, and easy to memorize without overwhelming short-term memory."),
      createBlock("2. Three-Tier Pricing and the Golden Ratio of Choice", "h3"),
      createBlock("In SaaS and product marketing, three options represent the sweet spot between choice paralysis and forced binary ultimatums:"),
      createBlock("• Tier 1 (Starter): Protects against low-budget drop-off."),
      createBlock("• Tier 2 (Pro - The Anchor/Target): Highlighted as 'Most Popular' and engineered for 70%+ adoption."),
      createBlock("• Tier 3 (Enterprise): Serves as the luxury price anchor, making Tier 2 look remarkably reasonable."),
    ],
  },

  // 12. LOGO MEMORABILITY & GESTALT
  {
    _id: "blog-brand-identity-design-systems",
    title: "Why Are Some Logos Impossible to Forget?",
    title_az: "Bəzi Loqolar Niyə Heç Vaxt Yaddan Çıxmır?",
    slug: { _type: "slug", current: "why-some-logos-are-impossible-to-forget" },
    slug_az: { _type: "slug", current: "bezi-loqolar-niye-unudulmur" },
    originalSlug: "brand-identity-design-systems",
    category: "Creative & Culture",
    category_az: "Kreativ və Mədəniyyət",
    excerpt: "Gestalt closure, radical simplicity, and the Von Restorff Isolation Effect: How FedEx, Apple, and Nike engineered symbols that burn into human neural circuitry.",
    excerpt_az: "Gestalt tamamlama, radikal sadəlik və Von Restorff Təcrid Effekti: FedEx, Apple və Nike-ın insan neyronlarına həkk olunan simvolları necə yaratdığı.",
    coverImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "image-logo-cover" },
      alt: "Iconic minimalist monochrome vector identity mark with negative space illusion",
      url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&auto=format&fit=crop&q=80",
    },
    publishDate: "2026-03-26",
    readTime: "9 min read",
    featured: true,
    tags: ["Logo Design", "Branding", "Gestalt Psychology", "Visual Identity", "Memorability"],
    body: [
      createBlock("Why Are Some Logos Impossible to Forget?", "h2"),
      createBlock("Think of the Nike Swoosh. Think of the Apple with a missing bite. Think of the hidden white arrow between the 'E' and 'x' in FedEx. You can sketch these marks from memory in two seconds on a napkin. Now try sketching the logo of your local health insurance company. You probably can't even remember its shape."),
      createBlock("Why do certain visual marks achieve permanent neural residency in billions of human brains while others evaporate instantly?"),
      createBlock("1. The Gestalt Law of Closure (The Secret Reward of Discovery)", "h3"),
      createBlock("The FedEx logo, designed by Lindon Leader in 1994, is a textbook masterpiece of Gestalt Closure. The negative space between the capital 'E' and lowercase 'x' forms a razor-sharp forward-pointing arrow. When a viewer discovers that hidden arrow for the first time, their brain experiences a delightful moment of cognitive completion."),
      createBlock("That 'Aha!' moment permanently encodes the logo into episodic memory. The brain loves solving small visual riddles, and when a brand offers that reward, the symbol becomes indelible."),
      createBlock("2. Radical Reducibility: The 5-Second Billboard Test", "h3"),
      createBlock("Legendary designer Paul Rand noted: 'A logo does not sell; it identifies.' The most memorable logos on earth are radically simple geometric silhouettes that survive at 16x16 pixels on a smartwatch screen or on a highway billboard viewed at 70 mph for half a second."),
    ],
  },

  // 13. RESTAURANT MENU PSYCHOLOGY & DECOY ANCHORS
  {
    _id: "blog-brand-positioning-matrix",
    title: "Why Do Restaurants Put One Ridiculously Expensive Dish on the Menu?",
    title_az: "Restoranlar Menyuya Niyə Gülünc Dərəcədə Bahalı Bir Yemək Qoyurlar?",
    slug: { _type: "slug", current: "why-restaurants-put-expensive-dish-on-menu" },
    slug_az: { _type: "slug", current: "restoran-menyu-lovber-qiymet-psixologiyasi" },
    originalSlug: "brand-positioning-matrix",
    category: "Marketing Psychology",
    category_az: "Marketinq Psixologiyası",
    excerpt: "Menu engineering and price contrast: How an absurd $180 seafood tower makes the $48 ribeye steak look like an absolute bargain.",
    excerpt_az: "Menyu mühəndisliyi və qiymət kontrastı: $180-lıq dəniz məhsulları qabının $48-lıq steyki necə inanılmaz sərfəli təklifə çevirdiyi.",
    coverImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "image-menu-cover" },
      alt: "Fine dining restaurant menu with elegant typographic layout and price anchors",
      url: "https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=1200&auto=format&fit=crop&q=80",
    },
    publishDate: "2026-03-28",
    readTime: "8 min read",
    featured: false,
    tags: ["Menu Psychology", "Pricing Anchoring", "Decoy Effect", "Behavioral Economics", "Consumer Behavior"],
    body: [
      createBlock("Why Do Restaurants Put One Ridiculously Expensive Dish on the Menu?", "h2"),
      createBlock("When you open a high-end restaurant menu, your eyes will frequently land on an outrageous item: a $180 Grand Seafood Platter or a $220 32oz Dry-Aged Tomahawk Steak with Gold Leaf."),
      createBlock("Here is the secret of menu engineering: The restaurant does not actually expect many guests to order that $180 dish. Its primary purpose on the menu is not culinary; it is purely psychological. It is a 'Price Anchor'."),
      createBlock("1. The Relativity of Numbers", "h3"),
      createBlock("If a menu's most expensive item is a $45 steak, paying $45 feels steep. But when the eye first encounters a $180 anchor at the top of the page, the $45 steak immediately feels modest, reasonable, and safe by comparison."),
      createBlock("This is the Contrast Effect. Human beings are terrible at judging absolute numerical value, but exceptionally good at judging comparative differences. By anchoring the top of the scale at an extreme number, everything beneath it shifts into the 'acceptable' cognitive zone."),
      createBlock("2. Omitting Dollar Signs ($)", "h3"),
      createBlock("Cornell University researchers proved that menus that omit dollar signs (e.g., printing '38' instead of '$38') cause diners to spend 8.1% more on average. The currency symbol activates the 'Pain of Paying' in the brain's insular cortex. Removing the symbol decouples the gastronomic enjoyment from financial loss."),
    ],
  },

  // 14. MOTION DESIGN MECHANICS & UI PHYSICS
  {
    _id: "blog-motion-design-mechanics",
    title: "Why Does Good Animation Feel Natural? (The Physics of UI)",
    title_az: "Yaxşı Animasiya Niyə Təbii Hiss Etdirir? (UI-ın Görünməz Fizikası)",
    slug: { _type: "slug", current: "why-good-animation-feels-natural-ui-physics" },
    slug_az: { _type: "slug", current: "yaxsi-animasiya-ve-ui-fizikasi" },
    originalSlug: "motion-design-mechanics",
    category: "Creative & Culture",
    category_az: "Kreativ və Mədəniyyət",
    excerpt: "Disney's 12 principles adapted to modern interface design: Cubic bezier easing curves, momentum, mass, and why linear transitions feel robotic and jarring.",
    excerpt_az: "Disney-in 12 animasiya prinsipinin müasir interfeysə tətbiqi: Cubic bezier əyriləri, impuls, kütlə və xətti keçidlərin niyə süni hiss etdirdiyi.",
    coverImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "image-motion-cover" },
      alt: "Abstract 3D motion wave displaying fluid physics easing trajectories",
      url: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=1200&auto=format&fit=crop&q=80",
    },
    publishDate: "2026-03-30",
    readTime: "9 min read",
    featured: true,
    tags: ["Motion Design", "UI Animation", "Easing Curves", "Physics", "User Experience"],
    body: [
      createBlock("Why Does Good Animation Feel Natural? (The Physics of UI)", "h2"),
      createBlock("When an object moves in the physical world—a dropped tennis ball, an opening door, or an apple falling from a tree—it never moves at constant velocity from instant zero to a dead stop. It must overcome inertia, accelerate smoothly, and decelerate gradually due to friction and gravity."),
      createBlock("Yet in amateur digital interfaces, elements routinely teleport across the screen with `transition: all 0.3s linear`. The human brain immediately recoils at linear motion because it violates every law of physics our nervous system evolved to track."),
      createBlock("1. The Beauty of Cubic-Bezier and Spring Dynamics", "h3"),
      createBlock("Natural motion relies on non-linear easing curves. An ease-out curve (`cubic-bezier(0.16, 1, 0.3, 1)`) launches with instant responsiveness to user input, then gracefully settles into its resting position. Modern UI frameworks like Framer Motion and SwiftUI embrace spring physics with mass, stiffness, and damping, allowing elements to interact with realistic tactile momentum."),
      createBlock("2. Functional vs. Decorative Motion", "h3"),
      createBlock("Great motion is invisible. It does not distract; it communicates spatial relationships, clarifies parent-child hierarchies, and confirms state changes before the user has to guess what just happened."),
    ],
  },

  // 15. ZEIGARNIK EFFECT & "YOU'RE ALMOST DONE"
  {
    _id: "blog-ui-ux-principles-reducing-cognitive-load",
    title: "Why Does 'You're Almost Done' Work So Well?",
    title_az: "Niyə 'Demək Olar Ki Bitirdiniz' Bildirişi Bu Qədər Güclüdür?",
    slug: { _type: "slug", current: "why-youre-almost-done-works-zeigarnik-effect" },
    slug_az: { _type: "slug", current: "zeigarnik-effekti-ve-tamamlama-psixologiyasi" },
    originalSlug: "ui-ux-principles-reducing-cognitive-load",
    category: "Design Psychology",
    category_az: "Dizayn Psixologiyası",
    excerpt: "The Zeigarnik Effect and Clark Hull's Goal Gradient Hypothesis: How incomplete tasks create mental tension that compels users to finish multi-step checkouts.",
    excerpt_az: "Zeigarnik Effekti və Məqsəd Qradiyenti Nəzəriyyəsi: Yarımçıq qalan işlərin yaratdığı zehni gərginlik istifadəçiləri qeydiyyatı bitirməyə necə məcbur edir.",
    coverImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "image-progress-cover" },
      alt: "Circular progress bar glowing at 85 percent completion on sleek interface",
      url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&auto=format&fit=crop&q=80",
    },
    publishDate: "2026-04-01",
    readTime: "8 min read",
    featured: false,
    tags: ["Zeigarnik Effect", "Goal Gradient", "Gamification", "UX Psychology", "Onboarding"],
    body: [
      createBlock("Why Does 'You're Almost Done' Work So Well?", "h2"),
      createBlock("In the 1920s, Soviet psychologist Bluma Zeigarnik sat in a bustling Vienna café. She observed that the waiters could remember dozens of complex, unpaid table orders with pinpoint accuracy. But the second the bill was paid, the waiters completely forgot the orders."),
      createBlock("Zeigarnik conducted controlled experiments and discovered a fundamental truth about human cognition: **Incomplete tasks create lingering cognitive tension in working memory.** Until an open loop is closed, the brain refuses to let go."),
      createBlock("1. The Goal Gradient Hypothesis (Clark Hull)", "h3"),
      createBlock("In 1932, psychologist Clark Hull placed rats in a maze with food at the finish line. He discovered that the closer the rats got to the food, the faster they ran. Human beings exhibit the exact same behavioral acceleration: our effort and motivation intensify dramatically as the perceived distance to the goal decreases."),
      createBlock("2. The Endowed Progress Illusion", "h3"),
      createBlock("In a famous car wash study by Nunes and Drèze (2006), two groups received loyalty cards:"),
      createBlock("• Group A: Card required 8 stamps to get a free wash (0 out of 8 complete)."),
      createBlock("• Group B: Card required 10 stamps, but came pre-stamped with 2 free stamps (2 out of 10 complete)."),
      createBlock("Mathematically, both groups needed exactly 8 more washes. Yet Group B completed the card nearly twice as fast (34% vs 19% completion rate)! The feeling of already having started provided the psychological momentum needed to complete the task."),
    ],
  },

  // 16. SOCIAL PROOF / "MOST POPULAR"
  {
    _id: "blog-conversion-rate-optimization-cro",
    title: "Why Does 'Most Popular' Work So Well on Pricing Tables?",
    title_az: "Qiymət Cədvəllərində 'Ən Məşhur' Nişanı Niyə Bu Qədər Yaxşı İşləyir?",
    slug: { _type: "slug", current: "why-most-popular-works-on-pricing-tables" },
    slug_az: { _type: "slug", current: "en-meshur-nisani-ve-sosial-subut" },
    originalSlug: "conversion-rate-optimization-cro",
    category: "Marketing Psychology",
    category_az: "Marketinq Psixologiyası",
    excerpt: "Robert Cialdini's Social Proof principle and default heuristics: How highlighting a specific tier eliminates decision paralysis and shifts 70% of conversions.",
    excerpt_az: "Robert Cialdini-nin Sosial Sübut prinsipi və qərar asanlığı: Bir paketi vurğulamaq seçimlər arasındakı çaşqınlığı aradan qaldıraraq satışları necə artırır.",
    coverImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "image-popular-cover" },
      alt: "Three modern SaaS pricing cards with center card elevated with glowing popular badge",
      url: "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=1200&auto=format&fit=crop&q=80",
    },
    publishDate: "2026-04-03",
    readTime: "8 min read",
    featured: false,
    tags: ["Social Proof", "Pricing Tables", "Cialdini", "SaaS Growth", "CRO"],
    body: [
      createBlock("Why Does 'Most Popular' Work So Well on Pricing Tables?", "h2"),
      createBlock("When potential customers face multiple subscription tiers (e.g., $19/mo, $49/mo, $199/mo), they experience cognitive friction. They ask themselves: *'Am I overpaying if I buy the high tier? Will the low tier be missing critical features?'*"),
      createBlock("The moment a designer elevates the middle card and places a glowing badge labeled 'Most Popular' or 'Best Value', conversion rates on that tier skyrocket by up to 40%. Why?"),
      createBlock("1. Social Proof as an Evolutionary Shortcut", "h3"),
      createBlock("In Dr. Robert Cialdini's seminal work *Influence: The Psychology of Persuasion*, Social Proof is identified as one of the core principles that guide human decision-making under uncertainty. When we are unsure of what to do, we look to the actions of others to validate our choice."),
      createBlock("A 'Most Popular' badge reassures the buyer that hundreds of other smart people have already vetted this exact tier. It removes the fear of making a costly solo mistake."),
      createBlock("2. The Power of the Default Effect", "h3"),
      createBlock("Human beings possess a strong bias toward the default option. By elevating the target tier with distinct visual hierarchy (a subtle border glow, a slightly larger scale, and a pre-selected radio button), the designer transforms that tier into the natural cognitive default."),
    ],
  },

  // 17. CREATOR AUTHENTICITY VS CELEBRITIES
  {
    _id: "blog-social-proof-frameworks",
    title: "Why Do Small Creators Sometimes Sell More Than Celebrities?",
    title_az: "Kiçik Yaradıcılar Niyə Bəzən Məşhurlardan Daha Çox Məhsul Satırlar?",
    slug: { _type: "slug", current: "why-small-creators-sell-more-than-celebrities" },
    slug_az: { _type: "slug", current: "kicik-yaradicilar-ve-otentiklik-gucu" },
    originalSlug: "social-proof-frameworks",
    category: "Marketing Psychology",
    category_az: "Marketinq Psixologiyası",
    excerpt: "Parasocial intimacy and the collapse of glossy celebrity endorsements: Why niche audiences trust a creator with 10k engaged followers over an A-list actor.",
    excerpt_az: "Parasosial yaxınlıq və ənənəvi məşhur reklamlarının iflası: Niyə 10 min sadiq izləyicisi olan bir yaradıcıya Hollivud ulduzundan daha çox güvənirik.",
    coverImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "image-creator-cover" },
      alt: "Independent creator recording honest unscripted video review with natural studio lighting",
      url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=1200&auto=format&fit=crop&q=80",
    },
    publishDate: "2026-04-05",
    readTime: "9 min read",
    featured: false,
    tags: ["Creator Economy", "Parasocial Interaction", "Influencer Marketing", "Trust", "Branding"],
    body: [
      createBlock("Why Do Small Creators Sometimes Sell More Than Celebrities?", "h2"),
      createBlock("In the 1990s, a multimillion-dollar endorsement deal with an A-list Hollywood star was the undisputed pinnacle of advertising. In 2026, consumer brands are discovering that a single unscripted review from a niche YouTube creator with 25,000 subscribers can generate five times more revenue than a celebrity campaign costing ten times as much."),
      createBlock("What changed in consumer psychology?"),
      createBlock("1. The Erosion of Polished Fabrication", "h3"),
      createBlock("Modern consumers have developed extreme visual immunity to polished, staged commercial advertisements. Everyone knows the celebrity does not use that $8 shampoo or drive that mass-market sedan; they were paid millions to hold the bottle for thirty seconds."),
      createBlock("Micro-creators, by contrast, build their reputation over years of authentic, candid community engagement. When they recommend a tool, their personal credibility is on the line. The audience perceives their recommendation as advice from a trusted friend rather than a commercial transaction."),
      createBlock("2. Parasocial Intimacy and Niche Authority", "h3"),
      createBlock("Psychologists Horton and Wohl coined 'Parasocial Interaction' to describe the one-sided emotional bond people form with media figures. In niche subcultures (woodworking, UI design, mechanical keyboards, specialty coffee), a creator is not an untouchable idol—they are an accessible expert in a shared passion."),
    ],
  },

  // 18. FLOPPY DISK & SKEUOMORPHIC INERTIA
  {
    _id: "blog-viral-growth-loops",
    title: "Why Is the Save Icon Still a Floppy Disk in 2026?",
    title_az: "2026-cı İldə Yadda Saxla İkonu Niyə Hələ Də Diskətdir?",
    slug: { _type: "slug", current: "why-save-icon-is-still-a-floppy-disk" },
    slug_az: { _type: "slug", current: "yadda-saxla-ikonu-niye-diskisdir" },
    originalSlug: "viral-growth-loops",
    category: "Design History",
    category_az: "Dizayn Tarixi",
    excerpt: "Skeuomorphic inertia and semiotic shifts: Why an obsolete magnetic storage square from 1981 remains the immortal universal symbol of data persistence.",
    excerpt_az: "Skevomorfizm ətaləti və semiotika: 1981-ci ilin köhnəlmiş 3.5 düymlük disketinin necə məlumatı qorumağın əbədi qlobal simvoluna çevrilməsi.",
    coverImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "image-floppy-cover" },
      alt: "Vintage 3.5 inch floppy disk resting next to ultra-modern glowing digital interface",
      url: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=1200&auto=format&fit=crop&q=80",
    },
    publishDate: "2026-04-08",
    readTime: "8 min read",
    featured: true,
    tags: ["Floppy Disk", "Design History", "Semiotics", "Iconography", "Skeuomorphism"],
    body: [
      createBlock("Why Is the Save Icon Still a Floppy Disk in 2026?", "h2"),
      createBlock("Ask a 14-year-old child to identify a real physical 3.5-inch floppy disk, and they might call it a '3D printed model of the Save button'. It is one of the most amusing paradoxes of modern technology: an artifact that has been obsolete for twenty years remains the undisputed global icon for saving data."),
      createBlock("Why has no designer successfully replaced it with a cloud, an arrow, or a hard drive?"),
      createBlock("1. The Immense Cost of Re-learning Universal Symbols", "h3"),
      createBlock("Once an arbitrary visual mark achieves global consensus across billions of users and thousands of software applications, the cost of changing it becomes astronomical. If Microsoft, Apple, and Google decided tomorrow to change the Save icon to a downward cloud arrow, hundreds of millions of users would experience immediate disorientation."),
      createBlock("2. From Skeuomorphic Affordance to Pure Semiotic Glyphs", "h3"),
      createBlock("In linguistics, words frequently outlive their etymological origins (we still say 'dial a number' on touchscreens and 'roll up the window' in electric cars). The floppy disk icon has completed this journey: it is no longer an image of magnetic plastic; it is a hieroglyphic character meaning 'Save'."),
    ],
  },

  // 19. ZERO PRICE EFFECT / THE POWER OF "FREE"
  {
    _id: "blog-customer-lifetime-value-ltv",
    title: "Why Does 'Free' Make People Buy Things They Never Wanted?",
    title_az: "'Pulsuz' Sözü İnsanlara Niyə Heç Vaxt İstəmədikləri Şeyləri Aldırır?",
    slug: { _type: "slug", current: "why-free-makes-people-buy-zero-price-effect" },
    slug_az: { _type: "slug", current: "pulsuz-sozunun-qeyri-adi-psixologiyasi" },
    originalSlug: "customer-lifetime-value-ltv",
    category: "Marketing Psychology",
    category_az: "Marketinq Psixologiyası",
    excerpt: "Dan Ariely's Zero Price Effect: Why a drop from 1 cent to 0 cents causes a non-linear psychological explosion in demand compared to a drop from $2 to $1.",
    excerpt_az: "Dan Ariely-nin Sıfır Qiymət Effekti: 1 qəpikdən 0 qəpiyə enməyin insan beynində yaratdığı irrasional emosional təsir və pulsuz çatdırılma sehri.",
    coverImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "image-free-cover" },
      alt: "Minimalist gift box wrapped with satin ribbon representing the zero price effect",
      url: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=1200&auto=format&fit=crop&q=80",
    },
    publishDate: "2026-04-10",
    readTime: "9 min read",
    featured: false,
    tags: ["Zero Price Effect", "Behavioral Economics", "Pricing Psychology", "Dan Ariely", "Consumer Habits"],
    body: [
      createBlock("Why Does 'Free' Make People Buy Things They Never Wanted?", "h2"),
      createBlock("In his landmark book *Predictably Irrational*, MIT behavioral economist Dan Ariely set up a chocolate stand to test human decision-making with two chocolates:"),
      createBlock("• A luxury Lindt truffle (normally 50 cents) priced at 15 cents."),
      createBlock("• An ordinary Hershey's Kiss (normally 5 cents) priced at 1 cent."),
      createBlock("At these prices, 73% of people chose the Lindt truffle. They correctly calculated that getting a luxury 50-cent truffle for only 15 cents was an incredible deal."),
      createBlock("Then Ariely lowered the price of both by exactly one single cent:"),
      createBlock("• The Lindt truffle was now 14 cents."),
      createBlock("• The Hershey's Kiss was now FREE (0 cents)."),
      createBlock("The price difference between the two chocolates remained exactly the same (14 cents). If humans were purely rational economic calculators, their preferences should not have changed. Instead, **69% of people suddenly chose the Hershey's Kiss!**"),
      createBlock("1. The Emotional Surge of Zero Risk", "h3"),
      createBlock("When something costs even 1 single cent, the brain must perform a cost-benefit calculation: *'Is this worth paying for?'* There is always a risk of buyer's remorse."),
      createBlock("When the price drops to ZERO, the perceived risk vanishes entirely. The brain views 'Free' not as a numerical price, but as an emotional trigger that signals pure upside with zero downside. That is why people will wait in line for 45 minutes for a free scoop of ice cream they wouldn't cross the street to buy for $1."),
    ],
  },

  // 20. "ONLY 3 LEFT IN STOCK" / SCARCITY HEURISTIC
  {
    _id: "blog-data-driven-marketing-analytics",
    title: "Why Does 'Only 3 Left in Stock' Make You Panic Buy?",
    title_az: "'Yalnız 3 Ədəd Qaldı' Yazısı Niyə Ani Alış Panikası Yaradır?",
    slug: { _type: "slug", current: "why-only-3-left-makes-you-panic-buy-scarcity" },
    slug_az: { _type: "slug", current: "mehdud-sayda-qalma-psixologiyasi" },
    originalSlug: "data-driven-marketing-analytics",
    category: "Marketing Psychology",
    category_az: "Marketinq Psixologiyası",
    excerpt: "The scarcity heuristic, evolutionary resource competition, and how e-commerce stock counters trigger immediate purchasing impulses.",
    excerpt_az: "Qıtlıq evristikası və təkamül rəqabəti: E-ticarət platformalarındakı qalıq sayğaclarının ani alış qərarlarını necə sürətləndirdiyi.",
    coverImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "image-scarcity-cover" },
      alt: "Hourglass with running sand visualizing time constraint and inventory scarcity",
      url: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1200&auto=format&fit=crop&q=80",
    },
    publishDate: "2026-04-12",
    readTime: "8 min read",
    featured: false,
    tags: ["Scarcity", "E-Commerce Psychology", "Consumer Behavior", "Conversion", "Urgency"],
    body: [
      createBlock("Why Does 'Only 3 Left in Stock' Make You Panic Buy?", "h2"),
      createBlock("You find a pair of sneakers you like. You consider bookmarking the tab to think about it for a few days. Then you notice a small amber indicator beneath the size selector: *'Only 2 pairs remaining at this price!'*"),
      createBlock("Suddenly, your heart rate elevates. You enter your credit card details immediately. What neurological mechanisms triggered that sudden shift from casual deliberation to urgent action?"),
      createBlock("1. The Evolutionary Primate Brain: Resource Competition", "h3"),
      createBlock("For 99% of human history, resources (shelter, fresh meat, tools, clean water) were strictly limited. Seeing another primate approach a scarce resource meant: *Take it now or starve.*"),
      createBlock("When a digital interface displays 'Only 3 left', it triggers that ancestral threat network. We subconsciously perceive other unseen buyers competing for our desired item, bypassing slow analytical thinking (System 2) and activating fast emotional action (System 1)."),
      createBlock("2. The Scarcity Heuristic: 'Rare Equals Valuable'", "h3"),
      createBlock("In consumer psychology, we use scarcity as an automatic heuristic for quality: If an item is almost sold out, it must be exceptionally desirable. When e-commerce brands deploy this ethically based on real inventory levels, it remains one of the highest-converting signals in commerce."),
    ],
  },
];
