import { BlogPost } from "../../types/blog";

function createBlock(text: string, style = "normal", key = Math.random().toString(36).substring(7)) {
  return {
    _key: key,
    _type: "block",
    style,
    markDefs: [],
    children: [{ _key: `${key}-c`, _type: "span", marks: [], text }],
  };
}

export const ARTICLES_VIRAL_MASTERCLASS: BlogPost[] = [
  // ── 01. Salary Negotiation ──
  {
    _id: "blog-masterclass-maas-danisigi-psixologiyasi-harvard-metodu",
    title: "Who Should Name the First Number in Salary Negotiation?",
    title_az: "Maaş Danışığında İlk Rəqəmi Kim Deməlidir?",
    deck: "Daniel Kahneman's anchoring bias, Harvard negotiation frameworks, and FBI hostage scripts for landing top-tier compensation offers.",
    deck_az: "Daniel Kanemanın Lövbər effekti, Harvard danışıqlar modeli və şirkətlərin büdcə tələsindən çıxmaq üçün dəqiq skriptlər.",
    slug: { _type: "slug", current: "salary-negotiation-psychology-harvard-method" },
    slug_az: { _type: "slug", current: "maas-danisigi-psixologiyasi-harvard-metodu" },
    originalSlug: "maas-danisigi-psixologiyasi-harvard-metodu",
    category: "Career & Negotiation",
    category_az: "Karyera & Danışıqlar",
    format: "Bələdçi",
    cluster: "career",
    excerpt: "Who should speak first when discussing compensation? Discover how anchoring heuristics, calibrated open-ended questions, and total compensation bundling create massive leverage.",
    excerpt_az: "Müsahibədə ilk rəqəmi kim deməlidir? Daniel Kanemanın Lövbər effekti, FTB danışıqçısı Kris Vossun sualları və şirkətlərdən yüksək təklif almağın dəqiq skriptləri.",
    coverImage: {
      _type: "image",
      url: "https://images.unsplash.com/photo-1528819622765-d6bcf132f793?w=1200&h=675&fit=crop&auto=format&q=80",
      alt: "Strategic salary negotiation represented by minimal chess pieces on dark background",
    },
    publishDate: "26 Avqust 2026",
    readTime: "3 min read",
    featured: true,
    authorName: "Ravan Mammadov",
    authorRole: "Senior Creative Designer & Visual Strategist",
    authorSlug: "ravan-mammadov",
    authorPhoto: "/imports/ravan_1-400.webp",
    tags: ["Career Strategy", "Salary Negotiation", "Behavioral Economics", "Daniel Kahneman", "HR Insights"],
    discussionPrompt: {
      question: "When an employer asks for your salary expectation, do you anchor first with a strategic range or wait for their budget?",
      question_az: "Bir şirkət sizdən maaş gözləntinizi soruşanda ilk rəqəmi siz deyərdiniz, yoxsa onların büdcəsini gözləyərdiniz?",
      context: "The first anchor establishes the gravity field for all subsequent concessions. Share your real interview experiences below.",
      context_az: "Maaş danışıqlarında ilk addım bütün danışıqların istiqamətini dəyişir. Təcrübənizi bölüşün.",
    },
    sources: [
      { title: "15 Rules for Negotiating a Job Offer", author: "Deepak Malhotra (Harvard Business Review)", year: 2014 },
      { title: "Thinking, Fast and Slow", author: "Daniel Kahneman", year: 2011 },
      { title: "Never Split the Difference", author: "Chris Voss", year: 2016 },
    ],
    socialDrafts: {
      linkedin: "In salary negotiations, does the party that names the first number lose or win? Behavioral economics proves that anchoring bias dictates up to 80% of final outcomes:",
      x: "Who should name the first number in job interviews? Harvard negotiation research and Kahneman's anchoring heuristic explained:",
      instagram: "Naming the wrong number in an interview can cost you thousands of dollars annually. Here is the exact psychological framework to command top-tier offers:",
    },
    body: [
      createBlock("The single most consequential moment of any hiring process is not the review of your portfolio or technical assessment—it is the exact second the hiring manager asks: 'What are your compensation expectations?'", "normal"),
      createBlock("Two professionals with identical resumes, skill sets, and domain expertise can land offers separated by 40% to 100% simply because of how they navigate behavioral economics during negotiation. Research from Harvard Business School professor Deepak Malhotra and Nobel laureate Daniel Kahneman reveals that negotiation is not a game of luck; it is a structured science of cognitive anchoring and psychological framing.", "normal"),
      createBlock("1. The Psychology of the Employer: Behind Closed Doors", "h3"),
      createBlock("According to global hiring analytics from LinkedIn, over 73% of mid-to-large companies operate with pre-approved compensation bands for every open role (for instance, $3,500 – $5,500 monthly).", "normal"),
      createBlock("• If you prematurely state: 'I am comfortable with $3,200', the recruiter internally celebrates saving operational budget, and your ceiling is permanently capped.", "normal"),
      createBlock("• If you establish high-conviction value and professionally anchor at '$5,200', the company will still hire you because it falls squarely within their approved authorization ceiling.", "normal"),
      createBlock("2. Anchoring Bias: Who Should Fire First?", "h3"),
      createBlock("Daniel Kahneman's cognitive research on the Anchoring Heuristic demonstrates that the first explicit number introduced into a negotiation becomes the subconscious gravitational center around which all subsequent counter-offers orbit.", "normal"),
      createBlock("Harvard's empirical recommendation: When you possess solid market benchmark data, you should set the anchor first. However, never anchor with a single rigid integer. Instead, deploy a 'Bolstering Range' (e.g., '$5,200 to $6,000'). In psychological experiments, employers almost universally compromise on the lower bound of a bolstering range, perceiving it as a collaborative concession while landing at your exact ideal target.", "normal"),
      createBlock("3. Calibrated Questions: The Chris Voss Hostage Method", "h3"),
      createBlock("Former FBI lead hostage negotiator Chris Voss introduced the concept of calibrated 'How' and 'What' questions to transfer cognitive pressure back across the table without provoking hostility.", "normal"),
      createBlock("Company: 'Our maximum fixed budget for this senior position is $3,500.'", "blockquote"),
      createBlock("Candidate: 'I completely respect your structural budget constraints. At the same time, given the substantial commercial targets and cross-functional leadership expected in this role, how can we structure this so that it works for both of us?'", "blockquote"),
      createBlock("Notice how this statement transforms the interaction from an adversarial confrontation into a shared problem-solving session.", "normal"),
      createBlock("4. Structuring Total Compensation Beyond Base Salary", "h3"),
      createBlock("When a company encounters an inflexible base salary cap, sophisticated negotiators shift focus to total compensation packaging:", "normal"),
      createBlock("1. Performance Bonuses & Milestone Bounties: Tying additional earnings to quantifiable commercial KPIs (e.g. conversion uplifts, pipeline velocity).", "normal"),
      createBlock("2. Remote & Flexible Work Allocations: Saving 40 hours monthly in commute time and commuting overhead.", "normal"),
      createBlock("3. Written Acceleration Protocols: Embedding an explicit contractual review: 'Following a successful 90-day evaluation against defined milestones, compensation automatically scales to $4,800.'", "normal"),
      createBlock("Conclusion: Confidence Rooted in Objective Value", "h3"),
      createBlock("Salary negotiation is not an act of greed; it is a professional demonstration of how you advocate for value under pressure. If you cannot negotiate effectively on your own behalf, how will an employer trust you to negotiate high-stakes outcomes for their business? Anchor early, frame collaborative questions, and never negotiate against yourself.", "normal")
    ],
    body_az: [
      createBlock("Müsahibələrin ən kritik məqamı təcrübəniz deyil, 'Maaş gözləntiniz nədir?' sualının verildiyi andır.", "normal"),
      createBlock("Eyni bacarığa və portfelə sahib iki mütəxəssisdən biri ayda 800 AZN alarkən, digərinin 1800 AZN qazanmasının tək səbəbi var: danışıq psixologiyası və davranış iqtisadiyyatını düzgün idarə etmək.", "normal"),
      createBlock("Harvard Universitetinin professoru Dikpak Malhotra və Nobel mükafatçısı Daniel Kanemanın araşdırmaları göstərir ki, maaş danışığı şans deyil, idarəolunan psixoloji mexanizmdir.", "normal"),
      createBlock("1. Masanın Digər Tərəfi: Şirkət Nə Düşünür?", "h3"),
      createBlock("LinkedIn-in qlobal hesabatına görə, işəgötürənlərin 73%-nin hər vakansiya üçün əvvəlcədən təsdiqlənmiş büdcə dəhlizi olur (məsələn: 1000 – 1600 AZN).", "normal"),
      createBlock("• Əgər 'Mənə 900 AZN bəs edər' desəniz, HR daxilən sevinir və büdcəyə qənaət edir, siz isə potensial qazancınızı itirirsiniz.", "normal"),
      createBlock("• Əgər dəyəri əsaslandırıb '1500 AZN' desəniz, şirkət yenə də sizi işə götürür, çünki bu məbləğ onların onsuz da təsdiqlənmiş dəhlizinin içindədir.", "normal"),
      createBlock("2. 'Lövbər Effekti': İlk Rəqəmi Kim Deməlidir?", "h3"),
      createBlock("Daniel Kanemanın kəşf etdiyi Lövbər Effektinə görə, masada səslənən ilk rəqəm bütün sonrakı müzakirələrin cazibə mərkəzinə çevrilir.", "normal"),
      createBlock("Harvard tövsiyəsi: Bazar dəyərini bilirsinizsə, lövbəri birinci siz atın; amma tək rəqəmlə yox, 'Strateji Aralıq' (məsələn: 1400 - 1700 AZN) ilə. Bu zaman işəgötürən aralığın minimumunu təbii kompromis kimi qəbul edir və hədəflədiyiniz məbləğə razılaşır.", "normal"),
      createBlock("3. Kris Vossdan 'Kalibrlənmiş Suallar'", "h3"),
      createBlock("Keçmiş FTB girov danışıqçısı Kris Vossun metodu: 'Necə?' sualları ilə təzyiqi qarşı tərəfə ötürmək.", "normal"),
      createBlock("Şirkət: 'Biz sizə maksimum 800 AZN təklif edə bilərik.'", "blockquote"),
      createBlock("Siz: 'Büdcə çərçivənizi tam başa düşürəm. Eyni zamanda, bu vəzifədə məndən gözlənilən böyük hədəfləri nəzərə alsaq, bu büdcə ilə qarşılıqlı olaraq necə irəliləyə bilərik?'", "blockquote"),
      createBlock("4. 'Total Compensation' Paketi", "h3"),
      createBlock("1. Hibrid/Uzaqdan iş imkanı (ayda 150 AZN yol xərcinə və 35 saat vaxta qənaət).", "normal"),
      createBlock("2. İllik fərdi təhsil və konfrans büdcəsi.", "normal"),
      createBlock("3. Rəsmi artım protokolu: '3 aylıq sınaqdan sonra maaş rəsmi 1400 AZN-ə qaldırılır.'", "normal"),
      createBlock("Nəticə: Dəyərinizə Güvənin", "h3"),
      createBlock("Maaş danışığı acgözlük deyil, öz peşəkar dəyərinizi müdafiə etmək bacarığıdır. Öz maraqlarını peşəkarlıqla qoruya bilməyən mütəxəssisə şirkət böyük layihələri etibar etməz.", "normal")
    ],
    seo: {
      metaTitle: "Maaş Danışığında İlk Rəqəmi Kim Deməlidir? | Rvan.me",
      metaDescription: "Müsahibədə ilk rəqəmi kim deməlidir? Daniel Kanemanın Lövbər effekti, FTB danışıqçısı Kris Vossun sualları və şirkətlərdən yüksək təklif almağın dəqiq skriptləri.",
      canonicalUrl: "https://www.rvan.me/blog/salary-negotiation-psychology-harvard-method"
    }
  },

  // ── 02. Beautiful Design Loses Money ──
  {
    _id: "blog-masterclass-gozel-dizayn-niye-pul-itirir-nielsen-norman-group",
    title: "Why Does Beautiful Design Fail to Convert?",
    title_az: "Gözəl Dizayn Niyə Satmır?",
    deck: "Why Dribbble-style visual perfection kills real checkout conversion rates and how cognitive load dictates user purchasing behavior.",
    deck_az: "Dribbble üslublu animasiyaların real e-ticarətdə səbət tərkini 68%-ə qaldırma səbəbləri və konversiya memarlığı.",
    slug: { _type: "slug", current: "why-beautiful-design-loses-money-nng-research" },
    slug_az: { _type: "slug", current: "gozel-dizayn-niye-pul-itirir-nielsen-norman-group" },
    originalSlug: "gozel-dizayn-niye-pul-itirir-nielsen-norman-group",
    category: "UI/UX & Product Design",
    category_az: "UI/UX & Rəqəmsal Məhsul",
    format: "Analiz",
    cluster: "design",
    excerpt: "Why highly upvoted Dribbble concepts fail in production e-commerce. Inside the Baymard Institute's 68.8% checkout abandonment data and 4 essential metrics every product designer must master.",
    excerpt_az: "Dribbble-dakı min layklı dizaynlar real biznesdə niyə satışları öldürür? Baymard İnstitutunun 68.8% səbət tərki araşdırması və dizaynerin dəyərini artıran 4 biznes metrikası.",
    coverImage: {
      _type: "image",
      url: "https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=1200&h=675&fit=crop&auto=format&q=80",
      alt: "Minimal visual representation of UX friction and conversion architecture",
    },
    publishDate: "24 Avqust 2026",
    readTime: "2 min read",
    featured: true,
    authorName: "Ravan Mammadov",
    authorRole: "Senior Creative Designer & Visual Strategist",
    authorSlug: "ravan-mammadov",
    authorPhoto: "/imports/ravan_1-400.webp",
    tags: ["UI/UX Design", "Conversion Rate", "Baymard Institute", "NNGroup", "E-Commerce Architecture"],
    discussionPrompt: {
      question: "When visual aesthetics and friction-free usability clash in product design, how do you resolve the tension?",
      question_az: "Dribbble konsepti ilə real biznes ehtiyacı toqquşanda hansını seçirsiniz: vizual gözəllik, yoxsa konversiya?",
      context: "Highly expressive interface animations frequently introduce cognitive friction that hurts checkout completion rates.",
      context_az: "Gözəl interfeyslər həmişə funksional olmur. Bəs siz balans nöqtəsini harada görürsünüz?",
    },
    sources: [
      { title: "48 Cart Abandonment Rate Statistics", author: "Baymard Institute", year: 2023 },
      { title: "Eyetracking Web Usability", author: "Jakob Nielsen & Kara Pernice (NN/g)", year: 2010 },
      { title: "The Design of Everyday Things", author: "Don Norman", year: 2013 },
    ],
    body: [
      createBlock("There is a pervasive, seductive myth in the digital design ecosystem: 'If an interface looks gorgeous, elegant, and animation-rich, it will automatically achieve commercial success.'", "normal"),
      createBlock("Yet when visually breathtaking Dribbble prototypes are deployed to real production e-commerce environments, a brutal reality often strikes: conversion rates crater, bounce rates spike, and users abandon checkouts in frustration. Designing for visual applause is fundamentally different from designing for human decision-making.", "normal"),
      createBlock("1. The Baymard Institute: The 68.8% Abandonment Reality", "h3"),
      createBlock("Across large-scale usability benchmarks analyzing over 48,000 online shoppers, the Baymard Institute discovered that the average global shopping cart abandonment rate is a staggering 68.8%. When dissecting why users abandon:", "normal"),
      createBlock("• 24% – Mandatory forced account creation before purchase.", "normal"),
      createBlock("• 18% – Overly complicated, multi-step checkout architecture.", "normal"),
      createBlock("• 17% – Hidden or ambiguous fee structures revealed at the final step.", "normal"),
      createBlock("Every additional form field, subtle animation delay, or unconventional UI pattern introduces micro-friction that compounds into catastrophic revenue leaks.", "normal"),
      createBlock("2. Cognitive Load and Hick's Law", "h3"),
      createBlock("Hick's Law establishes that the time required to make a decision increases logarithmically with the number and complexity of choices. When an interface bombards a customer with decorative carousels, floating widgets, and competing accent colors, the prefrontal cortex experiences decision paralysis.", "normal"),
      createBlock("High-performing design systems operate on cognitive subtraction: stripping away every single visual element that does not directly contribute to user orientation or task completion.", "normal"),
      createBlock("3. Case Study: How Radical Simplification Drove +42% Conversions", "h3"),
      createBlock("In a comprehensive redesign of a high-volume food logistics platform:", "normal"),
      createBlock("• Forced registration was replaced with frictionless single-tap SMS one-time passcode verification.", "normal"),
      createBlock("• The 4-step checkout was consolidated into a single progressive viewport with inline validation.", "normal"),
      createBlock("• Primary action triggers were repositioned into the ergonomic 'Thumb Zone' of modern mobile viewports.", "normal"),
      createBlock("Result: Completed order rates surged from 32.0% to 45.4%—representing a net 42% revenue increase with zero marketing budget expansion.", "normal"),
      createBlock("Designers Who Drive Revenue", "h3"),
      createBlock("The transition from junior pixel artist to senior product strategist occurs the moment you stop asking 'Does this look cool?' and start asking 'What cognitive friction does this introduce, and how does it impact customer retention?' Aesthetics attract; architecture converts.", "normal")
    ],
    body_az: [
      createBlock("Dizayn dünyasında çox təhlükəli bir mif var: 'Əgər dizayn estetik və rəngarəngdirsə, o mütləq uğurlu olacaq.'", "normal"),
      createBlock("Dribbble-da minlərlə layk toplayan animasiyalı dizaynları real biznesə tətbiq etdikdə acı reallıq üzə çıxır: Satışlar kəskin düşür, istifadəçilər çaşqınlıq içində saytı tərk edir.", "normal"),
      createBlock("1. Baymard İnstitutu: 68.8% Səbət Tərki", "h3"),
      createBlock("48.000-dən çox istifadəçini əhatə edən qlobal araşdırmaya görə, onlayn alış-verişdə səbəti tərk edənlərin ortalaması 68.8%-dir. Əsas səbəblər:", "normal"),
      createBlock("• 24% – Məcburi uzun qeydiyyat tələbi.", "normal"),
      createBlock("• 18% – Ödəniş prosesinin həddindən artıq mürəkkəb olması.", "normal"),
      createBlock("• 17% – Sonda gözlənilməz əlavə xərclərin çıxması.", "normal"),
      createBlock("2. NN/g: F-Şəkilli Baxış Modeli və Koqnitiv Yük", "h3"),
      createBlock("Nielsen Norman Group sübut etdi ki, istifadəçilər saytları kitab kimi oxumur, F-şəkilli trayektoriya ilə gözdən keçirir. Ən vacib düymə bu təbii axına uyğun deyilsə, istifadəçi saytdan çıxır.", "normal"),
      createBlock("3. Sadəlik Satışı Necə 42% Artırdı?", "h3"),
      createBlock("Real çatdırılma xidmətində edilən UX dəyişiklikləri:", "normal"),
      createBlock("• Qeydiyyat tam ləğv edildi (tək SMS kod).", "normal"),
      createBlock("• Checkout tək səhifəyə endirildi.", "normal"),
      createBlock("• Əsas düymə baş barmağın rahat çatdığı Thumb Zone sahəsinə qoyuldu.", "normal"),
      createBlock("Nəticə: Sifarişi tamamlayanların nisbəti 32%-dən 45.4%-ə yüksəldi (+42% xalis artım).", "normal"),
      createBlock("Nəticə: Biznesə Xidmət Edən Dizayn", "h3"),
      createBlock("Peşəkar dizaynerin dəyəri sadəcə gözəl qrafika çəkməklə deyil, istifadəçi sürtünməsini aradan qaldırıb biznesə real gəlir gətirməklə ölçülür.", "normal")
    ],
    seo: {
      metaTitle: "Gözəl Dizayn Niyə Satmır? | Rvan.me",
      metaDescription: "Dribbble-dakı min layklı dizaynlar real biznesdə niyə satışları öldürür? Baymard İnstitutunun 68.8% səbət tərki araşdırması və 4 əsas UX metrikası.",
      canonicalUrl: "https://www.rvan.me/blog/why-beautiful-design-loses-money-nng-research"
    }
  },

  // ── 03. Followers Don't Equal Sales ──
  {
    _id: "blog-masterclass-izleyici-coxlugu-satis-getirmir-cialdini-funnel",
    title: "Why Having 50K Followers Doesn't Generate Sales",
    title_az: "50K İzləyici Niyə Pul Qazandırmır?",
    deck: "Escaping vanity metrics with Robert Cialdini's persuasion funnel and high-intent audience conversion architecture.",
    deck_az: "Sosial mediada rəqəm aldanışı və soyuq izləyicini sadiq alıcıya çevirən 3 pilləli Cialdini satış qıfı.",
    slug: { _type: "slug", current: "why-large-followers-dont-equal-sales-cialdini-funnel" },
    slug_az: { _type: "slug", current: "izleyici-coxlugu-satis-getirmir-cialdini-funnel" },
    originalSlug: "izleyici-coxlugu-satis-getirmir-cialdini-funnel",
    category: "Marketing & Growth Strategy",
    category_az: "Marketinq & SMM",
    format: "Keys",
    cluster: "marketing",
    excerpt: "The dangerous trap of vanity metrics. How Robert Cialdini's 3 psychological persuasion levers convert cold social audiences into high-paying clients.",
    excerpt_az: "Sosial mediada 'Vanity Metrics' tələsi. Robert Çaldininin 3 psixoloji prinsipi və soyuq izləyicini sadiq alıcıya çevirən 3 pilləli satış qıfı strategiyası.",
    coverImage: {
      _type: "image",
      url: "https://images.unsplash.com/photo-1563986768609-322da13575f2?w=1200&h=675&fit=crop&auto=format&q=80",
      alt: "Abstract spheres representing audience density versus conversion depth",
    },
    publishDate: "22 Avqust 2026",
    readTime: "2 min read",
    featured: true,
    authorName: "Ravan Mammadov",
    authorRole: "Senior Creative Designer & Visual Strategist",
    authorSlug: "ravan-mammadov",
    authorPhoto: "/imports/ravan_1-400.webp",
    tags: ["Marketing Strategy", "Social Media", "Cialdini Psychology", "Sales Funnels", "Audience Monetization"],
    discussionPrompt: {
      question: "For a growing creative business, is it better to have 500 loyal buyers or 50,000 passive followers?",
      question_az: "Sizcə biznes üçün 100 sadiq alıcı daha vacibdir, yoxsa 10.000 passiv izləyici?",
      context: "Inflated follower counts create the illusion of brand authority while masking deep conversion inefficiencies.",
      context_az: "Sosial şəbəkələrdə şişirdilmiş izləyici sayları həqiqətən satışa təsir edir?",
    },
    sources: [
      { title: "Influence: The Psychology of Persuasion", author: "Robert B. Cialdini", year: 2006 },
      { title: "Contagious: Why Things Catch On", author: "Jonah Berger", year: 2013 },
    ],
    body: [
      createBlock("The most expensive illusion in modern digital marketing is equating social media follower counts with sustainable commercial revenue.", "normal"),
      createBlock("Brands and creator businesses pour thousands into viral giveaways and superficial growth tactics, celebrating a 50,000 follower milestone, only to discover that when they launch a premium product, virtually nobody purchases. Followers are a vanity metric; trust and perceived commercial utility are the only currency that clears an invoice.", "normal"),
      createBlock("1. Robert Cialdini's 3 Levers of Audience Persuasion", "h3"),
      createBlock("In his landmark research on cognitive compliance, Dr. Robert Cialdini outlined the psychological triggers that transform passive observers into committed buyers:", "normal"),
      createBlock("1. Social Proof: Unedited, authentic client reviews and verifiable case studies. Displaying real client transformation data increases conversion likelihood by over 270%.", "normal"),
      createBlock("2. Demonstrated Authority: Cease broadcasting generic promotional claims. Publish deep-dive technical analyses, architectural teardowns, and proprietary methodologies.", "normal"),
      createBlock("3. Reciprocity: Deliver overwhelming upfront value without asking for anything in return (comprehensive guides, customizable Figma assets, revenue audit templates).", "normal"),
      createBlock("2. The 3-Tier Conversion Funnel Architecture", "h3"),
      createBlock("High-converting creator enterprises structure their content pipeline across three deliberate stages:", "normal"),
      createBlock("• TOFU (Top of Funnel - 60%): High-reach, educational viral essays and counter-intuitive insights that attract qualified domain specialists.", "normal"),
      createBlock("• MOFU (Middle of Funnel - 30%): Trust-building teardowns, client case studies, and transparent problem-solving walkthroughs.", "normal"),
      createBlock("• BOFU (Bottom of Funnel - 10%): Direct, frictionless commercial offers with unambiguous calls-to-action.", "normal"),
      createBlock("Monetizing Genuine Attention", "h3"),
      createBlock("A tightly curated community of 1,000 engaged professionals who trust your domain expertise will consistently generate more recurring revenue than an unfocused crowd of 100,000 passive scrollers. Build depth, not shallow volume.", "normal")
    ],
    body_az: [
      createBlock("Sosial mediada ən çox pul itkisinə səbəb olan təməl yanılsama: 'İzləyici sayı çoxdursa, satış da çox olacaq.'", "normal"),
      createBlock("Hər gün minlərlə manat giveaway-lərə xərclənir. Nəticədə 50-100 minlik səhifələr yaranır, amma bir post paylaşanda heç kim rəy yazmır və satış olmur.", "normal"),
      createBlock("Əsl dəyər 'İzləyici sayı'nda deyil, 'Auditoriyanın Güvən İndeksi'ndədir.", "normal"),
      createBlock("1. Robert Çaldininin 3 Qızıl Qaydası", "h3"),
      createBlock("1. **Sosial Sübut:** Real müştəri rəyləri və səs yazıları. Araşdırmalara görə real rəylər satışı 270% artırır.", "normal"),
      createBlock("2. **Avtoritet:** Sadəcə məhsul satmayın, sahənizdə maarifləndirici ekspert təhlilləri verin.", "normal"),
      createBlock("3. **Qarşılıqlılıq:** Əvvəlcə təmənnasız dəyər verin (Pulsuz bələdçi, şablon, analiz).", "normal"),
      createBlock("2. Satış Qıfının 3 Pilləsi:", "h3"),
      createBlock("• **TOFU (60%):** Hər kəs üçün maraqlı, viral maarifləndirici məzmun.", "normal"),
      createBlock("• **MOFU (30%):** Etibar yaradan Case Study və real nəticələr.", "normal"),
      createBlock("• **BOFU (10%):** Birbaşa konkret təklif və aydın çağırış (CTA).", "normal"),
      createBlock("Nəticə", "h3"),
      createBlock("Sizə minlərlə passiv izləyici yox, sizin ekspertizaya inanan və xidmətiniz üçün ödəməyə hazır olan keyfiyyətli auditoriya lazımdır.", "normal")
    ],
    seo: {
      metaTitle: "50K İzləyici Niyə Pul Qazandırmır? | Rvan.me",
      metaDescription: "Sosial mediada 'Vanity Metrics' tələsi. Robert Çaldininin 3 psixoloji prinsipi və soyuq izləyicini sadiq alıcıya çevirən 3 pilləli satış qıfı strategiyası.",
      canonicalUrl: "https://www.rvan.me/blog/why-large-followers-dont-equal-sales-cialdini-funnel"
    }
  },

  // ── 04. Global Freelancing ──
  {
    _id: "blog-masterclass-qlobal-frilans-upwork-linkedin-saati-40-dollar",
    title: "How to Charge $40+/Hour in Global Freelancing",
    title_az: "Qlobal Frilansda Saatı $40+ Necə Qazanılır?",
    deck: "The Futur value pricing framework, high-converting Upwork proposal architecture, and inbound LinkedIn client acquisition.",
    deck_az: "Yerli büdcə limitlərindən çıxış, The Futur metodologiyası, Upwork təklif şablonu və beynəlxalq müqavilələr.",
    slug: { _type: "slug", current: "global-freelancing-upwork-linkedin-40-dollar-hour" },
    slug_az: { _type: "slug", current: "qlobal-frilans-upwork-linkedin-saati-40-dollar" },
    originalSlug: "qlobal-frilans-upwork-linkedin-saati-40-dollar",
    category: "Freelance & Global Markets",
    category_az: "Frilans & Qlobal Bazar",
    format: "Bələdçi",
    cluster: "career",
    excerpt: "Breaking free from local marketplace budget constraints. How The Futur proposal methodology, asynchronous Loom video teardowns, and LinkedIn inbound funnels secure $40-$80 hourly contracts.",
    excerpt_az: "Yerli bazarın büdcə limitlərindən çıxış yolu. The Futur metodologiyası, qlobal müştəriyə təsir edən Proposal şablonu və LinkedIn Inbound satış sistemi.",
    coverImage: {
      _type: "image",
      url: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&h=675&fit=crop&auto=format&q=80",
      alt: "Abstract digital network globe representing international freelance client acquisition",
    },
    publishDate: "20 Avqust 2026",
    readTime: "3 min read",
    featured: false,
    authorName: "Ravan Mammadov",
    authorRole: "Senior Creative Designer & Visual Strategist",
    authorSlug: "ravan-mammadov",
    authorPhoto: "/imports/ravan_1-400.webp",
    tags: ["Freelancing", "Upwork Strategy", "LinkedIn Growth", "Remote Work", "Value Pricing"],
    discussionPrompt: {
      question: "When bidding for international client contracts, what is your primary competitive edge: speed, price, or specialized domain expertise?",
      question_az: "Qlobal müştəriyə təklif göndərəndə ən çox hansı çətinliklə qarşılaşırsınız: dil baryeri, yoxsa qiymət təyini?",
      context: "Competing on price is a race to the bottom. Value pricing reframes you as an indispensable strategic partner.",
      context_az: "Xarici bazarlarla işləyən mütəxəssislərin təcrübəsi digərləri üçün ən böyük bələdçidir.",
    },
    sources: [
      { title: "Pricing Design & The Psychology of Value", author: "Chris Do (The Futur)", year: 2020 },
      { title: "Freelance Forward Global Report", author: "Upwork Research Institute", year: 2023 },
    ],
    body: [
      createBlock("Competing in localized marketplaces with micro-budgets and micromanaging clients leads directly to chronic creative burnout.", "normal"),
      createBlock("The exact same technical skill, aesthetic taste, and hours of effort that earn $200 locally can command $2,000 to $6,000 when repositioned for venture-funded global startups in North America, Western Europe, and the Middle East. The difference is not talent; it is positioning, client qualification, and value pricing psychology.", "normal"),
      createBlock("1. The Cheap Price Paradox", "h3"),
      createBlock("When a high-value US tech founder encounters an Upwork profile charging $10/hour, their immediate cognitive reflex is suspicion: 'This person will require constant hand-holding, lack commercial judgment, and produce brittle output.'", "normal"),
      createBlock("Enterprise and funded clients do not want cheap labor; they want risk mitigation, speed, and autonomous execution. Pricing at $45–$75/hour signals seniority, rigor, and professional accountability.", "normal"),
      createBlock("2. The 4-Sentence Upwork Proposal That Converts at 30%", "h3"),
      createBlock("Discard the standard 500-word generic introduction summarizing your biography. Replace it with this high-velocity 4-sentence framework:", "normal"),
      createBlock("1. Sentence 1: Directly address their specific commercial bottleneck without introducing yourself ('Noticed your SaaS landing page has a 70% bounce rate on mobile due to viewport layout shifts.').", "normal"),
      createBlock("2. Sentence 2: Provide an asynchronous 90-second Loom video audit with direct fixes.", "normal"),
      createBlock("3. Sentence 3: Cite a verifiable similar case study with quantifiable outcome metrics ('Recently helped an AI analytics tool elevate trial signups by 38% using this framework.').", "normal"),
      createBlock("4. Sentence 4: Low-friction closing invitation ('Open to a brief 10-minute diagnostic exchange this Thursday?').", "normal"),
      createBlock("3. LinkedIn Inbound: Becoming the Sought-After Specialist", "h3"),
      createBlock("To transition from outbound hunting to inbound attraction:", "normal"),
      createBlock("• Optimize your headline around specific business outcomes rather than tool titles (e.g. 'Helping B2B FinTech startups scale conversion rates through high-fidelity visual design systems').", "normal"),
      createBlock("• Post 2 weekly visual case studies breaking down how you solved complex product challenges.", "normal"),
      createBlock("Global Freedom", "h3"),
      createBlock("Operating globally liberates you from geographic income caps. When you master English business communication, position yourself around commercial impact, and price based on client value rather than labor hours, you unlock true location independence and financial leverage.", "normal")
    ],
    body_az: [
      createBlock("Yerli bazarda kiçik büdcəli müştərilərlə işləmək insanı tez tükəndirir. Eyni vaxtı və enerjini qlobal startaplara sərf etməklə saatı 40-70$ və ya layihə başına 2000-5000$ qazanmaq tamamilə realdır.", "normal"),
      createBlock("1. Ucuz Qiymətlə Rəqabət Tələsi", "h3"),
      createBlock("Qlobal müştəri saatı 8$ olan profili görəndə keyfiyyətsiz işdən şübhələnir. Onlar üçün əsas məsələ vaxta qənaət və problemin birdəfəlik peşəkar həllidir. Qiyməti saatı $40-$60 aralığında təyin etmək sizin təcrübəli və peşəkar olduğunuza işarədir.", "normal"),
      createBlock("2. Upwork-də 4 Pilləli Proposal Modeli:", "h3"),
      createBlock("1. **1-ci Cümlə:** Birbaşa müştərinin problemini vurğulamaq (adınızı və keçmişinizi tərifləmədən).", "normal"),
      createBlock("2. **2-ci Cümlə:** Qısa 90 saniyəlik fərdi Loom video izahı və audit linki.", "normal"),
      createBlock("3. **3-cü Cümlə:** Əvvəlki oxşar layihədə əldə edilən konkret rəqəmsal nəticə (+35% konversiya artımı).", "normal"),
      createBlock("4. **4-cü Cümlə:** Sadə və rahat 10 dəqiqəlik tanışlıq zəngi təklifi.", "normal"),
      createBlock("3. LinkedIn-də Inbound Müştəri Sistemi", "h3"),
      createBlock("Hər həftə 2 dəfə dizayn etdiyiniz real layihələrin 'Əvvəl / Sonra' analitik təhlilini paylaşın. Müştərilər sizin necə düşündüyünüzü görəndə özləri sizə layihə təklif edəcəklər.", "normal"),
      createBlock("Nəticə", "h3"),
      createBlock("Qlobal bazar coğrafi məhdudiyyətləri aradan qaldırır. İngilis dilində işgüzar ünsiyyəti mənimsəmək və dəyərə əsaslanan qiymət siyasəti yürütmək sizə tam maliyyə azadlığı verəcək.", "normal")
    ],
    seo: {
      metaTitle: "Qlobal Frilansda Saatı $40+ Necə Qazanılır? | Rvan.me",
      metaDescription: "Yerli bazarın büdcə limitlərindən çıxış yolu. The Futur metodologiyası, qlobal müştəriyə təsir edən Proposal şablonu və LinkedIn Inbound satış sistemi.",
      canonicalUrl: "https://www.rvan.me/blog/global-freelancing-upwork-linkedin-40-dollar-hour"
    }
  },

  // ── 05. Resumes Rejected in 6 Seconds ──
  {
    _id: "blog-masterclass-cv-niye-6-saniyede-red-edilir-ats-sistemleri",
    title: "Why 75% of Resumes Get Rejected in 6 Seconds by ATS",
    title_az: "CV-ni 6 Saniyədə Kim Ələyir?",
    deck: "Decoding Applicant Tracking Systems, avoiding visual Canva traps, and deploying Google's XYZ impact framework.",
    deck_az: "CV-lərin 75%-nin insan gözü görmədən rədd edilmə səbəbi, ATS alqoritmləri və Google XYZ formulu.",
    slug: { _type: "slug", current: "why-resumes-get-rejected-in-6-seconds-ats-secrets" },
    slug_az: { _type: "slug", current: "cv-niye-6-saniyede-red-edilir-ats-sistemleri" },
    originalSlug: "cv-niye-6-saniyede-red-edilir-ats-sistemleri",
    category: "Career & Hiring",
    category_az: "Karyera & HR",
    format: "Tədqiqat",
    cluster: "career",
    excerpt: "Why 75% of digital resumes are automatically filtered before a human recruiter ever sees them. The truth about Canva graphic templates, The Ladders eye-tracking research, and Google's XYZ accomplishment formula.",
    excerpt_az: "CV-lərin 75%-i niyə insan gözü görmədən rədd edilir? Canva tələsi, The Ladders göz izləmə araşdırması və Google-un məşhur XYZ formulu.",
    coverImage: {
      _type: "image",
      url: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=1200&h=675&fit=crop&auto=format&q=80",
      alt: "Minimal document layout symbolizing applicant tracking systems and resume screening",
    },
    publishDate: "03 Avqust 2026",
    readTime: "2 min read",
    featured: false,
    authorName: "Ravan Mammadov",
    authorRole: "Senior Creative Designer & Visual Strategist",
    authorSlug: "ravan-mammadov",
    authorPhoto: "/imports/ravan_1-400.webp",
    tags: ["Resume Architecture", "ATS Systems", "Hiring Analytics", "Google XYZ Formula", "Career Development"],
    discussionPrompt: {
      question: "Do you design your resume as a graphical presentation or as clean, single-column, ATS-parseable text?",
      question_az: "CV hazırlayarkən Canva şablonu işlətmisiniz və nəticəsi nə olub?",
      context: "Complex multi-column layouts and graphical skill bars frequently cause ATS parsing failures.",
      context_az: "Qrafik barlar və 2 sütunlu dizaynlar ATS robotlarını çaşdırır. Sizin təcrübəniz necədir?",
    },
    sources: [
      { title: "Hidden Workers: Untapped Talent", author: "Harvard Business School", year: 2021 },
      { title: "Eye-Tracking Study on Resume Readability", author: "The Ladders", year: 2018 },
    ],
    body: [
      createBlock("A comprehensive study conducted by Harvard Business School revealed that over 75% of job applications submitted to modern enterprises are automatically screened out by Applicant Tracking Systems (ATS) without ever being viewed by a human recruiter.", "normal"),
      createBlock("Candidates spend weeks polishing intricate graphical templates on Canva, incorporating dual-column tables, skill progress bars, and custom vector icons—completely unaware that these exact visual elements scramble ATS text parsers, categorizing the candidate as unqualified.", "normal"),
      createBlock("1. The 6-Second Recruiter Eye-Tracking Reality", "h3"),
      createBlock("Landmark eye-tracking research by The Ladders demonstrated that when a resume successfully passes the ATS filter, human recruiters spend an average of just 7.4 seconds on their initial screening decision. Their gaze follows a strict hierarchy:", "normal"),
      createBlock("• Candidate Name & Current Role Title", "normal"),
      createBlock("• Current Company & Start/End Dates", "normal"),
      createBlock("• Previous Company & Position History", "normal"),
      createBlock("• Education & Core Verified Skill Keywords", "normal"),
      createBlock("If this critical information cannot be extracted within 7 seconds, the application is discarded.", "normal"),
      createBlock("2. The Fatal 'Canva Resume' Pitfalls", "h3"),
      createBlock("1. Multi-Column Tables: ATS parsers read left-to-right across columns, mixing two distinct job experiences into nonsensical sentences.", "normal"),
      createBlock("2. Subjective Skill Meters: Stating 'Figma: 90%' or 'Photoshop: 4/5 stars' provides zero objective context and cannot be indexed by semantic keyword scanners.", "normal"),
      createBlock("3. Text Inside Graphics: Saving project descriptions as flattened raster layers makes content completely invisible to automated parsers.", "normal"),
      createBlock("3. Google's XYZ Accomplishment Formula", "h3"),
      createBlock("To stand out in both automated and human reviews, Google's People Operations team recommends structuring every single bullet point using this proven syntax:", "normal"),
      createBlock("Accomplished [X], as measured by [Y], by doing [Z].", "blockquote"),
      createBlock("Weak: 'Designed social media graphics and refreshed the brand website.'", "normal"),
      createBlock("Google XYZ: 'Elevated mobile landing page conversion rates by 34% (X), generating $18,000 in incremental monthly MRR (Y), by re-architecting visual hierarchy and checkout UX (Z).'", "normal"),
      createBlock("The Ultimate Resume Standard", "h3"),
      createBlock("Keep your resume strictly single-column, cleanly formatted in standard typography (Geist, Inter, Helvetica), exported as a clean text-searchable PDF, and quantified with hard business metrics.", "normal")
    ],
    body_az: [
      createBlock("Harvard araşdırması göstərir ki, şirkətlərə daxil olan CV-lərin 75%-dən çoxu insan tərəfindən oxunmadan, birbaşa avtomatlaşdırılmış ATS proqramları tərəfindən rədd edilir.", "normal"),
      createBlock("1. Canva Dizaynları Niyə Keçmir?", "h3"),
      createBlock("2 sütunlu qrafik dizaynlar, mürəkkəb cədvəllər və qrafik bacarıq faizləri ATS robotlarının mətni düzgün oxumasına mane olur və namizəd avtomatik arxivə göndərilir.", "normal"),
      createBlock("2. The Ladders: 6 Saniyəlik Baxış Qaydası", "h3"),
      createBlock("Araşdırmalar göstərir ki, HR mütəxəssisi bir CV-yə ilkin baxış üçün cəmi 6-7 saniyə vaxt ayırır. Əgər vəzifəniz, iş təcrübəniz və nailiyyətləriniz ilk baxışda aydın görünmürsə, müraciət kənara qoyulur.", "normal"),
      createBlock("3. Google-un 'XYZ Formulu'", "h3"),
      createBlock("Mən [Z] tətbiq edərək [Y] nəticəsini əldə etdim və bu [X] metrikayla ölçüldü.", "blockquote"),
      createBlock("Zəif: 'Şirkətin sosial media postlarını hazırladım.'", "normal"),
      createBlock("Güclü: 'Yeni vizual dildən və tipoqrafik sistemdən istifadə edərək (Z), şirkətin sosial media kliklənmə faizini 42% artırdım (X) və aylıq 120 yeni müştəri cəlb etdim (Y).'", "normal"),
      createBlock("4. Düzgün CV Arxitekturası", "h3"),
      createBlock("• Tək sütunlu, təmiz və oxunaqlı şriftlərdən (Inter, Helvetica) istifadə edin.", "normal"),
      createBlock("• Hər cümləni konkret rəqəm və faizlərlə əsaslandırın.", "normal"),
      createBlock("• Faylı PDF formatında saxlayın və mətnin axtarıla bildiyinə əmin olun.", "normal")
    ],
    seo: {
      metaTitle: "CV-ni 6 Saniyədə Kim Ələyir? | Rvan.me",
      metaDescription: "CV-lərin 75%-i niyə insan görmədən rədd edilir? Canva tələsi, The Ladders araşdırması və Google-un məşhur XYZ formulu.",
      canonicalUrl: "https://www.rvan.me/blog/why-resumes-get-rejected-in-6-seconds-ats-secrets"
    }
  },

  // ── 06. Who Will AI Really Replace? ──
  {
    _id: "blog-masterclass-sunii-intellekt-kimleri-issiz-qoyacaq-mit-stanford",
    title: "Will AI Really Replace Designers? The MIT & Stanford Truth",
    title_az: "AI Dizaynerləri İşsiz Qoyacaq?",
    deck: "MIT & Stanford benchmark findings on automation vs hybrid domain leverage in visual and software architecture.",
    deck_az: "MIT və Stanford araşdırması: AI iş yerlərini yox edir, yoxsa mütəxəssisləri 2 qat gücləndirir?",
    slug: { _type: "slug", current: "who-will-ai-replace-mit-stanford-studies" },
    slug_az: { _type: "slug", current: "sunii-intellekt-kimleri-issiz-qoyacaq-mit-stanford" },
    originalSlug: "sunii-intellekt-kimleri-issiz-qoyacaq-mit-stanford",
    category: "AI & Future of Work",
    category_az: "Süni İntellekt & Gələcək",
    format: "Analiz",
    cluster: "ai",
    excerpt: "Does artificial intelligence destroy creative careers or redistribute market leverage? Inside MIT's 453-professional benchmark and the high-income hybrid skillsets of the next decade.",
    excerpt_az: "AI iş yerlərini yox edir, yoxsa yenidən bölüşdürür? MIT-nin 453 mütəxəssis üzərindəki eksperimenti və gələcəyin ən yüksək qazanclı hibrid bacarıqları.",
    coverImage: {
      _type: "image",
      url: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=1200&h=675&fit=crop&auto=format&q=80",
      alt: "Minimal digital neural landscape representing artificial intelligence leverage",
    },
    publishDate: "28 İyul 2026",
    readTime: "2 min read",
    featured: false,
    authorName: "Ravan Mammadov",
    authorRole: "Senior Creative Designer & Visual Strategist",
    authorSlug: "ravan-mammadov",
    authorPhoto: "/imports/ravan_1-400.webp",
    tags: ["Artificial Intelligence", "Future of Work", "MIT Research", "Stanford HAI", "Creative Technology"],
    discussionPrompt: {
      question: "Which creative tasks have you already automated with AI, and which tasks remain strictly human-driven?",
      question_az: "AI sizə gündə 3 saat vaxt qazandırsa, bunun müqabilində hansı dizayn işini ona tam həvalə edərdiniz?",
      context: "Generative AI is shifting the bottleneck from raw asset production to taste, curation, and domain architecture.",
      context_az: "AI alətləri gündəlik işlərimizi dəyişir. Siz hansı tapşırıqları avtomatlaşdırmısınız?",
    },
    sources: [
      { title: "Experimental Evidence on the Productivity Effects of Generative Artificial Intelligence", author: "Shakked Noy & Whitney Zhang (MIT / Science)", year: 2023 },
      { title: "Artificial Intelligence Index Report 2024", author: "Stanford HAI", year: 2024 },
    ],
    body: [
      createBlock("The mainstream discourse surrounding artificial intelligence oscillates between two extreme caricatures: apocalyptic fears of complete creative obsolescence versus dismissive claims that AI is merely a glorified autocomplete gimmick.", "normal"),
      createBlock("Rigorous empirical research conducted by economists at MIT and Stanford paints a much more nuanced, actionable reality: AI does not replace entire professions; it commoditizes low-level mechanical tasks while exponentially magnifying the leverage of high-taste domain experts.", "normal"),
      createBlock("1. The MIT 453-Professional Benchmark", "h3"),
      createBlock("In a landmark study published in Science, researchers Shakked Noy and Whitney Zhang evaluated 453 white-collar professionals across standardized writing, analysis, and communication tasks:", "normal"),
      createBlock("• Professionals equipped with generative AI completed complex assignments 37% faster.", "normal"),
      createBlock("• Independent blind evaluators rated the output quality 18% higher.", "normal"),
      createBlock("• Most crucially, the performance gap between junior and senior practitioners narrowed significantly, establishing AI as a massive capability equalizer.", "normal"),
      createBlock("2. The Collapse of the Commodity Pixel Pusher", "h3"),
      createBlock("What is being eliminated by Midjourney, Claude, and generative Figma plugins is the market for commodity production: basic background removals, stock photography adaptations, and repetitive layout variations.", "normal"),
      createBlock("However, the commercial demand for design judgment, brand visual identity systems, behavioural UX architecture, and cross-functional product direction has never been higher.", "normal"),
      createBlock("3. The 3 High-Leverage Hybrid Disciplines", "h3"),
      createBlock("To command top-tier compensation in the AI era, creative professionals must synthesize three intersecting capabilities:", "normal"),
      createBlock("1. Taste & Curation: The ability to instantly discern between mediocre AI slop and mathematically refined typographic hierarchy.", "normal"),
      createBlock("2. Rapid Prototyping (Design + Code): Using tools like Cursor, Claude, and Framer to build fully functional web applications in hours.", "normal"),
      createBlock("3. Commercial Problem Solving: Diagnosing business friction and deploying AI pipelines to solve revenue bottlenecks.", "normal"),
      createBlock("The Future of Human Creativity", "h3"),
      createBlock("AI will not replace designers. But a designer who harnesses AI to execute at 5x velocity while maintaining impeccable taste will inevitably replace ten designers who refuse to evolve.", "normal")
    ],
    body_az: [
      createBlock("Süni intellekt haqqında iki yanlış təsəvvür var: ya onun bütün peşələri tamamilə məhv edəcəyi qorxusu, ya da onun sadəcə oyuncaq olduğunu düşünmək.", "normal"),
      createBlock("MIT və Stanford universitetlərinin araşdırmaları göstərdi ki, süni intellekt peşələri yox etmir; mexaniki, təkrar olunan işləri avtomatlaşdırır və yüksək zövqlü ekspertlərin bazar dəyərini qat-qat artırır.", "normal"),
      createBlock("1. MIT-nin 453 Mütəxəssis Üzərindəki Tədqiqatı", "h3"),
      createBlock("• AI alətlərindən istifadə edən mütəxəssislər işlərini 37% daha sürətli tamamladılar.", "normal"),
      createBlock("• Nəticələrin keyfiyyəti müstəqil ekspertlər tərəfindən 18% daha yüksək qiymətləndirildi.", "normal"),
      createBlock("• Ən əsası: Təcrübəli və gənc mütəxəssislər arasındakı sürət fərqi azaldı, çünki AI bacarıqları bərabərləşdirir.", "normal"),
      createBlock("2. Hansı Bacarıqlar Dəyərini İtirir?", "h3"),
      createBlock("Sadəcə şablon kopyalayan, fon silən və mexaniki qrafika yığan işlər sürətlə avtomatlaşdırılır. Lakin brend arxitekturası, istifadəçi psixologiyası, zövq və strateji qərarlar qəbul edən mütəxəssislərə tələbat heç vaxt olmadığı qədər yüksəkdir.", "normal"),
      createBlock("3. Gələcəyin 3 Əsas Hibrid Bacarığı", "h3"),
      createBlock("1. **Zövq və Kurasiya:** AI-nin yaratdığı minlərlə variant arasından ən estetik və funksional olanı seçmək.", "normal"),
      createBlock("2. **Sürətli Prototipləşdirmə (Dizayn + Kod):** Framer, Claude və Cursor ilə dizaynı bir neçə saata canlı sayta çevirmək.", "normal"),
      createBlock("3. **Biznes Düşüncəsi:** Şirkətin satış və konversiya problemlərini dizaynla həll etmək.", "normal"),
      createBlock("Nəticə", "h3"),
      createBlock("Süni intellekt insanı əvəz etməyəcək. Amma süni intellektdən istifadə edərək işini 5 qat sürətləndirən bir dizayner, köhnə üsullarla işləyən 10 həmkarını qabaqlayacaq.", "normal")
    ],
    seo: {
      metaTitle: "AI Dizaynerləri İşsiz Qoyacaq? | Rvan.me",
      metaDescription: "AI iş yerlərini yox edir, yoxsa yenidən bölüşdürür? MIT-nin 453 mütəxəssis üzərindəki eksperimenti və gələcəyin ən yüksək qazanclı hibrid bacarıqları.",
      canonicalUrl: "https://www.rvan.me/blog/who-will-ai-replace-mit-stanford-studies"
    }
  },

  // ── 07. Self-Taught UI/UX Roadmap ──
  {
    _id: "blog-masterclass-sifirdan-ui-ux-dizayn-oyrenmek-6-ayliq-xerite",
    title: "Why a High-Converting Portfolio Beats Any University Degree",
    title_az: "Portfolio Niyə Diplomdan Güclüdür?",
    deck: "A 6-month self-directed product design curriculum based on first-principles learning and production case studies.",
    deck_az: "Bahalı kurslar olmadan, Josh Kaufman metodologiyası ilə 6 aya real UI/UX öyrənmək və iş tapmaq xəritəsi.",
    slug: { _type: "slug", current: "self-taught-ui-ux-designer-6-month-roadmap" },
    slug_az: { _type: "slug", current: "sifirdan-ui-ux-dizayn-oyrenmek-6-ayliq-xerite" },
    originalSlug: "sifirdan-ui-ux-dizayn-oyrenmek-6-ayliq-xerite",
    category: "Design Education & Career",
    category_az: "Təhsil & Dizayn",
    format: "Bələdçi",
    cluster: "design",
    excerpt: "How to become a hired product designer in 6 months using open-access documentation. The Josh Kaufman accelerated skill acquisition model, Figma auto-layout mastery, and 2 bulletproof case study frameworks.",
    excerpt_az: "Pulsuz resurslarla 6 aya necə peşəkar dizayner olmaq olar? Josh Kaufman-ın sürətli öyrənmə metodu, Figma ustalığı və 2 güclü Case Study formulu.",
    coverImage: {
      _type: "image",
      url: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=1200&h=675&fit=crop&auto=format&q=80",
      alt: "Minimal design workspace wireframe layout representing UI UX education",
    },
    publishDate: "22 İyul 2026",
    readTime: "13 min read",
    featured: false,
    authorName: "Ravan Mammadov",
    authorRole: "Senior Creative Designer & Visual Strategist",
    authorSlug: "ravan-mammadov",
    authorPhoto: "/imports/ravan_1-400.webp",
    tags: ["UI/UX Design", "Figma Systems", "Career Roadmap", "Product Design", "Portfolio Building"],
    discussionPrompt: {
      question: "When hiring a designer, do you value academic degrees or two deeply documented, commercial case studies?",
      question_az: "İşə qəbulda diplom vacibdir, yoxsa 2 dənə dərindən işlənmiş Case Study?",
      context: "Modern tech companies evaluate problem-solving frameworks and execution speed over traditional formal credentials.",
      context_az: "Dizayn sənayesində formal təhsil və portfel arasındakı fərq hər gün böyüyür.",
    },
    sources: [
      { title: "The First 20 Hours: How to Learn Anything Fast", author: "Josh Kaufman", year: 2013 },
      { title: "Laws of UX", author: "Jon Yablonski", year: 2020 },
    ],
    body: [
      createBlock("The era of requiring a formal four-year university degree or an overpriced $10,000 bootcamp certificate to land a high-paying product design role is officially over.", "normal"),
      createBlock("Silicon Valley giants, European scaleups, and agile remote agencies prioritize one fundamental metric: Can you diagnose complex product problems and engineer clean, scalable, accessible design systems that move commercial metrics? Here is the structured 6-month roadmap to self-taught design mastery.", "normal"),
      createBlock("Month 1–2: Foundational Visual Systems & Figma Mechanics", "h3"),
      createBlock("• Deconstruct Gestalt Psychology: Proximity, Similarity, Continuity, and Closure.", "normal"),
      createBlock("• Master Typographic Scale: Implementing modular type scales, APCA contrast ratios, and responsive optical sizing.", "normal"),
      createBlock("• Figma Advanced Architecture: Complete mastery of Auto Layout 5.0, Component Sets, Nested Properties, Variables, and Design Tokens.", "normal"),
      createBlock("Month 3–4: Reverse Engineering & Cognitive UX Laws", "h3"),
      createBlock("• Clone 10 Top-Tier Products: Recreate interfaces from Linear, Stripe, Airbnb, and Apple down to the exact pixel and padding token.", "normal"),
      createBlock("• Study Cognitive Laws: Jakob's Law, Fitts's Law, Miller's Law, and the Peak-End Rule.", "normal"),
      createBlock("Month 5–6: Engineering 2 Unbeatable Commercial Case Studies", "h3"),
      createBlock("Never fill your portfolio with 20 superficial mockups. Instead, build 2 comprehensive, narrative-driven case studies structured as follows:", "normal"),
      createBlock("1. The Commercial Context: The existing product metric that was underperforming (e.g. 45% onboarding drop-off).", "normal"),
      createBlock("2. User Research & Friction Mapping: Identifying the exact psychological barriers impeding users.", "normal"),
      createBlock("3. Iterative Systems: High-fidelity prototypes, interactive micro-states, and design token documentation.", "normal"),
      createBlock("4. Verifiable Impact: The measured outcome (+28% user retention).", "normal"),
      createBlock("Your Proof of Competence", "h3"),
      createBlock("A live, interactive web portfolio showcasing your design systems and clear business thinking will outperform any paper degree on Earth. Build consistently, document your rationale, and let your work speak for itself.", "normal")
    ],
    body_az: [
      createBlock("Dizayn sahəsində işə qəbul üçün 4 illik universitet diplomu və ya minlərlə manatlıq kurs sertifikatları tələb edən dövr artıq arxada qaldı.", "normal"),
      createBlock("Müasir texnologiya şirkətləri üçün tək vacib meyar var: Siz real istifadəçi problemlərini həll edə və biznesə gəlir gətirən interfeyslər qura bilirsinizmi? 6 aylıq addım-addım bələdçi:", "normal"),
      createBlock("1-2-ci Ay: Təməl Vizual Qaydalar və Figma Ustalığı", "h3"),
      createBlock("• Qeştalt Psixologiyası: Yaxınlıq, Oxşarlıq və Vizual İyerarxiya qanunları.", "normal"),
      createBlock("• Tipoqrafika və Rəng: APCA kontrast qaydaları və 60-30-10 rəng balansı.", "normal"),
      createBlock("• Figma Dərinliyi: Auto Layout 5.0, Komponent dəstləri, Variables və Dizayn Tokenləri.", "normal"),
      createBlock("3-4-cü Ay: Klonlama və Laws of UX Psixologiyası", "h3"),
      createBlock("• Stripe, Linear və Airbnb kimi qlobal məhsulların interfeyslərini piksel-piksel təkrarlayaraq arxitekturasını öyrənmək.", "normal"),
      createBlock("• Jakob qanunu, Fits qanunu və Hikin qərar vermə modeli.", "normal"),
      createBlock("5-6-cı Ay: 2 Güclü Case Study və Canlı Portfolio", "h3"),
      createBlock("Portfelinizə 20 dənə səthi şəkil qoymayın. Yalnız 2 dənə real problemi əvvəldən sona həll edən, araşdırmasını və nəticəsini göstərən dərin Case Study hazırlayın.", "normal"),
      createBlock("Nəticə", "h3"),
      createBlock("Sizin ən böyük zəmanətiniz diplomunuz deyil, canlı işləyən interaktiv portfolionuz və problemləri həll etmə bacarığınızdır.", "normal")
    ],
    seo: {
      metaTitle: "Portfolio Niyə Diplomdan Güclüdür? | Rvan.me",
      metaDescription: "Pulsuz resurslarla 6 aya necə peşəkar dizayner olmaq olar? Josh Kaufman-ın metodu, Figma ustalığı və 2 güclü Case Study formulu.",
      canonicalUrl: "https://www.rvan.me/blog/self-taught-ui-ux-designer-6-month-roadmap"
    }
  },

  // ── 08. No-Code Framer Monetization ──
  {
    _id: "blog-masterclass-kod-yazmadan-sayt-yigib-satmaq-framer-no-code",
    title: "How to Build & Sell $1,500 No-Code Websites with Framer",
    title_az: "Kodsuz Sayt Qurub $1500 Qazanmaq",
    deck: "The Figma-to-Framer production pipeline, interactive components, and selling high-converting landing pages to modern businesses.",
    deck_az: "Gartner-in 70%-lik proqnozu, Figma-dan Framer-ə 3 addımlıq istehsal zənciri və 48 saata işlək sayt satmaq modeli.",
    slug: { _type: "slug", current: "building-selling-no-code-websites-framer-figma" },
    slug_az: { _type: "slug", current: "kodsuz-sayt-qurub-1500-qazanmaq-framer-no-code" },
    originalSlug: "kod-yazmadan-sayt-yigib-satmaq-framer-no-code",
    category: "No-Code & Web Design",
    category_az: "No-Code & Veb",
    format: "Bələdçi",
    cluster: "strategy",
    excerpt: "Gartner projects over 70% of new digital applications will leverage no-code platforms. How solo designers build, animate, and deploy high-performance $1,500 websites in under 48 hours.",
    excerpt_az: "Gartner-in 70%-lik No-Code proqnozu. Figma-dan Framer-ə 3 addımlıq istehsal zənciri və bizneslərə Landing Page satmağın dəqiq skripti.",
    coverImage: {
      _type: "image",
      url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=1200&h=675&fit=crop&auto=format&q=80",
      alt: "Minimal code and modular software building blocks for no-code development",
    },
    publishDate: "16 İyul 2026",
    readTime: "2 min read",
    featured: false,
    authorName: "Ravan Mammadov",
    authorRole: "Senior Creative Designer & Visual Strategist",
    authorSlug: "ravan-mammadov",
    authorPhoto: "/imports/ravan_1-400.webp",
    tags: ["No-Code Development", "Framer", "Figma to Framer", "Web Design", "Agency Model"],
    discussionPrompt: {
      question: "Are modern no-code platforms like Framer and Webflow replacing traditional frontend handoffs for marketing sites?",
      question_az: "No-Code alətləri ənənəvi frontend developerlərin işini azaldacaq, yoxsa onların işini sürətləndirəcək?",
      context: "Framer allows solo creators to ship award-winning, responsive, CMS-backed websites in a fraction of traditional development cycles.",
      context_az: "Framer və Webflow ilə sayt qurmaq artıq günlərlə deyil, saatlarla ölçülür.",
    },
    sources: [
      { title: "Forecast Analysis: Low-Code / No-Code Development Technologies", author: "Gartner Research", year: 2023 },
    ],
    body: [
      createBlock("According to global industry research from Gartner, over 70% of new commercial web applications and digital interfaces are being built with low-code and no-code tooling.", "normal"),
      createBlock("Traditionally, launching a custom, responsive, animation-rich website required a fragmented team: a UI designer, a frontend engineer, and a DevOps specialist—taking 6 to 10 weeks and thousands in overhead. With Framer, a single multidisciplinary designer can design, animate, and deploy high-converting production websites in 48 hours, capturing $1,000 to $3,500 per project.", "normal"),
      createBlock("1. The 3-Stage Figma-to-Framer Workflow", "h3"),
      createBlock("1. Figma Architecture: Build your interface strictly with Auto Layout frames and structured text styles.", "normal"),
      createBlock("2. Direct Native Copy: Utilize the official 'HTML to Framer' or native Figma copy-paste pipeline to preserve full structural integrity.", "normal"),
      createBlock("3. Interactive Polish: Add spring scroll animations, dynamic hover interactions, CMS collections, and integrated analytics forms directly in Framer.", "normal"),
      createBlock("2. Why Modern Businesses Gladly Pay $1,500+", "h3"),
      createBlock("Clients do not care whether a website is written in raw React or assembled in Framer; they care about:", "normal"),
      createBlock("• Blazing Fast Page Load Speeds (Sub-1s LCP metrics).", "normal"),
      createBlock("• Built-In SEO & Social Meta Architecture.", "normal"),
      createBlock("• Intuitive CMS Editing: Allowing non-technical marketing teams to publish blog posts and change copy without hiring developers.", "normal"),
      createBlock("Full Creative Sovereignty", "h3"),
      createBlock("No-code technology bridges the historical divide between design vision and software execution. When you control the full pipeline from idea to live URL, your commercial value as a creative professional multiplies dramatically.", "normal")
    ],
    body_az: [
      createBlock("Gartner-in qlobal hesabatına görə, dünyada yeni biznes saytlarının və tətbiqlərinin 70%-dən çoxu No-Code və Low-Code platformaları ilə hazırlanacaq.", "normal"),
      createBlock("Əvvəllər keyfiyyətli, animasiyalı bir sayt hazırlamaq üçün dizayner, developer və server mühəndisindən ibarət komanda və həftələrlə vaxt lazım olurdu. İndi isə tək bir dizayner Framer vasitəsilə 48 saata işlək, sürətli və animasiyalı saytı hazırlayıb 500-1500 AZN-ə təhvil verə bilir.", "normal"),
      createBlock("1. 3 Addımlıq İstehsal Zənciri", "h3"),
      createBlock("1. **Figma Arxitekturası:** Bütün dizaynı Auto Layout və dəqiq komponentlərlə strukturlaşdırmaq.", "normal"),
      createBlock("2. **Framer-ə Köçürmə:** 'Figma to Framer' ilə dizaynı bir kliklə canlı mühitə atmaq.", "normal"),
      createBlock("3. **İnteraktivlik və CMS:** Scroll animasiyaları, əlaqə formaları və bloq/məhsul üçün daxili idarəetmə panelini qoşmaq.", "normal"),
      createBlock("2. Müştərilər Niyə Bu Saytlar Üçün $1500 Ödəyirlər?", "h3"),
      createBlock("• Sayt saniyədən az müddətdə ildırım kimi sürətlə açılır.", "normal"),
      createBlock("• SEO və Google axtarış sistemləri üçün tam optimallaşdırılmış olur.", "normal"),
      createBlock("• Müştəri özü developer çağırmadan mətni və şəkilləri 1 dəqiqəyə dəyişə bilir.", "normal"),
      createBlock("Nəticə", "h3"),
      createBlock("No-Code sizə sadəcə dizayn çəkmək yox, birbaşa işləyən hazır rəqəmsal məhsul satmaq imkanı verir və gəlirinizi bir neçə dəfə artırır.", "normal")
    ],
    seo: {
      metaTitle: "Kodsuz Sayt Qurub $1500 Qazanmaq | Rvan.me",
      metaDescription: "Gartner-in 70%-lik No-Code proqnozu. Figma-dan Framer-ə 3 addımlıq istehsal zənciri və bizneslərə Landing Page satmağın dəqiq skripti.",
      canonicalUrl: "https://www.rvan.me/blog/building-selling-no-code-websites-framer-figma"
    }
  },

  // ── 09. Value Audit Client Acquisition ──
  {
    _id: "blog-masterclass-0-tecrube-ile-ilk-1000-azn-deyer-auditi-metodu",
    title: "How to Land Your First $1,000 Client with Zero Experience",
    title_az: "İlk $1,000 Müştəri Necə Tapılır?",
    deck: "Applying Alex Hormozi's '$100M Leads' principles to asynchronous Loom revenue audits that make saying 'No' irrational.",
    deck_az: "Aleks Hormozinin '$100M Leads' prinsipləri və xidmət satmaq yerinə biznesin itirdiyi pulu göstərən 2 dəqiqəlik Loom auditi.",
    slug: { _type: "slug", current: "landing-first-client-zero-experience-value-audit" },
    slug_az: { _type: "slug", current: "0-tecrube-ile-ilk-1000-azn-deyer-auditi-metodu" },
    originalSlug: "0-tecrube-ile-ilk-1000-azn-deyer-auditi-metodu",
    category: "Sales & Freelancing",
    category_az: "Satış & Frilans",
    format: "Bələdçi",
    cluster: "strategy",
    excerpt: "Alex Hormozi's $100M Leads framework applied to creative consulting. How personalized asynchronous Loom audits demonstrate undeniable value and close four-figure contracts.",
    excerpt_az: "Aleks Hormozinin '$100M Leads' prinsipləri. Xidmət satmaq yerinə biznesin itirdiyi pulu göstərən 2 dəqiqəlik Loom audit strategiyası.",
    coverImage: {
      _type: "image",
      url: "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=1200&h=675&fit=crop&auto=format&q=80",
      alt: "Minimal ascending steps representing first revenue generation and growth",
    },
    publishDate: "10 İyul 2026",
    readTime: "3 min read",
    featured: false,
    authorName: "Ravan Mammadov",
    authorRole: "Senior Creative Designer & Visual Strategist",
    authorSlug: "ravan-mammadov",
    authorPhoto: "/imports/ravan_1-400.webp",
    tags: ["Client Acquisition", "Sales Strategy", "Alex Hormozi", "Freelancing", "Cold Outreach"],
    discussionPrompt: {
      question: "When reaching out to potential clients, do you send generic portfolio links or customized video diagnosis audits?",
      question_az: "Müştəriyə soyuq mesaj yazanda hansı üsul daha çox cavab gətirir: portfel linki, yoxsa fərdi video audit?",
      context: "Generic cold outreach emails have less than a 1% response rate. Video value audits consistently convert at 20-30%.",
      context_az: "Şablon mesajlar artıq oxunmur. Fərdiləşdirilmiş dəyər necə fərq yaradır?",
    },
    sources: [
      { title: "$100M Leads: How to Get Strangers to Want to Buy Your Stuff", author: "Alex Hormozi", year: 2023 },
    ],
    body: [
      createBlock("The fundamental mistake made by 95% of beginner freelancers and creative agencies is sending generic, spammy cold outreach messages: 'Hey, check out my portfolio! I do logos, UI design, and branding.'", "normal"),
      createBlock("Business owners do not wake up in the morning wanting to buy a logo or lines of code. Business owners wake up wanting to fix leaking revenue pipelines, reduce customer acquisition costs, and elevate their brand prestige. When you sell services, you compete with thousands on price; when you diagnose and fix commercial pain points, you operate as an indispensable advisor.", "normal"),
      createBlock("1. The 'Value Audit' Method: Alex Hormozi's Core Insight", "h3"),
      createBlock("In his book $100M Leads, entrepreneur Alex Hormozi emphasizes giving away your best diagnostic value upfront to establish overwhelming authority. Here is the exact 4-step execution system:", "normal"),
      createBlock("1. Identify 15 Qualified Target Businesses: Choose thriving local or regional companies with proven product-market fit but visually outdated or clunky checkout websites.", "normal"),
      createBlock("2. Uncover 2 Obvious Conversion Bottlenecks: For example, an unreadable mobile font size, broken mobile menu navigation, or an obscured CTA button.", "normal"),
      createBlock("3. Redesign the Fix in Figma (15 Minutes): Recreate their hero section with flawless typography, high-contrast CTA buttons, and clean visual breathing room.", "normal"),
      createBlock("4. Record a 90-Second Personalized Loom Video: Warmly walk through their current friction, show the redesigned prototype, and explain why it will lift conversions.", "normal"),
      createBlock("2. The Unassailable Closing Script", "h3"),
      createBlock("Hey [Founder Name], I am a massive fan of [Company Name]. I was checking your checkout flow on mobile and noticed two layout issues that might be costing you sales during peak hours. I took 15 minutes to redesign the mobile viewport to fix the contrast issues. Here is a 90-second Loom walkthrough with the free Figma asset. No pitch—hope it helps your team!", "blockquote"),
      createBlock("Out of 15 customized value audits, an average of 3 to 5 business owners will respond asking to hire you for a full website overhaul at $1,000 to $2,500.", "normal"),
      createBlock("Delivering Value Before Extraction", "h3"),
      createBlock("When you demonstrate undeniable proof of competence before asking for a single dollar, you eliminate client hesitation and establish trust from day one.", "normal")
    ],
    body_az: [
      createBlock("Yeni başlayan dizayner və frilanserlərin 95%-nin etdiyi ən böyük səhv şablon mesajlar göndərməkdir: 'Salam, mənim portfolioma baxın, dizayn və loqo xidməti göstərirəm.'", "normal"),
      createBlock("Biznes sahibləri heç vaxt sadəcə 'loqo' almaq istəmirlər; onlar satışlarını artırmaq, müştəri itkisini azaltmaq və brendlərinin nüfuzunu qaldırmaq istəyirlər.", "normal"),
      createBlock("1. 'Dəyər Auditi' Metodunun 4 Addımı:", "h3"),
      createBlock("1. **15 Potensial Müştəri Seçin:** Yaxşı gəliri olan, lakin saytı köhnəlmiş yerli və ya regional biznesləri siyahıya alın.", "normal"),
      createBlock("2. **2 Kritik Xətanı Tapın:** Məsələn, mobildə oxunmayan balaca şrift, itən sifariş düyməsi və ya zəif rəng kontrastı.", "normal"),
      createBlock("3. **Figma-da Düzəliş Edin (15 dəqiqə):** Həmin hissəni müasir, təmiz və rahat şəkildə yenidən yığın.", "normal"),
      createBlock("4. **90 Saniyəlik Loom Videosu Çəkin:** Sahibkara təmənnasız göndərin: 'Salam, saytınızda satışları azaldan 2 xətanı görüb sizə faydalı olması üçün qısa video və həllini hazırladım.'", "normal"),
      createBlock("2. Nəticə və Statistika", "h3"),
      createBlock("15 fərdiləşdirilmiş video auditdən ən az 3-4 biznes sahibi sizə təşəkkür edib tam saytın və ya brendin yenilənməsini sizə həvalə edəcək (500 - 2000 AZN dəyərində).", "normal")
    ],
    seo: {
      metaTitle: "İlk $1,000 Müştəri Necə Tapılır? | Rvan.me",
      metaDescription: "Aleks Hormozinin '$100M Leads' prinsipləri. Xidmət satmaq yerinə biznesin itirdiyi pulu göstərən 2 dəqiqəlik Loom audit strategiyası.",
      canonicalUrl: "https://www.rvan.me/blog/landing-first-client-zero-experience-value-audit"
    }
  },

  // ── 10. Digital Products & Passive Income ──
  {
    _id: "blog-masterclass-reqemsal-sablonlar-sataraq-passiv-gelir-gumroad",
    title: "Building $2,000/Month Passive Income Selling Digital Templates",
    title_az: "Dizayner Nə Vaxt 'Bahalı' Sayılır?",
    deck: "Naval Ravikant's permissionless leverage applied to Figma UI kits, Framer components, and recurring digital assets.",
    deck_az: "Naval Ravikantın 'İcazəsiz Leverec' fəlsəfəsi və Figma UI Kit, Framer şablonları ilə passiv gəlir qurmaq.",
    slug: { _type: "slug", current: "passive-income-digital-templates-figma-notion" },
    slug_az: { _type: "slug", current: "reqemsal-sablonlar-sataraq-passiv-gelir-gumroad" },
    originalSlug: "reqemsal-sablonlar-sataraq-passiv-gelir-gumroad",
    category: "Digital Products & Passive Income",
    category_az: "Passiv Gəlir & Məhsul",
    format: "Fikir",
    cluster: "strategy",
    excerpt: "Naval Ravikant's permissionless leverage applied to creative design. How building modular Figma UI kits, Framer landing templates, and Notion operating systems generates scalable recurring revenue.",
    excerpt_az: "Naval Ravikantın 'İcazəsiz Leverec' fəlsəfəsi. Figma UI Kit, Framer Template və Notion şablonları ilə aylıq $500-2000 passiv gəlir qurmaq.",
    coverImage: {
      _type: "image",
      url: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=1200&h=675&fit=crop&auto=format&q=80",
      alt: "Minimal digital template grid representing scalable passive income assets",
    },
    publishDate: "04 İyul 2026",
    readTime: "3 min read",
    featured: false,
    authorName: "Ravan Mammadov",
    authorRole: "Senior Creative Designer & Visual Strategist",
    authorSlug: "ravan-mammadov",
    authorPhoto: "/imports/ravan_1-400.webp",
    tags: ["Passive Income", "Digital Products", "Figma UI Kits", "Gumroad", "Naval Ravikant"],
    discussionPrompt: {
      question: "Is selling client hours sustainable long-term compared to building scalable digital product assets?",
      question_az: "Müştəri layihələrinə vaxt satmaq daha gəlirlidir, yoxsa öz rəqəmsal məhsulunu qurmaq?",
      context: "Client service has linear 1:1 income ceilings. Digital products have 95%+ gross margins with global 24/7 distribution.",
      context_az: "Vaxt məhduddur, lakin rəqəmsal məhsul 1 dəfə yaradılıb minlərlə dəfə satıla bilir.",
    },
    sources: [
      { title: "How to Get Rich Without Getting Lucky", author: "Naval Ravikant", year: 2019 },
      { title: "Creator Economics Report", author: "Gumroad", year: 2024 },
    ],
    body: [
      createBlock("Naval Ravikant famously noted: 'If you do not find a way to make money while you sleep, you will work until you die.'", "normal"),
      createBlock("Client service is inherently linear: you trade one hour of focused labor for one fixed hourly rate. If you get sick, take a vacation, or reach the 40-hour weekly ceiling, your income abruptly stops. Digital products represent the ultimate form of permissionless leverage: code and media that you build once, market continuously, and distribute to thousands of customers globally with zero marginal replication cost.", "normal"),
      createBlock("1. The 95% Margin Advantage", "h3"),
      createBlock("Unlike physical commerce with inventory storage, shipping logistics, and manufacturing depreciation, digital template assets operate with 95%+ gross profit margins. Once a comprehensive Figma UI Kit or Framer agency template is published to Gumroad or Lemon Squeezy, every additional sale is pure profit.", "normal"),
      createBlock("2. The Top 3 High-Demand Creative Product Verticals", "h3"),
      createBlock("1. Specialized Figma Design Systems & UI Kits ($39 – $99): Comprehensive component libraries tailored to specific niches (e.g. FinTech mobile dashboards, Healthcare portals, AI analytics).", "normal"),
      createBlock("2. Production-Ready Framer & Webflow Templates ($49 – $149): High-converting agency portfolio templates, SaaS launch landing pages, and creator directories.", "normal"),
      createBlock("3. Notion Operating Workspaces ($19 – $49): Complete freelance client portal managers, design sprint trackers, and agency finance databases.", "normal"),
      createBlock("3. The Evergreen Distribution Engine", "h3"),
      createBlock("• Share free 'Lite' versions on Figma Community to generate thousands of top-of-funnel downloads and brand exposure.", "normal"),
      createBlock("• Embed clear upgrade pathways to the paid 'Pro' edition with extended component variants, auto-layout tokens, and documentation.", "normal"),
      createBlock("• Publish weekly educational case study threads on LinkedIn and X demonstrating how the template solves specific production problems in minutes.", "normal"),
      createBlock("True Creative Freedom", "h3"),
      createBlock("Building digital products decouples your income from your physical time. When your creative assets generate $2,000+ monthly in recurring passive sales, you gain the ultimate luxury: the freedom to accept only the client projects you genuinely care about.", "normal")
    ],
    body_az: [
      createBlock("Naval Ravikantın məşhur bir sözü var: 'Əgər siz yatarkən pul qazanmağın yolunu tapmasanız, ömrünüzün sonuna qədər vaxtınızı satmaq məcburiyyətində qalacaqsınız.'", "normal"),
      createBlock("Müştəriyə xidmət göstərmək həmişə vaxtla məhdudlaşır: 1 saat iş = 1 saatlıq ödəniş. Əgər xəstələnsəniz və ya tətilə çıxsanız, gəliriniz dərhal dayanır. Rəqəmsal məhsullar isə 1 dəfə yaradılır və minlərlə müştəriyə fasiləsiz satılır.", "normal"),
      createBlock("1. 95% Xalis Marja Üstünlüyü", "h3"),
      createBlock("Fiziki mallardan fərqli olaraq rəqəmsal şablonların anbar, çatdırılma və istehsal xərci yoxdur. Figma və ya Framer şablonunu Gumroad və ya Lemon Squeezy platformasına yüklədikdən sonra hər satış demək olar ki, 100% xalis mənfəətdir.", "normal"),
      createBlock("2. Ən Çox Tələbat Olan 3 Məhsul:", "h3"),
      createBlock("1. **Figma UI Kit & Dizayn Sistemləri** ($30 - $80): Mobil tətbiqlər və SaaS idarəetmə panelləri üçün hazır komponentlər.", "normal"),
      createBlock("2. **Framer və Webflow Şablonları** ($49 - $99): Agentliklər və startaplar üçün hazır landing page şablonları.", "normal"),
      createBlock("3. **Notion İdarəetmə Sistemləri** ($15 - $40): Frilanserlər üçün layihə və maliyyə izləmə bazaları.", "normal"),
      createBlock("3. Satış Qıfının Qurulması", "h3"),
      createBlock("• Şablonun sadələşdirilmiş 'Lite' versiyasını Figma Community-də pulsuz paylaşaraq minlərlə yüklənmə əldə edin.", "normal"),
      createBlock("• Şablonun içində tam pullu versiyaya keçid linki qoyun.", "normal"),
      createBlock("• LinkedIn-də şablonla 5 dəqiqəyə sayt yığmağın videosunu paylaşın.", "normal"),
      createBlock("Nəticə", "h3"),
      createBlock("Aylıq 1000-2000$ passiv gəlir qurmaq sizə ən böyük azadlığı verir: yalnız sevdiyiniz və həqiqətən dəyərli müştəri layihələrini qəbul etmək imkanı.", "normal")
    ],
    seo: {
      metaTitle: "Dizayner Nə Vaxt 'Bahalı' Sayılır? | Rvan.me",
      metaDescription: "Naval Ravikantın 'İcazəsiz Leverec' fəlsəfəsi. Figma UI Kit, Framer Template və Notion şablonları ilə aylıq $500-2000 passiv gəlir qurmaq.",
      canonicalUrl: "https://www.rvan.me/blog/passive-income-digital-templates-figma-notion"
    }
  },
];
