import { BlogPost } from "../../types/blog";

function createBlock(text: string, style = "normal", key = Math.random().toString(36).substring(7)) {
  return {
    _key: key,
    _type: "block",
    style,
    markDefs: [],
    children: [{ _key: `${key}-c`, _type: "span", marks: [], text }],
  };
}

function createImageBlock(url: string, alt: string, caption?: string) {
  return {
    _key: Math.random().toString(36).substring(7),
    _type: "image",
    asset: { _type: "reference", _ref: "image-manual" },
    alt,
    caption,
    url,
  };
}

export const ARTICLES_31_TO_39: BlogPost[] = [
  // 31. WHY SETTINGS IS A MECHANICAL GEAR
  {
    _id: "blog-automating-creative-workflows-with-ai-agents",
    title: "Why Is the Settings Icon a Mechanical Gear?",
    title_az: "Tənzimləmələr İkonu Niyə Mexaniki Dişli Çarx Şəklindədir?",
    slug: { _type: "slug", current: "why-settings-icon-is-a-mechanical-gear" },
    slug_az: { _type: "slug", current: "tenzimlemeler-niye-disli-carxdir" },
    originalSlug: "automating-creative-workflows-with-ai-agents",
    category: "Design History",
    category_az: "Dizayn Tarixi",
    excerpt: "The Industrial Revolution metaphor: How interlocking cogs and clockwork machinery became the universal digital symbol for system configuration.",
    excerpt_az: "Sənaye İnqilabı metaforası: Bir-birinə keçən dişli çarxların və saat mexanizmlərinin sistem tənzimləmələrinin qlobal simvoluna çevrilməsi.",
    coverImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "image-35f291a056702bbc7354aee2e0378a7ab73a9781-1600x1067-jpg" },
      alt: "Industrial design photograph of mechanical clockwork gears representing digital settings configuration",
      url: "https://cdn.sanity.io/images/0lqwkcmg/production/35f291a056702bbc7354aee2e0378a7ab73a9781-1600x1067.jpg",
    },
    publishDate: "2026-05-04",
    readTime: "8 min read",
    featured: false,
    tags: ["Iconography", "Settings UI", "Design History", "Skeuomorphism", "Affordance"],
    body: [
      createBlock("Why Is the Settings Icon a Mechanical Gear?", "h2"),
      createBlock("When you want to calibrate your display, change your Wi-Fi password, or toggle notifications, you tap an icon featuring a toothed wheel—a mechanical gear cog. In software composed entirely of invisible semiconductor electrons, why do we use an 18th-century Industrial Revolution clockwork component to represent configuration?"),
      createBlock("1. The Mechanics Behind the Metaphor", "h3"),
      createBlock("Before digital electronics, adjusting a machine meant opening its outer casing and adjusting the physical transmission gears, springs, or levers that dictated its timing and speed. A gear was the visible engine of adjustment."),
      createBlock("When GUI pioneers needed an icon that communicated 'the internal mechanisms that control how this application runs', the interlocking cog wheel was the perfect mental shortcut."),
    ],
  },

  // 32. WHY DELETE IS A TRASH CAN
  {
    _id: "blog-generative-ui-and-automated-layout-engines",
    title: "Why Is the Delete Action a Trash Can?",
    title_az: "Silmə Əməliyyatı Niyə Məhz Zibil Qutusu İkonudur?",
    slug: { _type: "slug", current: "why-delete-action-is-a-trash-can" },
    slug_az: { _type: "slug", current: "silme-niye-zibil-qutusudur" },
    originalSlug: "generative-ui-and-automated-layout-engines",
    category: "Design History",
    category_az: "Dizayn Tarixi",
    excerpt: "Tim Mott and Larry Tesler's desktop metaphor at Xerox and Apple: How the trash can provided both an intuitive deletion affordance and a psychological safety net.",
    excerpt_az: "Tim Mott və Larry Tesler-in masaüstü metaforası: Zibil qutusunun silmə əməliyyatına həm aydınlıq, həm də psixoloji geri qaytarma güvəni verməsi.",
    coverImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "image-05b84901cc52ea9195189d594335788c9ed1a6ba-1600x1067-jpg" },
      alt: "Desktop metaphor still life illustrating the intuitive affordance and safety net of the trash can icon",
      url: "https://cdn.sanity.io/images/0lqwkcmg/production/05b84901cc52ea9195189d594335788c9ed1a6ba-1600x1067.jpg",
    },
    publishDate: "2026-05-06",
    readTime: "8 min read",
    featured: false,
    tags: ["Iconography", "Apple History", "Desktop Metaphor", "UX Safety", "Interaction Design"],
    body: [
      createBlock("Why Is the Delete Action a Trash Can?", "h2"),
      createBlock("In command-line computing (MS-DOS, Unix), deleting a file meant typing `rm document.txt`. If you hit Enter, the file was instantly, irreversibly erased from disk. There was no visual feedback and no second chance."),
      createBlock("In the early 1980s, Xerox PARC and Apple designed the Lisa and Macintosh desktop interfaces. They introduced the Trash Can (designed by Susan Kare). Why was this breakthrough so revolutionary?"),
      createBlock("1. The Psychological Safety Net", "h3"),
      createBlock("In an actual office, when you throw a draft into the wastebasket next to your desk, it is not incinerated immediately. You can reach down and pull it out if you change your mind, until the janitor empties the bin at night."),
      createBlock("By simulating this physical reality—allowing files to sit in the Trash until the user explicitly selects 'Empty Trash'—software engineers eliminated the paralyzing anxiety of accidental deletion, making computers approachable for billions of everyday humans."),
    ],
  },

  // 33. WHY LUXURY BRANDS USE SO MUCH EMPTY SPACE
  {
    _id: "blog-ai-micro-saas-blueprint",
    title: "Why Do Luxury Brands Use So Much Empty Space? The Architecture of Restraint",
    title_az: "Lüks Brendlər Niyə Bu Qədər Çox Boş Məkandan İstifadə Edirlər? Təmkin Arxitekturası",
    slug: { _type: "slug", current: "why-luxury-brands-use-so-much-empty-space" },
    slug_az: { _type: "slug", current: "luks-brendler-ve-bos-mekan-psixologiyasi" },
    originalSlug: "ai-micro-saas-blueprint",
    category: "Creative & Culture",
    category_az: "Kreativ və Mədəniyyət",
    excerpt: "The economics and perception of non-utilitarian space: How Veblen's Conspicuous Waste, focal isolation, and intentional whitespace distinguish true luxury design from empty, barren layouts.",
    excerpt_az: "Qeyri-utilitar məkanın iqtisadiyyatı və qavrayışı: Veblen-in Nümayişkaranə İsraf nəzəriyyəsi, fokus təcridi və düşünülmüş boş məkanın lüks dizaynı necə formalaşdırdığı.",
    coverImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "image-luxury-spatial-restraint" },
      alt: "Architectural editorial composition of a minimalist gallery space demonstrating vast spatial abundance and visual restraint",
      url: "/images/editorial/luxury-spatial-restraint.jpg",
    },
    publishDate: "2026-05-08",
    readTime: "11 min read",
    featured: true,
    tags: ["Luxury Branding", "Veblen Goods", "Spatial Design", "Negative Space", "Architecture", "Design Systems"],
    body: [
      createBlock("Why Do Luxury Brands Use So Much Empty Space? The Architecture of Restraint", "h2"),
      createBlock("Step inside a high-volume discount warehouse: aisles are densely packed, shelves climb to the ceiling, and yellow promotional placards scream from every beam. Every square foot of commercial real estate must generate maximum transaction volume per hour."),
      createBlock("Now step into an architectural flagship boutique on Avenue Montaigne: a 5,000-square-foot room of hand-troweled lime plaster features exactly three leather bags resting in silent isolation on carved basalt blocks. Why do high-end brands intentionally 'waste' valuable space?"),

      createBlock("1. The Economics of Non-Utilitarian Space (Veblen's Conspicuous Waste)", "h3"),
      createBlock("In his foundational 1899 sociological treatise *The Theory of the Leisure Class*, Thorstein Veblen introduced the concept of 'Conspicuous Waste': elite social status is demonstrated not by productive efficiency, but by the ability to consume expensive resources without economic anxiety."),
      createBlock("In commercial real estate, where prime retail space costs hundreds of dollars per square foot per month, leaving 85% of a room completely empty is a formidable financial power signal. It communicates that the brand is completely detached from the frantic necessity of immediate sales pressure."),

      createBlock("2. Translating Spatial Abundance to Digital Interfaces", "h3"),
      createBlock("A digital screen has no physical rent, yet the exact same cognitive signaling dictates user perception:"),
      createBlock("• Discount Marketplaces (Amazon, Shein, Temu): Maximize density above the fold with coupon banners, countdown tickers, related product carousels, and flash-sale badges. High density signals transactional urgency and budget abundance."),
      createBlock("• Luxury & High-End Digital Flagships (Apple, Hermès, Polestar, Teenage Engineering): Embrace vast negative space and disciplined focal isolation. A single product is framed in dramatic silence with ample margins, signaling: *'This object possesses sufficient intrinsic value that it does not require decorative noise to hold your attention.'*"),

      createBlock("3. Empty Space vs. Intentional Space: The Crucial Boundary", "h3"),
      createBlock("Simply inflating CSS margins does not automatically make a website look like luxury. Uncontrolled whitespace feels lazy, clumsy, and barren:"),
      createBlock("• Accidental / Cheap Emptiness: Large blank voids between disconnected elements, lack of modular grid pacing, default typography, and unresolved visual tension."),
      createBlock("• Disciplined Intentional Space: Spatial breathing room engineered around strict proportional grid ratios (e.g. 64px container padding vs 8px micro-label gaps), asymmetric anchor points, and mathematical typographic hierarchy."),

      createBlock("4. The Practical Spatial Hierarchy Framework", "h3"),
      createBlock("When designing high-end digital products or editorial platforms, apply these three spatial principles:"),
      createBlock("• The Single Dominant Focal Anchor: Allow one primary visual element (a hero asset or editorial title) to command the viewport before introducing secondary metadata."),
      createBlock("• Extreme Contrast in Micro vs. Macro Pacing: Keep internal component elements (badges, labels, metadata tokens) tightly grouped via Gestalt proximity (4px to 8px), while separating major conceptual sections with expansive breathing room (80px to 140px)."),
      createBlock("• Elimination of Redundant Borders: Replace heavy bounding boxes and divider lines with pure spatial separation. When negative space does the work of dividing content, the interface feels weightless and sophisticated."),
    ],
  },

  // 34. CHANGING A FONT CHANGES BRAND PERSONALITY
  {
    _id: "blog-building-custom-gpts-and-specialized-knowledge-bases",
    title: "Why Does Changing a Font Completely Change a Brand's Personality?",
    title_az: "Şrifti Dəyişmək Bir Brendin Xarakterini Niyə Kökündən Dəyişir?",
    slug: { _type: "slug", current: "why-changing-a-font-changes-brand-personality" },
    slug_az: { _type: "slug", current: "srift-deyisikliyi-ve-brend-xarakteri" },
    originalSlug: "building-custom-gpts-and-specialized-knowledge-bases",
    category: "Typography",
    category_az: "Tipoqrafika",
    excerpt: "The semiotics of type anatomy: How stroke weight, geometry, and terminal contrast transform an institutional corporation into an approachable startup—and why luxury fashion abandoned, then revived, serif heritage.",
    excerpt_az: "Şrift anatomiyasının semiotikası: Xətt qalınlığı, həndəsə və künc kontrastının brendi necə rəsmi korporasiyadan səmimi startapa çevirdiyi və lüks brendlərin şrift dəyişikliyi dərsləri.",
    coverImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "image-typographic-personality-transition" },
      alt: "Conceptual editorial composition showing abstract geometric and serif typographic shadows",
      url: "/images/editorial/typographic-personality-transition.jpg",
    },
    publishDate: "2026-05-10",
    readTime: "11 min read",
    featured: true,
    tags: ["Typography", "Brand Personality", "Semiotics", "Font Psychology", "Visual Identity", "Design Systems"],
    body: [
      createBlock("Why Does Changing a Font Completely Change a Brand's Personality?", "h2"),
      createBlock("Set the word 'TRUST' in three different typefaces: Baskerville, Futura Bold, and Comic Sans."),
      createBlock("The semantic content is mathematically identical—five ASCII characters spelling out the same human virtue. Yet your nervous system immediately registers three completely distinct institutions: a 250-year-old private wealth bank, an uncompromising Bauhaus architectural studio, and a neighborhood primary school bake sale."),
      createBlock("Before a single sentence is consciously read, letterform geometry delivers an instantaneous non-verbal appraisal of competence, status, and cultural intent."),

      createBlock("1. The Physical Semiotics of Letterforms", "h3"),
      createBlock("Letterforms are not neutral vessels for language; they are physical artifacts carrying centuries of cultural lineage and technological constraints:"),
      createBlock("• High-Contrast Serifs & Razor Hairlines (Didot, Bodoni): Born during the 18th-century copperplate engraving revolution, these letterforms required ultra-smooth coated rag paper and precision iron presses—luxuries historically reserved for the royal court and aristocracy. That association endures: extreme stroke modulation remains the universal visual dialect of haute couture and fine fragrance."),
      createBlock("• Monolinear Geometric Sans (Futura, Avant Garde): Stripping calligraphic stroke modulation entirely, geometric sans-serifs rely on pure Euclidean circles, triangles, and straight stems. They communicate industrial rationality, unyielding engineering confidence, and architectural permanence."),
      createBlock("• Humanist Rhythm & Open Apertures (Frutiger, Gill Sans, Open Sans): Humanist designs preserve the dynamic stroke variation of the human hand. Their wide, open apertures maximize optical clarity at small sizes, signaling democratic accessibility, public service, and civic warmth."),

      createBlock("2. The Sans-Serif Blanding Wave and the Heritage Rebound", "h3"),
      createBlock("Between 2017 and 2021, an unprecedented aesthetic convergence swept global branding. Historic luxury fashion houses—Burberry, Saint Laurent, Balenciaga, and Berluti—ruthlessly discarded centuries-old typographic quirks in favor of nearly indistinguishable all-caps geometric grotesques."),
      createBlock("The engineering rationale was pragmatic: low-resolution mobile screens, small app icons, and cross-border digital storefronts penalized delicate serif brackets. But the commercial consequence was severe: extreme homogenization destroyed distinct brand equity."),
      createBlock("By 2023, the pendulum swung back. When Burberry unveiled its refreshed identity under Daniel Lee, it restored sharp, elegant serif terminals and historic British quirkiness. Similarly, when Johnson & Johnson retired its 136-year-old signature cursive script in 2023 for an unembellished geometric sans, it deliberately signaled a structural transition from consumer baby care to high-tech biomedical enterprise."),

      createBlock("3. Crossmodal Sensation: The Weight and Sound of Type", "h3"),
      createBlock("Psycholinguistic research in crossmodal correspondence demonstrates that human visual processing cross-wires letter shapes with tactile and auditory expectations. In controlled perception studies, participants consistently associate rounded, low-contrast letterforms with sweetness, softness, and safety, whereas angular, sharp-cornered fonts evoke bitterness, physical hardness, and high financial cost."),
      createBlock("When a user lands on a SaaS pricing tier or checkout page, the geometry of the numerals dictates whether the price tag feels 'accessible and friendly' or 'severe and institutional'."),

      createBlock("4. The Practical Typographic Personality Audit", "h3"),
      createBlock("Before committing a typeface to a design system or brand identity, run it through this 3-step diagnostic stress test:"),
      createBlock("• The Silhouette Isolation Test: Set your logotype in solid black (#000000) on solid white (#FFFFFF) with zero color, gradients, or photography. Does the raw letterform geometry still communicate your core brand attributes?"),
      createBlock("• The Extreme Scale Polarity Test: Test the typeface at 12px on an entry-level mobile screen and at 120px on an outdoor billboard. Does low-size stroke thinning destroy legibility, or does high-size letter-spacing feel unrefined?"),
      createBlock("• The Value-Perception Alignment Test: Present the standalone typeface to 20 unbiased evaluators without revealing your product. If an enterprise cybersecurity tool is mistaken for a playful wellness app, your typographic geometry is in direct conflict with your positioning."),
    ],
  },

  // 35. WHY EMAIL IS AN ENVELOPE WITH A TRIANGLE FLAP
  {
    _id: "blog-llm-integration-in-saas-products",
    title: "Why Is Email Represented by a Paper Envelope with a Triangular Flap?",
    title_az: "E-poçt Niyə Üçbucaqlı Qapağı Olan Kağız Zərf İkonudur?",
    slug: { _type: "slug", current: "why-email-is-a-paper-envelope-icon" },
    slug_az: { _type: "slug", current: "e-poct-niye-kagiz-zerf-ikonudur" },
    originalSlug: "llm-integration-in-saas-products",
    category: "Design History",
    category_az: "Dizayn Tarixi",
    excerpt: "From Ray Tomlinson's 1971 ARPANET protocol to Gmail's iconic red-and-white envelope: How a Victorian postal wrapper became the immortal emblem of digital text messages.",
    excerpt_az: "1971-ci il ARPANET protokolundan Gmail-in ikonik qırmızı-ağ zərfinə qədər: 19-cu əsrin poçt kağızının rəqəmsal rabitənin əbədi simvoluna çevrilməsi.",
    coverImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "image-01dec9326d0ce07c87983c2f6da5f9dfdb1b3819-1600x2400-jpg" },
      alt: "Communication history still life showing the paper envelope as a metaphor for privacy and containment",
      url: "https://cdn.sanity.io/images/0lqwkcmg/production/01dec9326d0ce07c87983c2f6da5f9dfdb1b3819-1600x2400.jpg",
    },
    publishDate: "2026-05-12",
    readTime: "8 min read",
    featured: false,
    tags: ["Iconography", "Email History", "Gmail", "Design History", "Skeuomorphism"],
    body: [
      createBlock("Why Is Email Represented by a Paper Envelope with a Triangular Flap?", "h2"),
      createBlock("An electronic mail message is a packet of binary ASCII bytes routed over SMTP port 587 through fiber optic undersea cables. It has no physical mass, no glue, and no folded paper corners."),
      createBlock("Yet across every mail client on earth (Gmail, Apple Mail, Outlook), the symbol for email is a classic rectangular paper envelope with an inverted triangular flap. Why did this specific form become immortal?"),
      createBlock("1. The Affordance of Privacy and Containment", "h3"),
      createBlock("Before the invention of the envelope in the 1830s, postal letters were folded sheets of paper sealed with hot wax. The envelope represented a revolutionary social contract: **Privacy.** It meant no postal carrier or intermediary could read the contents without visibly breaking the seal."),
      createBlock("When digital mail was introduced, designers needed to convey that your private message was secure, addressed to a specific person, and contained inside a digital vessel. The envelope was the most trusted visual metaphor in human communication."),
    ],
  },

  // 36. WHY CONTRAST MAKES DESIGNS IMPOSSIBLE TO IGNORE (VON RESTORFF)
  {
    _id: "blog-ai-driven-hyper-personalization",
    title: "Why Does Contrast Make Some Designs Completely Impossible to Ignore?",
    title_az: "Kontrast Niyə Bəzi Dizaynları Görməzdən Gəlməyi İmkansız Edir?",
    slug: { _type: "slug", current: "why-contrast-makes-designs-impossible-to-ignore-von-restorff" },
    slug_az: { _type: "slug", current: "kontrast-ve-von-restorff-effekti" },
    originalSlug: "ai-driven-hyper-personalization",
    category: "Design Psychology",
    category_az: "Dizayn Psixologiyası",
    excerpt: "Hedwig von Restorff's Isolation Effect: How the human visual cortex processes anomalies, salience maps, and why breaking visual patterns forces instant focus.",
    excerpt_az: "Hedwig von Restorff-un Təcrid Effekti: Vizual qabıq anomaliyaları necə emal edir və mövcud vizual naxışı qırmaq niyə ani diqqət cəlb edir.",
    coverImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "image-1a3d1f53d55118b62ae943f0c62fdb20945e4129-1600x1067-jpg" },
      alt: "Minimal conceptual visual demonstrating the Von Restorff isolation effect and visual contrast",
      url: "https://cdn.sanity.io/images/0lqwkcmg/production/1a3d1f53d55118b62ae943f0c62fdb20945e4129-1600x1067.jpg",
    },
    publishDate: "2026-05-14",
    readTime: "8 min read",
    featured: false,
    tags: ["Contrast", "Von Restorff Effect", "Visual Salience", "Design Psychology", "UI Focus"],
    body: [
      createBlock("Why Does Contrast Make Some Designs Completely Impossible to Ignore?", "h2"),
      createBlock("In 1933, German pediatrician and psychologist Hedwig von Restorff conducted a series of memory experiments. She presented participants with a long list of similar items (such as two-digit numbers) with a single unexpected outlier (such as a three-letter word printed in bold red)."),
      createBlock("When tested, participants remembered the outlier at a rate over 400% higher than the surrounding items. This phenomenon became known in cognitive science as the **Von Restorff Isolation Effect**."),
      createBlock("1. The Evolutionary Salience Map", "h3"),
      createBlock("Our visual cortex generates a subconscious 'Salience Map' of our environment. Because the brain cannot process all visual stimuli simultaneously, it uses neural inhibition to suppress redundant visual information (a field of uniform green grass) while sounding an immediate alarm when it detects an anomalous contrast spike (a bright yellow flower or a predator's eye)."),
      createBlock("In digital product design, contrast is the primary lever of user action. A call-to-action button that uses an accent color found nowhere else on the page creates an intentional visual anomaly that the human eye cannot physically ignore."),
    ],
  },

  // 37. PSYCHOLOGY OF DARK MODE
  {
    _id: "blog-dark-mode-ui-architecture",
    title: "The Psychology of Dark Mode: Why Developers and Night Owls Love OLED Blacks",
    title_az: "Qaranlıq Rejim Psixologiyası: Proqramçılar Niyə OLED Qaralarını Bu Qədər Sevir?",
    slug: { _type: "slug", current: "psychology-of-dark-mode-oled-black-ui" },
    slug_az: { _type: "slug", current: "qaranliq-rejim-psixologiyasi-oled" },
    originalSlug: "dark-mode-ui-architecture",
    category: "Design Psychology",
    category_az: "Dizayn Psixologiyası",
    excerpt: "CRT phosphor nostalgia, photopic vs scotopic vision, and the aesthetic elevation of neon syntax: Why dark mode conquered IDEs, code editors, and luxury mobile apps.",
    excerpt_az: "Köhnə CRT monitor nostaljisi, görmə biologiyası və parlaq sintaksisin estetik cazibəsi: Qaranlıq rejimin proqramçıları və istifadəçiləri necə fəth etdiyi.",
    coverImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "image-82058b1f1694dc6bcdcb5b60922023a474924664-1600x1067-jpg" },
      alt: "Cinematic visual showing luminous syntax and color contrast emerging from true OLED black",
      url: "https://cdn.sanity.io/images/0lqwkcmg/production/82058b1f1694dc6bcdcb5b60922023a474924664-1600x1067.jpg",
    },
    publishDate: "2026-05-16",
    readTime: "8 min read",
    featured: false,
    tags: ["Dark Mode", "OLED UI", "Visual Ergonomics", "Developer Culture", "Color Contrast"],
    body: [
      createBlock("The Psychology of Dark Mode: Why Developers and Night Owls Love OLED Blacks", "h2"),
      createBlock("In the 1970s, every computer screen on earth was dark mode. Early cathode-ray tubes (CRTs) could only illuminate individual green or amber phosphor pixels against a dark vacuum tube."),
      createBlock("When Apple and Xerox introduced the desktop metaphor in the 1980s, they flipped screens to blinding white to imitate physical paper. Yet forty years later, developers, designers, and millions of everyday users have enthusiastically retreated back into the dark."),
      createBlock("1. Visual Ergonomics in Low-Ambient Environments", "h3"),
      createBlock("Staring at a 500-nit white screen in a dimly lit room forces the human pupil to constrict, causing ciliary muscle fatigue. Dark mode reduces overall luminous flux, easing photopic glare and preventing eye strain during 12-hour coding marathons."),
      createBlock("2. The Aesthetic Elevation of Contrast", "h3"),
      createBlock("Against a deep OLED black canvas (`#000000` or `#0a0a0c`), colors do not merely appear—they *glow*. Neon accents, syntax tokens, and glowing gradients feel vibrant, high-tech, and cinematic, creating an immersive flow state that light mode can rarely match."),
    ],
  },

  // 38. GESTALT PROXIMITY & VISUAL CHUNKING
  {
    _id: "blog-design-tokens-and-system-architecture",
    title: "Why Do We Group Things Together? (The Secret Power of Gestalt Proximity)",
    title_az: "Biz Niyə Əşyaları Qruplaşdırırıq? (Gestalt Yaxınlıq Qanununun Gizli Gücü)",
    slug: { _type: "slug", current: "why-we-group-things-together-gestalt-proximity" },
    slug_az: { _type: "slug", current: "gestalt-yaxinliq-qanunu-ve-qruplasma" },
    originalSlug: "design-tokens-and-system-architecture",
    category: "Design Psychology",
    category_az: "Dizayn Psixologiyası",
    excerpt: "Max Wertheimer's 1923 Gestalt law of proximity: How spatial spacing between input labels, buttons, and cards creates invisible cognitive clusters.",
    excerpt_az: "Max Wertheimer-in 1923-cü il Gestalt yaxınlıq qanunu: Elementlər arasındakı məsafənin beyində görünməz məntiqi qruplar yaratması.",
    coverImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "image-35f291a056702bbc7354aee2e0378a7ab73a9781-1600x1067-jpg" },
      alt: "Gestalt psychology geometric composition illustrating the law of proximity and visual grouping",
      url: "https://cdn.sanity.io/images/0lqwkcmg/production/35f291a056702bbc7354aee2e0378a7ab73a9781-1600x1067.jpg",
    },
    publishDate: "2026-05-18",
    readTime: "8 min read",
    featured: false,
    tags: ["Gestalt Psychology", "Proximity", "UI Layout", "Visual Chunking", "Spatial Hierarchy"],
    body: [
      createBlock("Why Do We Group Things Together? (The Secret Power of Gestalt Proximity)", "h2"),
      createBlock("In 1923, founder of Gestalt psychology Max Wertheimer published his foundational research on perceptual organization. He placed a series of uniform black dots on a white paper. When the dots were spaced evenly, viewers saw a single mass. But the second he pushed pairs of dots closer together, viewers instantly perceived distinct couples."),
      createBlock("This is the **Law of Proximity**: Objects that are physically close to each other are perceived as sharing a common function or identity."),
      createBlock("1. The Most Common UI Bug: The Floating Label", "h3"),
      createBlock("Look at a poorly designed form: An input label sits equidistant between the input box above it and the input box below it (e.g., 16px margin top and 16px margin bottom). The user's visual cortex experiences a micro-second of confusion: *'Does this label describe the box above or the box below?'*"),
      createBlock("Master UI designers use mathematical proximity ratios: An input label should have an 8px margin to its corresponding field, and a 24px margin to the preceding unrelated field. Proximity establishes instant, unmistakable cognitive grouping without needing a single border line."),
    ],
  },

  // 39. THE PSYCHOLOGY OF GOOGLE SEARCH
  {
    _id: "blog-seo-fundamentals-for-creatives",
    title: "The Psychology of Search Interfaces: Why Position Dictates Perceived Authority",
    title_az: "Axtarış İnterfeyslərinin Psixologiyası: Mövqe Niyə Nüfuz Təsiri Yaradır?",
    slug: { _type: "slug", current: "psychology-of-google-search-position-bias" },
    slug_az: { _type: "slug", current: "google-axtaris-ve-movqe-psixologiyasi" },
    originalSlug: "seo-fundamentals-for-creatives",
    category: "Design Psychology",
    category_az: "Dizayn Psixologiyası",
    excerpt: "The evolution of search ergonomics: From the 2005 Golden Triangle to modern pinball scanning, AI overviews, and how human cognitive offloading turns ranking position into instant authority.",
    excerpt_az: "Axtarış erqonomikasının təkamülü: 2005-ci ilin Qızıl Üçbucağından müasir pinbol skanerinə, süni intellekt icmallarına və mövqenin necə ani güvən yaratmasına dair elmi təhlil.",
    coverImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "image-7a074d507caea12c94707fce0faa49c9f75acbd1-1600x1067-jpg" },
      alt: "Conceptual visual hierarchy diagram illustrating search engine interface perception and eye scanning patterns",
      url: "https://cdn.sanity.io/images/0lqwkcmg/production/7a074d507caea12c94707fce0faa49c9f75acbd1-1600x1067.jpg",
    },
    publishDate: "2026-05-20",
    readTime: "11 min read",
    featured: true,
    tags: ["Search Psychology", "Position Bias", "Cognitive Offloading", "Authority Heuristic", "SERP Ergonomics", "Eye Tracking"],
    body: [
      createBlock("The Psychology of Search Interfaces: Why Position Dictates Perceived Authority", "h2"),
      createBlock("Type a complex technical question or clinical symptom into a search engine. Within 200 milliseconds, an index returns hundreds of thousands of candidate documents. The overwhelming majority of users will click the first or second link without ever evaluating the remaining options."),
      createBlock("Why do human beings place nearly absolute cognitive trust in the topmost ranking position of an automated software index?"),

      createBlock("1. From the 'Golden Triangle' to the Pinball Scanning Era", "h3"),
      createBlock("In 2005, early eye-tracking research (notably the pioneering Enquiro/Did-it study) revealed the rigid 'Google Golden Triangle': user gaze locked onto the top-left corner of the traditional 10-blue-link page in a strict F-shaped scanning pattern."),
      createBlock("In modern multi-modal search interfaces, eye-tracking demonstrates an evolution into what researchers call the **Pinball Pattern**: gaze bounces non-linearly between interactive rich cards, People Also Ask accordions, video carousels, and AI-generated synthesis summaries. Yet despite this visual complexity, position bias remains extraordinarily resilient: top placement continues to capture the dominant share of non-ad interactions."),

      createBlock("2. Cognitive Offloading & The Authority Heuristic", "h3"),
      createBlock("In Daniel Kahneman's dual-system framework of cognition, active verification is mentally expensive (System 2 thinking). Reading five competing technical articles to determine which author possesses superior engineering rigor requires sustained working memory and skepticism."),
      createBlock("Over decades of highly reliable search results, human users developed a powerful adaptive shortcut: **Cognitive Offloading**. Users outsource the exhausting task of editorial vetting to the ranking engine, operating on the subconscious heuristic: *'If the system placed this at the top, millions of algorithmic signals have already validated its accuracy.'*"),

      createBlock("3. The Snippet as a Trust Anchor (Cognitive Fluency)", "h3"),
      createBlock("While ranking position guarantees visual impressions, the snippet architecture dictates whether impressions convert into clicks:"),
      createBlock("• Cognitive Fluency: When a title and meta description directly mirror the user's underlying search intent with concise, precise terminology, the brain experiences instant cognitive ease, accelerating the decision to click."),
      createBlock("• The Jargon Hesitation: When a snippet is stuffed with clumsy keyword repetitions or vague marketing hype, the user experiences cognitive friction, bypassing position #1 in search of a clearer specialist source."),

      createBlock("4. Design Implications for Modern Knowledge Ecosystems", "h3"),
      createBlock("For designers, technical writers, and content architects, understanding search psychology reveals crucial interface principles:"),
      createBlock("• Structure Content for Immediate Intent Resolution: Lead with concrete answers, formulas, or code snippets before expanding into historical or theoretical context."),
      createBlock("• Treat Metadata as an Executive Summary: Write titles and descriptions not as keyword stuffing buckets, but as authoritative diagnostic summaries that resolve user ambiguity in under 3 seconds."),
      createBlock("• Respect Scannability: Use descriptive subheadings, structured tables, and bolded anchor terms so readers navigating from search can verify relevance in a single visual pass."),
    ],
  },
];
